package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class ACCTicketComm_t implements XdrAble {
    public TicketType_t TicketType;
    public TicketLogicalID_t TicketLogicalID;
    public TicketPhyID_t TicketPhyID;
    public int TestFlag;
    public SAMID_t TicketSAMID;
    public TicketSN_t TicketSN;
    public ValueCent_t valuePreTx;
    public Date2_t EndValidDate;

    public ACCTicketComm_t() {
    }

    public ACCTicketComm_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        TicketType.xdrEncode(xdr);
        TicketLogicalID.xdrEncode(xdr);
        TicketPhyID.xdrEncode(xdr);
        xdr.xdrEncodeInt(TestFlag);
        TicketSAMID.xdrEncode(xdr);
        TicketSN.xdrEncode(xdr);
        valuePreTx.xdrEncode(xdr);
        EndValidDate.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        TicketType = new TicketType_t(xdr);
        TicketLogicalID = new TicketLogicalID_t(xdr);
        TicketPhyID = new TicketPhyID_t(xdr);
        TestFlag = xdr.xdrDecodeInt();
        TicketSAMID = new SAMID_t(xdr);
        TicketSN = new TicketSN_t(xdr);
        valuePreTx = new ValueCent_t(xdr);
        EndValidDate = new Date2_t(xdr);
    }

}
// End of ACCTicketComm_t.java
