package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class AddBlackList_t implements XdrAble {
    public TicketPhyID_t ticketPhyID;
    public U8_t maintainFlag;
    public U8_t processFlag;

    public AddBlackList_t() {
    }

    public AddBlackList_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        ticketPhyID.xdrEncode(xdr);
        maintainFlag.xdrEncode(xdr);
        processFlag.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        ticketPhyID = new TicketPhyID_t(xdr);
        maintainFlag = new U8_t(xdr);
        processFlag = new U8_t(xdr);
    }

}
// End of AddBlackList_t.java
