package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class AdjustFile_t implements XdrAble {
    public java.lang.String fileName;
    public U32_t totalTxCount;
    public AdjustTx_t[] adjustTxList;

    public AdjustFile_t() {
    }

    public AdjustFile_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeString(fileName);
        totalTxCount.xdrEncode(xdr);
        { int $size = adjustTxList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { adjustTxList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        fileName = xdr.xdrDecodeString();
        totalTxCount = new U32_t(xdr);
        { int $size = xdr.xdrDecodeInt(); adjustTxList = new AdjustTx_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { adjustTxList[$idx] = new AdjustTx_t(xdr); } }
    }

}
// End of AdjustFile_t.java
