package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class AdvContentNew_t implements XdrAble {
    public U16_t advId;
    public java.lang.String advFileName;

    public AdvContentNew_t() {
    }

    public AdvContentNew_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        advId.xdrEncode(xdr);
        xdr.xdrEncodeString(advFileName);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        advId = new U16_t(xdr);
        advFileName = xdr.xdrDecodeString();
    }

}
// End of AdvContentNew_t.java
