package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class AdvPlayMethodNew_t implements XdrAble {
    public U16_t methodId;
    public U16_t timeToAdv;

    public AdvPlayMethodNew_t() {
    }

    public AdvPlayMethodNew_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        methodId.xdrEncode(xdr);
        timeToAdv.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        methodId = new U16_t(xdr);
        timeToAdv = new U16_t(xdr);
    }

}
// End of AdvPlayMethodNew_t.java
