package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class AGMAR_t implements XdrAble {
    public U32_t TicketCountInBox1;
    public U32_t TicketCountInBox2;
    public GateProcessStatByType_t [] GateProcessStatByType;

    public AGMAR_t() {
    }

    public AGMAR_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        TicketCountInBox1.xdrEncode(xdr);
        TicketCountInBox2.xdrEncode(xdr);
        { int $size = GateProcessStatByType.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { GateProcessStatByType[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        TicketCountInBox1 = new U32_t(xdr);
        TicketCountInBox2 = new U32_t(xdr);
        { int $size = xdr.xdrDecodeInt(); GateProcessStatByType = new GateProcessStatByType_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { GateProcessStatByType[$idx] = new GateProcessStatByType_t(xdr); } }
    }

}
// End of AGMAR_t.java
