package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class AlarmLampData_t implements XdrAble {
    public U16_t blackListLampFlag;
    public U16_t blackListVoiceFlag;
    public U16_t invalidCardLampFlag;
    public U16_t invalidCardVoiceFlag;
    public U16_t breakinLampFlag;
    public U16_t breakinVoiceFlag;

    public AlarmLampData_t() {
    }

    public AlarmLampData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        blackListLampFlag.xdrEncode(xdr);
        blackListVoiceFlag.xdrEncode(xdr);
        invalidCardLampFlag.xdrEncode(xdr);
        invalidCardVoiceFlag.xdrEncode(xdr);
        breakinLampFlag.xdrEncode(xdr);
        breakinVoiceFlag.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        blackListLampFlag = new U16_t(xdr);
        blackListVoiceFlag = new U16_t(xdr);
        invalidCardLampFlag = new U16_t(xdr);
        invalidCardVoiceFlag = new U16_t(xdr);
        breakinLampFlag = new U16_t(xdr);
        breakinVoiceFlag = new U16_t(xdr);
    }

}
// End of AlarmLampData_t.java
