package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class ARCommNew_t implements XdrAble {
    public AFCTime_t TransactionDateTime;
    public DeviceID_t DeviceID;
    public SN_t UDSNStart;
    public SN_t UDSNEnd;
    public SN_t YKTSNStart;
    public SN_t YKTSNEnd;
    public SN_t SVTCPUSNStart;
    public SN_t SVTCPUSNEnd;
    public SN_t JRICSNStart;
    public SN_t JRICSNEnd;
    public SN_t JTBSNStart;
    public SN_t JTBSNEnd;
    public SN_t GJICSNStart;
    public SN_t GJICSNEnd;
    public U32_t[] Rsvd;

    public ARCommNew_t() {
    }

    public ARCommNew_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        TransactionDateTime.xdrEncode(xdr);
        DeviceID.xdrEncode(xdr);
        UDSNStart.xdrEncode(xdr);
        UDSNEnd.xdrEncode(xdr);
        YKTSNStart.xdrEncode(xdr);
        YKTSNEnd.xdrEncode(xdr);
        SVTCPUSNStart.xdrEncode(xdr);
        SVTCPUSNEnd.xdrEncode(xdr);
        JRICSNStart.xdrEncode(xdr);
        JRICSNEnd.xdrEncode(xdr);
        JTBSNStart.xdrEncode(xdr);
        JTBSNEnd.xdrEncode(xdr);
        GJICSNStart.xdrEncode(xdr);
        GJICSNEnd.xdrEncode(xdr);
        { int $size = 4; for ( int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        TransactionDateTime = new AFCTime_t(xdr);
        DeviceID = new DeviceID_t(xdr);
        UDSNStart = new SN_t(xdr);
        UDSNEnd = new SN_t(xdr);
        YKTSNStart = new SN_t(xdr);
        YKTSNEnd = new SN_t(xdr);
        SVTCPUSNStart = new SN_t(xdr);
        SVTCPUSNEnd = new SN_t(xdr);
        JRICSNStart = new SN_t(xdr);
        JRICSNEnd = new SN_t(xdr);
        JTBSNStart = new SN_t(xdr);
        JTBSNEnd = new SN_t(xdr);
        GJICSNStart = new SN_t(xdr);
        GJICSNEnd = new SN_t(xdr);
        { int $size = 4; Rsvd = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx] = new U32_t(xdr); } }
    }

}
// End of ARCommNew_t.java
