package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class ARComm_t implements XdrAble {
    public AFCTime_t TransactionDateTime;
    public DeviceID_t DeviceID;
    public SN_t UDSNStart;
    public SN_t UDSNEnd;
    public SN_t YKTSNStart;
    public SN_t YKTSNEnd;

    public ARComm_t() {
    }

    public ARComm_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        TransactionDateTime.xdrEncode(xdr);
        DeviceID.xdrEncode(xdr);
        UDSNStart.xdrEncode(xdr);
        UDSNEnd.xdrEncode(xdr);
        YKTSNStart.xdrEncode(xdr);
        YKTSNEnd.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        TransactionDateTime = new AFCTime_t(xdr);
        DeviceID = new DeviceID_t(xdr);
        UDSNStart = new SN_t(xdr);
        UDSNEnd = new SN_t(xdr);
        YKTSNStart = new SN_t(xdr);
        YKTSNEnd = new SN_t(xdr);
    }

}
// End of ARComm_t.java
