package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Area_t implements XdrAble {
    public U16_t areaNumber;
    public U16_t areaXPos;
    public U16_t areaYPos;
    public U16_t areaWidth;
    public U16_t areaHeight;
    public InterfaceList_t[] interfaceViewList;

    public Area_t() {
    }

    public Area_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        areaNumber.xdrEncode(xdr);
        areaXPos.xdrEncode(xdr);
        areaYPos.xdrEncode(xdr);
        areaWidth.xdrEncode(xdr);
        areaHeight.xdrEncode(xdr);
        { int $size = interfaceViewList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { interfaceViewList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        areaNumber = new U16_t(xdr);
        areaXPos = new U16_t(xdr);
        areaYPos = new U16_t(xdr);
        areaWidth = new U16_t(xdr);
        areaHeight = new U16_t(xdr);
        { int $size = xdr.xdrDecodeInt(); interfaceViewList = new InterfaceList_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { interfaceViewList[$idx] = new InterfaceList_t(xdr); } }
    }

}
// End of Area_t.java
