package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
/**
 * Enumeration (collection of constants).
 */
public interface AreaTicketFlag_t {

    public static final int ATF_NoLimit = 0;
    public static final int ATF_ZoneLimit = 1;
    public static final int ATF_SectionLimit = 2;

}
// End of AreaTicketFlag_t.java
