package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class BOMAR_t implements XdrAble {
    public U32_t TicketCountInBox1;
    public U32_t TicketCountInBox2;
    public BOMProcessStatByType_t[] BOMProcessStatByType;

    public BOMAR_t() {
    }

    public BOMAR_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        TicketCountInBox1.xdrEncode(xdr);
        TicketCountInBox2.xdrEncode(xdr);
        { int $size = BOMProcessStatByType.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { BOMProcessStatByType[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        TicketCountInBox1 = new U32_t(xdr);
        TicketCountInBox2 = new U32_t(xdr);
        { int $size = xdr.xdrDecodeInt(); BOMProcessStatByType = new BOMProcessStatByType_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { BOMProcessStatByType[$idx] = new BOMProcessStatByType_t(xdr); } }
    }

}
// End of BOMAR_t.java
