package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class BOMProcessStatByType_t implements XdrAble {
    public TicketType_t TicketType;
    public U32_t CountOfSale;
    public U32_t ValueOfSale;
    public U32_t CountOfRefund;
    public U32_t ValueOfRefund;
    public U32_t CountOfUpdate;
    public U32_t ValueOfUpdate;
    public U32_t CountOfCharge;
    public U32_t ValueOfCharge;
    public U32_t CountOfBlock;

    public BOMProcessStatByType_t() {
    }

    public BOMProcessStatByType_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        TicketType.xdrEncode(xdr);
        CountOfSale.xdrEncode(xdr);
        ValueOfSale.xdrEncode(xdr);
        CountOfRefund.xdrEncode(xdr);
        ValueOfRefund.xdrEncode(xdr);
        CountOfUpdate.xdrEncode(xdr);
        ValueOfUpdate.xdrEncode(xdr);
        CountOfCharge.xdrEncode(xdr);
        ValueOfCharge.xdrEncode(xdr);
        CountOfBlock.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        TicketType = new TicketType_t(xdr);
        CountOfSale = new U32_t(xdr);
        ValueOfSale = new U32_t(xdr);
        CountOfRefund = new U32_t(xdr);
        ValueOfRefund = new U32_t(xdr);
        CountOfUpdate = new U32_t(xdr);
        ValueOfUpdate = new U32_t(xdr);
        CountOfCharge = new U32_t(xdr);
        ValueOfCharge = new U32_t(xdr);
        CountOfBlock = new U32_t(xdr);
    }

}
// End of BOMProcessStatByType_t.java
