package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class ButtonView_t implements XdrAble {
    public U8_t effectStatus;
    public String cnEffectFileName;
    public String enEffectFileName;

    public ButtonView_t() {
    }

    public ButtonView_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        effectStatus.xdrEncode(xdr);
        xdr.xdrEncodeString(cnEffectFileName);
        xdr.xdrEncodeString(enEffectFileName);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        effectStatus = new U8_t(xdr);
        cnEffectFileName = xdr.xdrDecodeString();
        enEffectFileName = xdr.xdrDecodeString();
    }

}
// End of ButtonView_t.java
