package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class CalendarTime_t implements XdrAble {
    public TimeIntervalID_t timeID;
    public SecondsSinceMidNight_t startTime;
    public SecondsSinceMidNight_t endTime;

    public CalendarTime_t() {
    }

    public CalendarTime_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        timeID.xdrEncode(xdr);
        startTime.xdrEncode(xdr);
        endTime.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        timeID = new TimeIntervalID_t(xdr);
        startTime = new SecondsSinceMidNight_t(xdr);
        endTime = new SecondsSinceMidNight_t(xdr);
    }

}
// End of CalendarTime_t.java
