package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class CalendarDate_t implements XdrAble {
    public Date2_t dateID;
    public DateTypeID_t dateTypeId;

    public CalendarDate_t() {
    }

    public CalendarDate_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        dateID.xdrEncode(xdr);
        dateTypeId.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        dateID = new Date2_t(xdr);
        dateTypeId = new DateTypeID_t(xdr);
    }

}
// End of CalendarDate_t.java
