package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class CalendarHold_t implements XdrAble {
    public FareTier_t fareTierID;
    public Seconds_t holdTimeValue;

    public CalendarHold_t() {
    }

    public CalendarHold_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        fareTierID.xdrEncode(xdr);
        holdTimeValue.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        fareTierID = new FareTier_t(xdr);
        holdTimeValue = new Seconds_t(xdr);
    }

}
// End of CalendarHold_t.java
