package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class CashBoxData_t implements XdrAble {
    public U32_t typeOfBankNoteInSale;
    public U16_t maxCountOfBankNoteInSale;
    public U16_t maxValueOfBankNoteInSale;
    public U32_t typeOfBankNoteInDeposit;
    public U16_t maxCountOfBankNoteInDeposit;
    public U16_t maxValueOfBankNoteInDeposit;
    public U8_t flagOfServiceInNoCoin;
    public U8_t maxCountOfCoinAccept;
    public U8_t maxCountOfCoinChange;
    public U8_t flagOfBNChangeInSale;
    public U8_t maxCountOfBNChange;
    public U8_t maxValueOfBNChange;
    public U16_t timeOfTnxCancel;
    public U8_t flagOfStandbyPic;
    public U16_t switchTimeOfStandby;
    public U16_t banknoteCountUptoFull;
    public U16_t banknoteCountFulled;
    public U16_t coinBoxCountUptoFull;
    public U16_t coinBoxCountFulled;
    public U16_t coinChangeCountUptoEmpty;
    public U16_t minTicketCountInService;
    public U16_t BNChangeCountUptoEmpty;

    public CashBoxData_t() {
    }

    public CashBoxData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        typeOfBankNoteInSale.xdrEncode(xdr);
        maxCountOfBankNoteInSale.xdrEncode(xdr);
        maxValueOfBankNoteInSale.xdrEncode(xdr);
        typeOfBankNoteInDeposit.xdrEncode(xdr);
        maxCountOfBankNoteInDeposit.xdrEncode(xdr);
        maxValueOfBankNoteInDeposit.xdrEncode(xdr);
        flagOfServiceInNoCoin.xdrEncode(xdr);
        maxCountOfCoinAccept.xdrEncode(xdr);
        maxCountOfCoinChange.xdrEncode(xdr);
        flagOfBNChangeInSale.xdrEncode(xdr);
        maxCountOfBNChange.xdrEncode(xdr);
        maxValueOfBNChange.xdrEncode(xdr);
        timeOfTnxCancel.xdrEncode(xdr);
        flagOfStandbyPic.xdrEncode(xdr);
        switchTimeOfStandby.xdrEncode(xdr);
        banknoteCountUptoFull.xdrEncode(xdr);
        banknoteCountFulled.xdrEncode(xdr);
        coinBoxCountUptoFull.xdrEncode(xdr);
        coinBoxCountFulled.xdrEncode(xdr);
        coinChangeCountUptoEmpty.xdrEncode(xdr);
        minTicketCountInService.xdrEncode(xdr);
        BNChangeCountUptoEmpty.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        typeOfBankNoteInSale = new U32_t(xdr);
        maxCountOfBankNoteInSale = new U16_t(xdr);
        maxValueOfBankNoteInSale = new U16_t(xdr);
        typeOfBankNoteInDeposit = new U32_t(xdr);
        maxCountOfBankNoteInDeposit = new U16_t(xdr);
        maxValueOfBankNoteInDeposit = new U16_t(xdr);
        flagOfServiceInNoCoin = new U8_t(xdr);
        maxCountOfCoinAccept = new U8_t(xdr);
        maxCountOfCoinChange = new U8_t(xdr);
        flagOfBNChangeInSale = new U8_t(xdr);
        maxCountOfBNChange = new U8_t(xdr);
        maxValueOfBNChange = new U8_t(xdr);
        timeOfTnxCancel = new U16_t(xdr);
        flagOfStandbyPic = new U8_t(xdr);
        switchTimeOfStandby = new U16_t(xdr);
        banknoteCountUptoFull = new U16_t(xdr);
        banknoteCountFulled = new U16_t(xdr);
        coinBoxCountUptoFull = new U16_t(xdr);
        coinBoxCountFulled = new U16_t(xdr);
        coinChangeCountUptoEmpty = new U16_t(xdr);
        minTicketCountInService = new U16_t(xdr);
        BNChangeCountUptoEmpty = new U16_t(xdr);
    }

}
// End of CashBoxData_t.java
