package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class ClearDetailBodyData_t implements XdrAble {
    public Date2_t settleDate;
    public LineID_t lineID;
    public CorrectTicketProfit_t[] correctTicketProfitlist;
    public DoubtTicketProfit_t[] doubtTicketProfitlist;

    public ClearDetailBodyData_t() {
    }

    public ClearDetailBodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        settleDate.xdrEncode(xdr);
        lineID.xdrEncode(xdr);
        { int $size = correctTicketProfitlist.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { correctTicketProfitlist[$idx].xdrEncode(xdr); } }
        { int $size = doubtTicketProfitlist.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { doubtTicketProfitlist[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        settleDate = new Date2_t(xdr);
        lineID = new LineID_t(xdr);
        { int $size = xdr.xdrDecodeInt(); correctTicketProfitlist = new CorrectTicketProfit_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { correctTicketProfitlist[$idx] = new CorrectTicketProfit_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); doubtTicketProfitlist = new DoubtTicketProfit_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { doubtTicketProfitlist[$idx] = new DoubtTicketProfit_t(xdr); } }
    }

}
// End of ClearDetailBodyData_t.java
