package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class ClearBodyData_t implements XdrAble {
    public Date2_t settleDate;
    public LineID_t lineID;
    public S32_t yptRideTxCount;
    public S32_t yptRideTxValue;
    public S32_t yptRideTxIncome;
    public S32_t yktRideTxCount;
    public S32_t yktRideTxValue;
    public S32_t yktRideTxSettledValue;
    public S32_t saleTxCount;
    public S32_t saleTxIncome;
    public S32_t chargeTxCount;
    public S32_t chargeTxIncome;
    public S32_t exchangeTxCount;
    public S32_t exchangeTxIncome;
    public S32_t refundTxCount;
    public S32_t refundTxIncome;
    public S32_t updateTxCount;
    public S32_t updateTxIncome;
    public S32_t SVTCPURideTxCount;
    public S32_t SVTCPURideTxValue;
    public S32_t SVTCPURideTxSettledValue;
    public S32_t JRICRideTxCount;
    public S32_t JRICRideTxValue;
    public S32_t JRICRideTxSettledValue;
    public S32_t JTBRideTxCount;
    public S32_t JTBRideTxValue;
    public S32_t JTBRideTxSettledValue;
    public S32_t GJICRideTxCount;
    public S32_t GJICRideTxValue;
    public S32_t GJICRideTxSettledValue;
    public S32_t QRRideTxCount;
    public S32_t QRRideTxValue;
    public S32_t QRRideTxSettledValue;
    public S32_t FCRideTxCount;
    public S32_t FCRideTxValue;
    public S32_t FCRideTxSettledValue;
    public S32_t[] Rsvd;

    public ClearBodyData_t() {
    }

    public ClearBodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        settleDate.xdrEncode(xdr);
        lineID.xdrEncode(xdr);
        yptRideTxCount.xdrEncode(xdr);
        yptRideTxValue.xdrEncode(xdr);
        yptRideTxIncome.xdrEncode(xdr);
        yktRideTxCount.xdrEncode(xdr);
        yktRideTxValue.xdrEncode(xdr);
        yktRideTxSettledValue.xdrEncode(xdr);
        saleTxCount.xdrEncode(xdr);
        saleTxIncome.xdrEncode(xdr);
        chargeTxCount.xdrEncode(xdr);
        chargeTxIncome.xdrEncode(xdr);
        exchangeTxCount.xdrEncode(xdr);
        exchangeTxIncome.xdrEncode(xdr);
        refundTxCount.xdrEncode(xdr);
        refundTxIncome.xdrEncode(xdr);
        updateTxCount.xdrEncode(xdr);
        updateTxIncome.xdrEncode(xdr);
        SVTCPURideTxCount.xdrEncode(xdr);
        SVTCPURideTxValue.xdrEncode(xdr);
        SVTCPURideTxSettledValue.xdrEncode(xdr);
        JRICRideTxCount.xdrEncode(xdr);
        JRICRideTxValue.xdrEncode(xdr);
        JRICRideTxSettledValue.xdrEncode(xdr);
        JTBRideTxCount.xdrEncode(xdr);
        JTBRideTxValue.xdrEncode(xdr);
        JTBRideTxSettledValue.xdrEncode(xdr);
        GJICRideTxCount.xdrEncode(xdr);
        GJICRideTxValue.xdrEncode(xdr);
        GJICRideTxSettledValue.xdrEncode(xdr);
        QRRideTxCount.xdrEncode(xdr);
        QRRideTxValue.xdrEncode(xdr);
        QRRideTxSettledValue.xdrEncode(xdr);
        FCRideTxCount.xdrEncode(xdr);
        FCRideTxValue.xdrEncode(xdr);
        FCRideTxSettledValue.xdrEncode(xdr);
        { int $size = 6; for ( int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        settleDate = new Date2_t(xdr);
        lineID = new LineID_t(xdr);
        yptRideTxCount = new S32_t(xdr);
        yptRideTxValue = new S32_t(xdr);
        yptRideTxIncome = new S32_t(xdr);
        yktRideTxCount = new S32_t(xdr);
        yktRideTxValue = new S32_t(xdr);
        yktRideTxSettledValue = new S32_t(xdr);
        saleTxCount = new S32_t(xdr);
        saleTxIncome = new S32_t(xdr);
        chargeTxCount = new S32_t(xdr);
        chargeTxIncome = new S32_t(xdr);
        exchangeTxCount = new S32_t(xdr);
        exchangeTxIncome = new S32_t(xdr);
        refundTxCount = new S32_t(xdr);
        refundTxIncome = new S32_t(xdr);
        updateTxCount = new S32_t(xdr);
        updateTxIncome = new S32_t(xdr);
        SVTCPURideTxCount = new S32_t(xdr);
        SVTCPURideTxValue = new S32_t(xdr);
        SVTCPURideTxSettledValue = new S32_t(xdr);
        JRICRideTxCount = new S32_t(xdr);
        JRICRideTxValue = new S32_t(xdr);
        JRICRideTxSettledValue = new S32_t(xdr);
        JTBRideTxCount = new S32_t(xdr);
        JTBRideTxValue = new S32_t(xdr);
        JTBRideTxSettledValue = new S32_t(xdr);
        GJICRideTxCount = new S32_t(xdr);
        GJICRideTxValue = new S32_t(xdr);
        GJICRideTxSettledValue = new S32_t(xdr);
        QRRideTxCount = new S32_t(xdr);
        QRRideTxValue = new S32_t(xdr);
        QRRideTxSettledValue = new S32_t(xdr);
        FCRideTxCount = new S32_t(xdr);
        FCRideTxValue = new S32_t(xdr);
        FCRideTxSettledValue = new S32_t(xdr);
        { int $size = 6; Rsvd = new S32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx] = new S32_t(xdr); } }
    }

}
// End of ClearBodyData_t.java
