package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class CurrentDateTimeDisplay_t implements XdrAble {
    public U16_t timeXPos;
    public U16_t timeYPos;
    public U16_t timeWidth;
    public U16_t timeHeight;
    public U16_t stationXPos;
    public U16_t stationYPos;
    public U16_t stationWidth;
    public U16_t stationHeight;

    public CurrentDateTimeDisplay_t() {
    }

    public CurrentDateTimeDisplay_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        timeXPos.xdrEncode(xdr);
        timeYPos.xdrEncode(xdr);
        timeWidth.xdrEncode(xdr);
        timeHeight.xdrEncode(xdr);
        stationXPos.xdrEncode(xdr);
        stationYPos.xdrEncode(xdr);
        stationWidth.xdrEncode(xdr);
        stationHeight.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        timeXPos = new U16_t(xdr);
        timeYPos = new U16_t(xdr);
        timeWidth = new U16_t(xdr);
        timeHeight = new U16_t(xdr);
        stationXPos = new U16_t(xdr);
        stationYPos = new U16_t(xdr);
        stationWidth = new U16_t(xdr);
        stationHeight = new U16_t(xdr);
    }

}
// End of CurrentDateTimeDisplay_t.java
