package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class CustomAlarmLampData_t implements XdrAble {
    public U8_t ticketIssueCompany;
    public U16_t ticketType;
    public U16_t lampFlag;
    public U16_t voiceFlag;

    public CustomAlarmLampData_t() {
    }

    public CustomAlarmLampData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        ticketIssueCompany.xdrEncode(xdr);
        ticketType.xdrEncode(xdr);
        lampFlag.xdrEncode(xdr);
        voiceFlag.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        ticketIssueCompany = new U8_t(xdr);
        ticketType = new U16_t(xdr);
        lampFlag = new U16_t(xdr);
        voiceFlag = new U16_t(xdr);
    }

}
// End of CustomAlarmLampData_t.java
