package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class CustomDisplayArea_t implements XdrAble {
    public U16_t areaNumber;
    public U16_t linkId;
    public U16_t linkXPos;
    public U16_t linkYPos;
    public U16_t linkWidth;
    public U16_t linkHeight;
    public U8_t useFlag;

    public CustomDisplayArea_t() {
    }

    public CustomDisplayArea_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        areaNumber.xdrEncode(xdr);
        linkId.xdrEncode(xdr);
        linkXPos.xdrEncode(xdr);
        linkYPos.xdrEncode(xdr);
        linkWidth.xdrEncode(xdr);
        linkHeight.xdrEncode(xdr);
        useFlag.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        areaNumber = new U16_t(xdr);
        linkId = new U16_t(xdr);
        linkXPos = new U16_t(xdr);
        linkYPos = new U16_t(xdr);
        linkWidth = new U16_t(xdr);
        linkHeight = new U16_t(xdr);
        useFlag = new U8_t(xdr);
    }

}
// End of CustomDisplayArea_t.java
