package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
/**
 * Enumeration (collection of constants).
 */
public interface DeviceType_t {

    public static final int DT_ES = 0x00;
    public static final int DT_TVM = 0x01;
    public static final int DT_BOM = 0x02;
    public static final int DT_CUS = 0x03;
    public static final int DT_TCM = 0x04;
    public static final int DT_PCA = 0x05;
    public static final int DT_AGM = 0x06;
    public static final int DT_TFM = 0x07;
    public static final int DT_Server = 0x11;
    public static final int DT_Workstation = 0x12;
    public static final int DT_Network = 0x13;
    public static final int DT_UPS = 0x14;
    public static final int DT_APP = 0x15;

}
// End of DeviceType_t.java
