package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
/**
 * Enumeration (collection of constants).
 */
public interface DeviceSubType_t {

    public static final int DTSub_CardES = 1;
    public static final int DTSub_TokenES = 2;
    public static final int DTSub_TvmButton = 3;
    public static final int DTSub_TvmTouch = 4;
    public static final int DTSub_PaidBom = 5;
    public static final int DTSub_UnpaidBom = 6;
    public static final int DTSub_EnG = 7;
    public static final int DTSub_ExG = 8;
    public static final int DTSub_DoubleAgm = 9;
    public static final int DTSub_CUS = 10;
    public static final int DTSub_TCM = 11;
    public static final int DTSub_PCA = 12;
    public static final int DTSub_TFM = 13;
    public static final int DTSub_Server = 21;
    public static final int DTSub_Workstation = 22;
    public static final int DTSub_Swither = 23;
    public static final int DTSub_Router = 24;
    public static final int DTSub_Firewall = 25;
    public static final int DTSub_UPS = 26;
    public static final int DTSub_APP = 27;

}
// End of DeviceSubType_t.java
