package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class DoubtTicketProfit_t implements XdrAble {
    public TicketType_t TicketType;
    public U32_t reason;
    public S32_t ticketSettledValue;
    public S32_t ticketFee;
    public S32_t[] Rsvd;

    public DoubtTicketProfit_t() {
    }

    public DoubtTicketProfit_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        TicketType.xdrEncode(xdr);
        reason.xdrEncode(xdr);
        ticketSettledValue.xdrEncode(xdr);
        ticketFee.xdrEncode(xdr);
        { int $size = 12; for ( int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        TicketType = new TicketType_t(xdr);
        reason = new U32_t(xdr);
        ticketSettledValue = new S32_t(xdr);
        ticketFee = new S32_t(xdr);
        { int $size = 12; Rsvd = new S32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx] = new S32_t(xdr); } }
    }

}
// End of DoubtTicketProfit_t.java
