package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class DoubtTx_t implements XdrAble {
    public ReconcileSeqNo_t transactionSn;
    public U32_t reason;

    public DoubtTx_t() {
    }

    public DoubtTx_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        transactionSn.xdrEncode(xdr);
        reason.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        transactionSn = new ReconcileSeqNo_t(xdr);
        reason = new U32_t(xdr);
    }

}
// End of DoubtTx_t.java
