package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class EODDataTVMConfigBD_t implements XdrAble {
    public EODModuleComm_t moduleComm;
    public TicketReaderData_t tvmTicketReaderData;
    public MaintenanceData_t tvmMaintenanceData;
    public CashBoxData_t tvmCashBoxData;
    public TicketBoxData_t tvmTicketBoxData;
    public TransactionQueryData_t tvmTransactionQueryData;

    public EODDataTVMConfigBD_t() {
    }

    public EODDataTVMConfigBD_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm.xdrEncode(xdr);
        tvmTicketReaderData.xdrEncode(xdr);
        tvmMaintenanceData.xdrEncode(xdr);
        tvmCashBoxData.xdrEncode(xdr);
        tvmTicketBoxData.xdrEncode(xdr);
        tvmTransactionQueryData.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm = new EODModuleComm_t(xdr);
        tvmTicketReaderData = new TicketReaderData_t(xdr);
        tvmMaintenanceData = new MaintenanceData_t(xdr);
        tvmCashBoxData = new CashBoxData_t(xdr);
        tvmTicketBoxData = new TicketBoxData_t(xdr);
        tvmTransactionQueryData = new TransactionQueryData_t(xdr);
    }

}
// End of EODDataTVMConfigBD_t.java
