package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class EODDataPriviledgeBD_t implements XdrAble {
    public EODModuleComm_t moduleComm;
    public PriviledgeRole_t[] roleList;
    public PriviledgeUser_t[] userList;

    public EODDataPriviledgeBD_t() {
    }

    public EODDataPriviledgeBD_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm.xdrEncode(xdr);
        { int $size = roleList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { roleList[$idx].xdrEncode(xdr); } }
        { int $size = userList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { userList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm = new EODModuleComm_t(xdr);
        { int $size = xdr.xdrDecodeInt(); roleList = new PriviledgeRole_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { roleList[$idx] = new PriviledgeRole_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); userList = new PriviledgeUser_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { userList[$idx] = new PriviledgeUser_t(xdr); } }
    }

}
// End of EODDataPriviledgeBD_t.java
