package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class EODDataFareTypeBD_t implements XdrAble {
    public EODModuleComm_t moduleComm;
    public FareTypeRecord_t[] fareTypeList;

    public EODDataFareTypeBD_t() {
    }

    public EODDataFareTypeBD_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm.xdrEncode(xdr);
        { int $size = fareTypeList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { fareTypeList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm = new EODModuleComm_t(xdr);
        { int $size = xdr.xdrDecodeInt(); fareTypeList = new FareTypeRecord_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { fareTypeList[$idx] = new FareTypeRecord_t(xdr); } }
    }

}
// End of EODDataFareTypeBD_t.java
