package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class EODDataSystemBD_t implements XdrAble {
    public EODModuleComm_t moduleComm;
    public Seconds_t retryWaitTime;
    public U8_t retryCount;
    public Seconds_t connectWaitTime;
    public Seconds_t ackTimeOut;
    public U8_t unAckCount;
    public Seconds_t timeVersionCheck;
    public Seconds_t timeSynch;
    public Seconds_t timeSynchMin;
    public Seconds_t timeSynchMax;
    public Seconds_t timeUD;
    public Seconds_t timeEvent;
    public Seconds_t timeAR;
    public Seconds_t timeUDTar;
    public U16_t fileCountUDTar;

    public EODDataSystemBD_t() {
    }

    public EODDataSystemBD_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm.xdrEncode(xdr);
        retryWaitTime.xdrEncode(xdr);
        retryCount.xdrEncode(xdr);
        connectWaitTime.xdrEncode(xdr);
        ackTimeOut.xdrEncode(xdr);
        unAckCount.xdrEncode(xdr);
        timeVersionCheck.xdrEncode(xdr);
        timeSynch.xdrEncode(xdr);
        timeSynchMin.xdrEncode(xdr);
        timeSynchMax.xdrEncode(xdr);
        timeUD.xdrEncode(xdr);
        timeEvent.xdrEncode(xdr);
        timeAR.xdrEncode(xdr);
        timeUDTar.xdrEncode(xdr);
        fileCountUDTar.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm = new EODModuleComm_t(xdr);
        retryWaitTime = new Seconds_t(xdr);
        retryCount = new U8_t(xdr);
        connectWaitTime = new Seconds_t(xdr);
        ackTimeOut = new Seconds_t(xdr);
        unAckCount = new U8_t(xdr);
        timeVersionCheck = new Seconds_t(xdr);
        timeSynch = new Seconds_t(xdr);
        timeSynchMin = new Seconds_t(xdr);
        timeSynchMax = new Seconds_t(xdr);
        timeUD = new Seconds_t(xdr);
        timeEvent = new Seconds_t(xdr);
        timeAR = new Seconds_t(xdr);
        timeUDTar = new Seconds_t(xdr);
        fileCountUDTar = new U16_t(xdr);
    }

}
// End of EODDataSystemBD_t.java
