package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class EODDataTopoBD_t implements XdrAble {
    public EODModuleComm_t moduleComm;
    public LineInfo_t[] lineInfoList;
    public StationInfo_t[] stationInfoList;
    public ExchangeInfo_t[] exchangeInfoList;

    public EODDataTopoBD_t() {
    }

    public EODDataTopoBD_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm.xdrEncode(xdr);
        { int $size = lineInfoList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { lineInfoList[$idx].xdrEncode(xdr); } }
        { int $size = stationInfoList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { stationInfoList[$idx].xdrEncode(xdr); } }
        { int $size = exchangeInfoList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { exchangeInfoList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm = new EODModuleComm_t(xdr);
        { int $size = xdr.xdrDecodeInt(); lineInfoList = new LineInfo_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { lineInfoList[$idx] = new LineInfo_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); stationInfoList = new StationInfo_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { stationInfoList[$idx] = new StationInfo_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); exchangeInfoList = new ExchangeInfo_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { exchangeInfoList[$idx] = new ExchangeInfo_t(xdr); } }
    }

}
// End of EODDataTopoBD_t.java
