package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class EODDataAGMConfigBD_t implements XdrAble {
    public EODModuleComm_t moduleComm;
    public TicketReaderData_t agmTicketReaderData;
    public MaintenanceData_t agmMaintenanceData;
    public TicketBoxData_t agmTicketBoxData;
    public PassControlData_t agmPassControlData;
    public AlarmLampData_t agmAlarmLampData;
    public CustomAlarmLampData_t [] agmCustomAlarmLampData;
    public TransactionQueryData_t agmTransactionQueryData;

    public EODDataAGMConfigBD_t() {
    }

    public EODDataAGMConfigBD_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm.xdrEncode(xdr);
        agmTicketReaderData.xdrEncode(xdr);
        agmMaintenanceData.xdrEncode(xdr);
        agmTicketBoxData.xdrEncode(xdr);
        agmPassControlData.xdrEncode(xdr);
        agmAlarmLampData.xdrEncode(xdr);
        { int $size = agmCustomAlarmLampData.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { agmCustomAlarmLampData[$idx].xdrEncode(xdr); } }
        agmTransactionQueryData.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm = new EODModuleComm_t(xdr);
        agmTicketReaderData = new TicketReaderData_t(xdr);
        agmMaintenanceData = new MaintenanceData_t(xdr);
        agmTicketBoxData = new TicketBoxData_t(xdr);
        agmPassControlData = new PassControlData_t(xdr);
        agmAlarmLampData = new AlarmLampData_t(xdr);
        { int $size = xdr.xdrDecodeInt(); agmCustomAlarmLampData = new CustomAlarmLampData_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { agmCustomAlarmLampData[$idx] = new CustomAlarmLampData_t(xdr); } }
        agmTransactionQueryData = new TransactionQueryData_t(xdr);
    }

}
// End of EODDataAGMConfigBD_t.java
