package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class EODDataNewTVMUIBD_t implements XdrAble {
    public EODModuleComm_t moduleComm;
    public ResolutionInfo_t[] resolutionInfo;
    public Interface_t[] interface_t;
    public Area_t [] area;
    public TVMValueSelectionNew_t[] tvmValueSelectionNew;
    public TVMFareAreaNew_t[] tvmFareAreaNew;
    public TVMStationInAreaNew_t[] tvmStationInAreaNew;
    public TVMLineSelectionNew_t[] tvmLineSelectionNew;
    public TVMStationInLineNew_t[] tvmStationInLineNew;
    public AdvContentNew_t[] advContentNew;
    public AdvPlayMethodNew_t[] advPlayMethodNew;
    public TVMLastTrainNew_t[] tvmLastTrainNew;
    public Picture_t[] picture;
    public Word_t[] word;
    public CustomDisplayArea_t [] customDisplayArea;

    public EODDataNewTVMUIBD_t() {
    }

    public EODDataNewTVMUIBD_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm.xdrEncode(xdr);
        { int $size = resolutionInfo.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { resolutionInfo[$idx].xdrEncode(xdr); } }
        { int $size = interface_t.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { interface_t[$idx].xdrEncode(xdr); } }
        { int $size = area.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { area[$idx].xdrEncode(xdr); } }
        { int $size = tvmValueSelectionNew.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { tvmValueSelectionNew[$idx].xdrEncode(xdr); } }
        { int $size = tvmFareAreaNew.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { tvmFareAreaNew[$idx].xdrEncode(xdr); } }
        { int $size = tvmStationInAreaNew.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { tvmStationInAreaNew[$idx].xdrEncode(xdr); } }
        { int $size = tvmLineSelectionNew.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { tvmLineSelectionNew[$idx].xdrEncode(xdr); } }
        { int $size = tvmStationInLineNew.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { tvmStationInLineNew[$idx].xdrEncode(xdr); } }
        { int $size = advContentNew.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { advContentNew[$idx].xdrEncode(xdr); } }
        { int $size = advPlayMethodNew.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { advPlayMethodNew[$idx].xdrEncode(xdr); } }
        { int $size = tvmLastTrainNew.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { tvmLastTrainNew[$idx].xdrEncode(xdr); } }
        { int $size = picture.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { picture[$idx].xdrEncode(xdr); } }
        { int $size = word.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { word[$idx].xdrEncode(xdr); } }
        { int $size = customDisplayArea.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { customDisplayArea[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm = new EODModuleComm_t(xdr);
        { int $size = xdr.xdrDecodeInt(); resolutionInfo = new ResolutionInfo_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { resolutionInfo[$idx] = new ResolutionInfo_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); interface_t = new Interface_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { interface_t[$idx] = new Interface_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); area = new Area_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { area[$idx] = new Area_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); tvmValueSelectionNew = new TVMValueSelectionNew_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { tvmValueSelectionNew[$idx] = new TVMValueSelectionNew_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); tvmFareAreaNew = new TVMFareAreaNew_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { tvmFareAreaNew[$idx] = new TVMFareAreaNew_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); tvmStationInAreaNew = new TVMStationInAreaNew_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { tvmStationInAreaNew[$idx] = new TVMStationInAreaNew_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); tvmLineSelectionNew = new TVMLineSelectionNew_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { tvmLineSelectionNew[$idx] = new TVMLineSelectionNew_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); tvmStationInLineNew = new TVMStationInLineNew_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { tvmStationInLineNew[$idx] = new TVMStationInLineNew_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); advContentNew = new AdvContentNew_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { advContentNew[$idx] = new AdvContentNew_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); advPlayMethodNew = new AdvPlayMethodNew_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { advPlayMethodNew[$idx] = new AdvPlayMethodNew_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); tvmLastTrainNew = new TVMLastTrainNew_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { tvmLastTrainNew[$idx] = new TVMLastTrainNew_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); picture = new Picture_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { picture[$idx] = new Picture_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); word = new Word_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { word[$idx] = new Word_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); customDisplayArea = new CustomDisplayArea_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { customDisplayArea[$idx] = new CustomDisplayArea_t(xdr); } }
    }

}
// End of EODDataNewTVMUIBD_t.java
