package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class EODDataBOMConfigBD_t implements XdrAble {
    public EODModuleComm_t moduleComm;
    public TicketReaderData_t bomTicketReaderData;
    public MaintenanceData_t bomMaintenanceData;
    public TicketBoxData_t bomTicketBoxData;
    public TransactionQueryData_t bomTransactionQueryData;

    public EODDataBOMConfigBD_t() {
    }

    public EODDataBOMConfigBD_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm.xdrEncode(xdr);
        bomTicketReaderData.xdrEncode(xdr);
        bomMaintenanceData.xdrEncode(xdr);
        bomTicketBoxData.xdrEncode(xdr);
        bomTransactionQueryData.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm = new EODModuleComm_t(xdr);
        bomTicketReaderData = new TicketReaderData_t(xdr);
        bomMaintenanceData = new MaintenanceData_t(xdr);
        bomTicketBoxData = new TicketBoxData_t(xdr);
        bomTransactionQueryData = new TransactionQueryData_t(xdr);
    }

}
// End of EODDataBOMConfigBD_t.java
