package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class EODDataCalendarBD_t implements XdrAble {
    public EODModuleComm_t moduleComm;
    public Seconds_t localTimeZoneValue;
    public SecondsSinceMidNight_t timeOfStartOperation;
    public SecondsSinceMidNight_t timeOfEndOperation;
    public CalendarDate_t [] specialDateList;
    public CalendarTime_t [] specialTimeList;
    public CalendarHold_t [] maxHoldList;

    public EODDataCalendarBD_t() {
    }

    public EODDataCalendarBD_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm.xdrEncode(xdr);
        localTimeZoneValue.xdrEncode(xdr);
        timeOfStartOperation.xdrEncode(xdr);
        timeOfEndOperation.xdrEncode(xdr);
        { int $size = specialDateList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { specialDateList[$idx].xdrEncode(xdr); } }
        { int $size = specialTimeList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { specialTimeList[$idx].xdrEncode(xdr); } }
        { int $size = maxHoldList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { maxHoldList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm = new EODModuleComm_t(xdr);
        localTimeZoneValue = new Seconds_t(xdr);
        timeOfStartOperation = new SecondsSinceMidNight_t(xdr);
        timeOfEndOperation = new SecondsSinceMidNight_t(xdr);
        { int $size = xdr.xdrDecodeInt(); specialDateList = new CalendarDate_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { specialDateList[$idx] = new CalendarDate_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); specialTimeList = new CalendarTime_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { specialTimeList[$idx] = new CalendarTime_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); maxHoldList = new CalendarHold_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { maxHoldList[$idx] = new CalendarHold_t(xdr); } }
    }

}
// End of EODDataCalendarBD_t.java
