package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class EODDataFareBD_t implements XdrAble {
    public EODModuleComm_t moduleComm;
    public ValueCent_t maxAddValue;
    public ValueCent_t defaultAddValue;
    public ValueCent_t stepAddValue;
    public FareGroup_t[] fareGroupList;
    public FareTierInfo_t[] fareTierList;
    public FareValue_t[] fareValueList;

    public EODDataFareBD_t() {
    }

    public EODDataFareBD_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm.xdrEncode(xdr);
        maxAddValue.xdrEncode(xdr);
        defaultAddValue.xdrEncode(xdr);
        stepAddValue.xdrEncode(xdr);
        { int $size = fareGroupList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { fareGroupList[$idx].xdrEncode(xdr); } }
        { int $size = fareTierList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { fareTierList[$idx].xdrEncode(xdr); } }
        { int $size = fareValueList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { fareValueList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm = new EODModuleComm_t(xdr);
        maxAddValue = new ValueCent_t(xdr);
        defaultAddValue = new ValueCent_t(xdr);
        stepAddValue = new ValueCent_t(xdr);
        { int $size = xdr.xdrDecodeInt(); fareGroupList = new FareGroup_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { fareGroupList[$idx] = new FareGroup_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); fareTierList = new FareTierInfo_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { fareTierList[$idx] = new FareTierInfo_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); fareValueList = new FareValue_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { fareValueList[$idx] = new FareValue_t(xdr); } }
    }

}
// End of EODDataFareBD_t.java
