package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class EODDataStationLayoutBD_t implements XdrAble {
    public EODModuleComm_t moduleComm;
    public LineID_t lineId;
    public StationLayout_t[] stationLayoutList;

    public EODDataStationLayoutBD_t() {
    }

    public EODDataStationLayoutBD_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm.xdrEncode(xdr);
        lineId.xdrEncode(xdr);
        { int $size = stationLayoutList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { stationLayoutList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm = new EODModuleComm_t(xdr);
        lineId = new LineID_t(xdr);
        { int $size = xdr.xdrDecodeInt(); stationLayoutList = new StationLayout_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { stationLayoutList[$idx] = new StationLayout_t(xdr); } }
    }

}
// End of EODDataStationLayoutBD_t.java
