package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class EODDataOtherTVMUIBD_t implements XdrAble {
    public EODModuleComm_t moduleComm;
    public TVMPersonalization_t[] tvmPersonalization;

    public EODDataOtherTVMUIBD_t() {
    }

    public EODDataOtherTVMUIBD_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm.xdrEncode(xdr);
        { int $size = tvmPersonalization.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { tvmPersonalization[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm = new EODModuleComm_t(xdr);
        { int $size = xdr.xdrDecodeInt(); tvmPersonalization = new TVMPersonalization_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { tvmPersonalization[$idx] = new TVMPersonalization_t(xdr); } }
    }

}
// End of EODDataOtherTVMUIBD_t.java
