package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class EODDataTrainScheduleBD_t implements XdrAble {
    public EODModuleComm_t moduleComm;
    public LineTrainSchedule_t[] LineTrainSchedule;

    public EODDataTrainScheduleBD_t() {
    }

    public EODDataTrainScheduleBD_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm.xdrEncode(xdr);
        { int $size = LineTrainSchedule.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { LineTrainSchedule[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm = new EODModuleComm_t(xdr);
        { int $size = xdr.xdrDecodeInt(); LineTrainSchedule = new LineTrainSchedule_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { LineTrainSchedule[$idx] = new LineTrainSchedule_t(xdr); } }
    }

}
// End of EODDataTrainScheduleBD_t.java
