package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class EODDataDiscountBD_t implements XdrAble {
    public EODModuleComm_t moduleComm;
    public MultiTripDiscount_t[] MultiTripDiscountList;
    public PointDiscount_t[] PointDiscountList;

    public EODDataDiscountBD_t() {
    }

    public EODDataDiscountBD_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm.xdrEncode(xdr);
        { int $size = MultiTripDiscountList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { MultiTripDiscountList[$idx].xdrEncode(xdr); } }
        { int $size = PointDiscountList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { PointDiscountList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm = new EODModuleComm_t(xdr);
        { int $size = xdr.xdrDecodeInt(); MultiTripDiscountList = new MultiTripDiscount_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { MultiTripDiscountList[$idx] = new MultiTripDiscount_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); PointDiscountList = new PointDiscount_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { PointDiscountList[$idx] = new PointDiscount_t(xdr); } }
    }

}
// End of EODDataDiscountBD_t.java
