package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class EODDataTVMUIBD_t implements XdrAble {
    public EODModuleComm_t moduleComm;
    public MonitorDefine_t monitorDefine;
    public InitWindow_t initWindow;
    public SuspendStatus_t suspendStatus;
    public TopoMap_t topoMap;
    public CurrentDateTimeDisplay_t currentDateTimeDisplay;
    public AdvContent_t[] advList;
    public AdvPlayMethod_t advPlayMethod;
    public TVMTopBanner_t[] bannerList;
    public TVMLastTrain_t[] lastTrainList;
    public TVMFareValueSelection_t[] valueButtonList;
    public TVMFareArea_t[] fareAreaList;
    public TVMStationInArea_t[] stationListInArea;
    public TVMLineSelection_t[] lineButtonList;
    public TVMStationInLine_t[] stationListInLine;

    public EODDataTVMUIBD_t() {
    }

    public EODDataTVMUIBD_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm.xdrEncode(xdr);
        monitorDefine.xdrEncode(xdr);
        initWindow.xdrEncode(xdr);
        suspendStatus.xdrEncode(xdr);
        topoMap.xdrEncode(xdr);
        currentDateTimeDisplay.xdrEncode(xdr);
        { int $size = advList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { advList[$idx].xdrEncode(xdr); } }
        advPlayMethod.xdrEncode(xdr);
        { int $size = bannerList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { bannerList[$idx].xdrEncode(xdr); } }
        { int $size = lastTrainList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { lastTrainList[$idx].xdrEncode(xdr); } }
        { int $size = valueButtonList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { valueButtonList[$idx].xdrEncode(xdr); } }
        { int $size = fareAreaList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { fareAreaList[$idx].xdrEncode(xdr); } }
        { int $size = stationListInArea.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { stationListInArea[$idx].xdrEncode(xdr); } }
        { int $size = lineButtonList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { lineButtonList[$idx].xdrEncode(xdr); } }
        { int $size = stationListInLine.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { stationListInLine[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        moduleComm = new EODModuleComm_t(xdr);
        monitorDefine = new MonitorDefine_t(xdr);
        initWindow = new InitWindow_t(xdr);
        suspendStatus = new SuspendStatus_t(xdr);
        topoMap = new TopoMap_t(xdr);
        currentDateTimeDisplay = new CurrentDateTimeDisplay_t(xdr);
        { int $size = xdr.xdrDecodeInt(); advList = new AdvContent_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { advList[$idx] = new AdvContent_t(xdr); } }
        advPlayMethod = new AdvPlayMethod_t(xdr);
        { int $size = xdr.xdrDecodeInt(); bannerList = new TVMTopBanner_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { bannerList[$idx] = new TVMTopBanner_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); lastTrainList = new TVMLastTrain_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { lastTrainList[$idx] = new TVMLastTrain_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); valueButtonList = new TVMFareValueSelection_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { valueButtonList[$idx] = new TVMFareValueSelection_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); fareAreaList = new TVMFareArea_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { fareAreaList[$idx] = new TVMFareArea_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); stationListInArea = new TVMStationInArea_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { stationListInArea[$idx] = new TVMStationInArea_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); lineButtonList = new TVMLineSelection_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { lineButtonList[$idx] = new TVMLineSelection_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); stationListInLine = new TVMStationInLine_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { stationListInLine[$idx] = new TVMStationInLine_t(xdr); } }
    }

}
// End of EODDataTVMUIBD_t.java
