package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class EODModuleRecord_t implements XdrAble {
    public int moduleType;
    public AFCTime_t moduleValidTime;
    public U32_t userTypeBitMap;
    public String fileName;
    public U16_t versionNo;

    public EODModuleRecord_t() {
    }

    public EODModuleRecord_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(moduleType);
        moduleValidTime.xdrEncode(xdr);
        userTypeBitMap.xdrEncode(xdr);
        xdr.xdrEncodeString(fileName);
        versionNo.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        moduleType = xdr.xdrDecodeInt();
        moduleValidTime = new AFCTime_t(xdr);
        userTypeBitMap = new U32_t(xdr);
        fileName = xdr.xdrDecodeString();
        versionNo = new U16_t(xdr);
    }

}
// End of EODModuleRecord_t.java
