package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class EODModuleComm_t implements XdrAble {
    public int moduleType;
    public U32_t userTypeBitmap;
    public U16_t moduleVersionNo;

    public EODModuleComm_t() {
    }

    public EODModuleComm_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(moduleType);
        userTypeBitmap.xdrEncode(xdr);
        moduleVersionNo.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        moduleType = xdr.xdrDecodeInt();
        userTypeBitmap = new U32_t(xdr);
        moduleVersionNo = new U16_t(xdr);
    }

}
// End of EODModuleComm_t.java
