package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class EODMasterBodyData_t implements XdrAble {
    public U16_t versionNo;
    public AFCTime_t versionValidDate;
    public EODModuleRecord_t[] moduleInfoList;

    public EODMasterBodyData_t() {
    }

    public EODMasterBodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        versionNo.xdrEncode(xdr);
        versionValidDate.xdrEncode(xdr);
        { int $size = moduleInfoList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { moduleInfoList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        versionNo = new U16_t(xdr);
        versionValidDate = new AFCTime_t(xdr);
        { int $size = xdr.xdrDecodeInt(); moduleInfoList = new EODModuleRecord_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { moduleInfoList[$idx] = new EODModuleRecord_t(xdr); } }
    }

}
// End of EODMasterBodyData_t.java
