package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class ExchangeInfo_t implements XdrAble {
    public StationID_t stationInA;
    public StationID_t stationInB;

    public ExchangeInfo_t() {
    }

    public ExchangeInfo_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        stationInA.xdrEncode(xdr);
        stationInB.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        stationInA = new StationID_t(xdr);
        stationInB = new StationID_t(xdr);
    }

}
// End of ExchangeInfo_t.java
