package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class FareTierInfo_t implements XdrAble {
    public FareTier_t fareTierId;
    public StationID_t entryStation;
    public StationID_t exitStation;

    public FareTierInfo_t() {
    }

    public FareTierInfo_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        fareTierId.xdrEncode(xdr);
        entryStation.xdrEncode(xdr);
        exitStation.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        fareTierId = new FareTier_t(xdr);
        entryStation = new StationID_t(xdr);
        exitStation = new StationID_t(xdr);
    }

}
// End of FareTierInfo_t.java
