package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class FareTypeRecord_t implements XdrAble {
    public TicketType_t ticketCode;
    public int ticketFamily;
    public U32_t cardTypeInChip;
    public UnicodeString_t ticketCnName;
    public String ticketEnName;
    public U8_t namedSVTFlag;
    public U8_t giftTicketFlag;
    public U8_t lampNo;
    public U8_t checkBLFlag;
    public U8_t checkSaleStationFlag;
    public U8_t addValueFlag;
    public ValueCent_t maxValueOfSVT;
    public ValueCent_t minEntryMoney;
    public ValueCent_t minExitMoney;
    public ValueCent_t deposit;
    public U32_t multiRideTicketPrice;
    public U8_t refundFlag;
    public ValueCent_t maxRefundIntime;
    public ValueCent_t refundFee;
    public U16_t maxTripCount;
    public FareTier_t maxTrip;
    public U16_t maxTripCountSingleDay;
    public DurationMode_t ticketDurationMode;
    public Duration_t duration;
    public Date2_t fixedExpireDate;
    public U8_t renewalFlag;
    public Duration_t renewalDays;
    public U8_t lastTripDiscountFlag;
    public Seconds_t freeUpdateTimeOfMultiEntry;
    public Seconds_t freeUpdateTimeOfMultiExit;
    public ValueCent_t updatedValue;
    public ValueCent_t exTimeUpdateValue;
    public ValueCent_t exTripUpdateValue;
    public ValueCent_t exTimeTripUpdateValue;
    public ValueCent_t entryExitDismatch;
    public ValueCent_t exitNotOfUpdateStation;
    public U8_t arUseFlag;
    public U8_t discountType;
    public U8_t multiTripDiscountCode;
    public U8_t pointDiscountCode;
    public U8_t discountInTianjin;
    public U8_t discountInJinbin;
    public U8_t useFlag;
    public U32_t reserved;

    public FareTypeRecord_t() {
    }

    public FareTypeRecord_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        ticketCode.xdrEncode(xdr);
        xdr.xdrEncodeInt(ticketFamily);
        cardTypeInChip.xdrEncode(xdr);
        ticketCnName.xdrEncode(xdr);
        xdr.xdrEncodeString(ticketEnName);
        namedSVTFlag.xdrEncode(xdr);
        giftTicketFlag.xdrEncode(xdr);
        lampNo.xdrEncode(xdr);
        checkBLFlag.xdrEncode(xdr);
        checkSaleStationFlag.xdrEncode(xdr);
        addValueFlag.xdrEncode(xdr);
        maxValueOfSVT.xdrEncode(xdr);
        minEntryMoney.xdrEncode(xdr);
        minExitMoney.xdrEncode(xdr);
        deposit.xdrEncode(xdr);
        multiRideTicketPrice.xdrEncode(xdr);
        refundFlag.xdrEncode(xdr);
        maxRefundIntime.xdrEncode(xdr);
        refundFee.xdrEncode(xdr);
        maxTripCount.xdrEncode(xdr);
        maxTrip.xdrEncode(xdr);
        maxTripCountSingleDay.xdrEncode(xdr);
        ticketDurationMode.xdrEncode(xdr);
        duration.xdrEncode(xdr);
        fixedExpireDate.xdrEncode(xdr);
        renewalFlag.xdrEncode(xdr);
        renewalDays.xdrEncode(xdr);
        lastTripDiscountFlag.xdrEncode(xdr);
        freeUpdateTimeOfMultiEntry.xdrEncode(xdr);
        freeUpdateTimeOfMultiExit.xdrEncode(xdr);
        updatedValue.xdrEncode(xdr);
        exTimeUpdateValue.xdrEncode(xdr);
        exTripUpdateValue.xdrEncode(xdr);
        exTimeTripUpdateValue.xdrEncode(xdr);
        entryExitDismatch.xdrEncode(xdr);
        exitNotOfUpdateStation.xdrEncode(xdr);
        arUseFlag.xdrEncode(xdr);
        discountType.xdrEncode(xdr);
        multiTripDiscountCode.xdrEncode(xdr);
        pointDiscountCode.xdrEncode(xdr);
        discountInTianjin.xdrEncode(xdr);
        discountInJinbin.xdrEncode(xdr);
        useFlag.xdrEncode(xdr);
        reserved.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        ticketCode = new TicketType_t(xdr);
        ticketFamily = xdr.xdrDecodeInt();
        cardTypeInChip = new U32_t(xdr);
        ticketCnName = new UnicodeString_t(xdr);
        ticketEnName = xdr.xdrDecodeString();
        namedSVTFlag = new U8_t(xdr);
        giftTicketFlag = new U8_t(xdr);
        lampNo = new U8_t(xdr);
        checkBLFlag = new U8_t(xdr);
        checkSaleStationFlag = new U8_t(xdr);
        addValueFlag = new U8_t(xdr);
        maxValueOfSVT = new ValueCent_t(xdr);
        minEntryMoney = new ValueCent_t(xdr);
        minExitMoney = new ValueCent_t(xdr);
        deposit = new ValueCent_t(xdr);
        multiRideTicketPrice = new U32_t(xdr);
        refundFlag = new U8_t(xdr);
        maxRefundIntime = new ValueCent_t(xdr);
        refundFee = new ValueCent_t(xdr);
        maxTripCount = new U16_t(xdr);
        maxTrip = new FareTier_t(xdr);
        maxTripCountSingleDay = new U16_t(xdr);
        ticketDurationMode = new DurationMode_t(xdr);
        duration = new Duration_t(xdr);
        fixedExpireDate = new Date2_t(xdr);
        renewalFlag = new U8_t(xdr);
        renewalDays = new Duration_t(xdr);
        lastTripDiscountFlag = new U8_t(xdr);
        freeUpdateTimeOfMultiEntry = new Seconds_t(xdr);
        freeUpdateTimeOfMultiExit = new Seconds_t(xdr);
        updatedValue = new ValueCent_t(xdr);
        exTimeUpdateValue = new ValueCent_t(xdr);
        exTripUpdateValue = new ValueCent_t(xdr);
        exTimeTripUpdateValue = new ValueCent_t(xdr);
        entryExitDismatch = new ValueCent_t(xdr);
        exitNotOfUpdateStation = new ValueCent_t(xdr);
        arUseFlag = new U8_t(xdr);
        discountType = new U8_t(xdr);
        multiTripDiscountCode = new U8_t(xdr);
        pointDiscountCode = new U8_t(xdr);
        discountInTianjin = new U8_t(xdr);
        discountInJinbin = new U8_t(xdr);
        useFlag = new U8_t(xdr);
        reserved = new U32_t(xdr);
    }

}
// End of FareTypeRecord_t.java
