package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class FareValue_t implements XdrAble {
    public FareGroupID_t fareGroupId;
    public FareTier_t fareTierId;
    public ValueCent_t fareValue;

    public FareValue_t() {
    }

    public FareValue_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        fareGroupId.xdrEncode(xdr);
        fareTierId.xdrEncode(xdr);
        fareValue.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        fareGroupId = new FareGroupID_t(xdr);
        fareTierId = new FareTier_t(xdr);
        fareValue = new ValueCent_t(xdr);
    }

}
// End of FareValue_t.java
