package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class FareGroup_t implements XdrAble {
    public TicketType_t ticketType;
    public DateTypeID_t dateTypeID;
    public TimeIntervalID_t timeInterval;
    public FareGroupID_t fareGroupId;

    public FareGroup_t() {
    }

    public FareGroup_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        ticketType.xdrEncode(xdr);
        dateTypeID.xdrEncode(xdr);
        timeInterval.xdrEncode(xdr);
        fareGroupId.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        ticketType = new TicketType_t(xdr);
        dateTypeID = new DateTypeID_t(xdr);
        timeInterval = new TimeIntervalID_t(xdr);
        fareGroupId = new FareGroupID_t(xdr);
    }

}
// End of FareGroup_t.java
