package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
/**
 * Enumeration (collection of constants).
 */
public interface FilePathType_t {

    public static final int FTP_UD = 1;
    public static final int FTP_AR = 2;
    public static final int FTP_EVENT = 3;
    public static final int FTP_EOD = 4;
    public static final int FTP_RUNCONFIG = 5;
    public static final int FTP_STOCK = 6;
    public static final int FTP_SETTLEMENT = 7;
    public static final int FTP_EOD2 = 8;
    public static final int FTP_EOD3 = 9;

}
// End of FilePathType_t.java
