package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class File_t implements XdrAble {
    public FileHeader_t FileHeader;
    public FileBodyData_t FileBodyData;
    public MD5_t Md5;

    public File_t() {
    }

    public File_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        FileHeader.xdrEncode(xdr);
        FileBodyData.xdrEncode(xdr);
        Md5.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        FileHeader = new FileHeader_t(xdr);
        FileBodyData = new FileBodyData_t(xdr);
        Md5 = new MD5_t(xdr);
    }

}
// End of File_t.java
