package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class FileHeader_t implements XdrAble {
    public int FileType;
    public U32_t ProtocalVersion;
    public AFCTime_t FileCreationTime;
    public DeviceID_t DeviceID;
    public SN_t FileSN;

    public FileHeader_t() {
    }

    public FileHeader_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(FileType);
        ProtocalVersion.xdrEncode(xdr);
        FileCreationTime.xdrEncode(xdr);
        DeviceID.xdrEncode(xdr);
        FileSN.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        FileType = xdr.xdrDecodeInt();
        ProtocalVersion = new U32_t(xdr);
        FileCreationTime = new AFCTime_t(xdr);
        DeviceID = new DeviceID_t(xdr);
        FileSN = new SN_t(xdr);
    }

}
// End of FileHeader_t.java
