package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class FileBodyData_t implements XdrAble {
    public int FileType;
    public UDBodyData_t YptUDBodyData;
    public UDBodyData_t YktUDBodyData;
    public UDBodyData_t SVTCPUUDBodyData;
    public UDBodyData_t JRICUDBodyData;
    public UDBodyData_t JTBUDBodyData;
    public UDBodyData_t GJICUDBodyData;
    public UDBodyData_t QpayUDBodyData;
    public UDBodyData_t QrcodeUDBodyData;
    public UDBodyData_t FaceUDBodyData;
    public ARBodyDataNew_t ARBodyDataNew;
    public ARBodyData_t ARBodyData;
    public EODMasterBodyData_t EODMasterBodyData;
    public RunMasterBodyData_t RunMasterBodyData;
    public OtherMasterBodyData_t OtherMasterBodyData;
    public EODDataSystemBD_t eodDataSystem;
    public EODDataTopoBD_t eodDataTopo;
    public EODDataFareTypeBD_t eodDataFareType;
    public EODDataDiscountBD_t eodDataDiscount;
    public EODDataCalendarBD_t eodDataCalendar;
    public EODDataFareBD_t eodDataFare;
    public EODDataTVMUIBD_t eodDataTVMUI;
    public EODDataTrainScheduleBD_t eodTrainSchedule;
    public EODDataNewTVMUIBD_t eodDataNewTVMUI;
    public EODDataPriviledgeBD_t eodDataPriviledge;
    public EODDataStationLayoutBD_t eodDataStationLayout;
    public EODDataTVMConfigBD_t eodDataTVMConfig;
    public EODDataAGMConfigBD_t eodDataAGMConfig;
    public EODDataBOMConfigBD_t eodDataBOMConfig;
    public ModeListBodyData_t ModeListBodyData;
    public YKTBlackListBD_t YktBlackListBodyData;
    public ACCAllBlackListBD_t YptAllBlackListBodyData;
    public ACCAddBlackListBD_t YptAddBlackListBodyData;
    public ACCRangeBlackListBD_t YptRangeBlackListBodyData;
    public StaffBlackListBD_t StaffBlackListBodyData;
    public PbocPkBD_t PbocPkInfoBodyData;
    public PbocParamBD_t PbocParamInfoBodyData;
    public PbocBinBD_t PbocBinInfoBodyData;
    public JTBAllWhiteListBD_t JTBAllWhiteListBodyData;
    public JTBAllBlackListBD_t JTBAllBlackListBodyData;
    public SVTCPUAllBlackListBD_t SVTCPUAllBlackListBodyData;
    public GJICAllBlackListBD_t GJICAllBlackListBodyData;
    public TxSettleBodyData_t TxSettleBodyData;
    public SettleAdjustBodyData_t SettleAdjustBodyData;
    public ClearBodyData_t ClearBodyData;
    public FtpAuditBodyData_t FtpAuditBodyData;
    public SPTFtpAuditBodyData_t SPTFtpAuditBodyData;
    public SPTTxSettleBodyData_t SPTTxSettleBodyData;
    public SPTSettleAdjustBodyData_t SPTSettleAdjustBodyData;
    public ClearDetailBodyData_t ClearDetailBodyData;
    public StockStatBodyData_t StockStatBodyData;
    public OtherEodBodyData_t OtherEodBodyData;
    public EODDataOtherTVMUIBD_t eodDataOtherTVMUI;

    public FileBodyData_t() {
    }

    public FileBodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(FileType);
        switch ( FileType ) {
        case MessageType_t.MT_YptTransaction:
            YptUDBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_YktTransaction:
            YktUDBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_SVTCPUCardTransaction:
            SVTCPUUDBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_ICCardTransaction:
            JRICUDBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_JTBCardTransaction:
            JTBUDBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_GJICCardTransaction:
            GJICUDBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_QpayTransaction:
            QpayUDBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_QrcodeTransaction:
            QrcodeUDBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_FaceTransaction:
            FaceUDBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_SleAuditRegisterNew:
            ARBodyDataNew.xdrEncode(xdr);
            break;
        case MessageType_t.MT_SleAuditRegister:
            ARBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_EodMasterControl:
            EODMasterBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_RunMasterControl:
            RunMasterBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_OtherMasterControl:
            OtherMasterBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_EodSystemControl:
            eodDataSystem.xdrEncode(xdr);
            break;
        case MessageType_t.MT_EodTopo:
            eodDataTopo.xdrEncode(xdr);
            break;
        case MessageType_t.MT_EodFareMediaType:
            eodDataFareType.xdrEncode(xdr);
            break;
        case MessageType_t.MT_EodDiscount:
            eodDataDiscount.xdrEncode(xdr);
            break;
        case MessageType_t.MT_EodCalendar:
            eodDataCalendar.xdrEncode(xdr);
            break;
        case MessageType_t.MT_EodFare:
            eodDataFare.xdrEncode(xdr);
            break;
        case MessageType_t.MT_EodTvmUi:
            eodDataTVMUI.xdrEncode(xdr);
            break;
        case MessageType_t.MT_EodTrainSchedule:
            eodTrainSchedule.xdrEncode(xdr);
            break;
        case MessageType_t.MT_EodNewTvmUi:
            eodDataNewTVMUI.xdrEncode(xdr);
            break;
        case MessageType_t.MT_EodPriviledge:
            eodDataPriviledge.xdrEncode(xdr);
            break;
        case MessageType_t.MT_EodStationLayout:
            eodDataStationLayout.xdrEncode(xdr);
            break;
        case MessageType_t.MT_EodTvmRunConfig:
            eodDataTVMConfig.xdrEncode(xdr);
            break;
        case MessageType_t.MT_EodAgmRunConfig:
            eodDataAGMConfig.xdrEncode(xdr);
            break;
        case MessageType_t.MT_EodBomRunConfig:
            eodDataBOMConfig.xdrEncode(xdr);
            break;
        case MessageType_t.MT_ModeHistoryList:
            ModeListBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_YktBlacklist:
            YktBlackListBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_YptAllBlackList:
            YptAllBlackListBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_YptAddBlackList:
            YptAddBlackListBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_YptRangeBlackList:
            YptRangeBlackListBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_StaffBlackList:
            StaffBlackListBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_PbocPk:
            PbocPkInfoBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_PbocParam:
            PbocParamInfoBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_PbocBin:
            PbocBinInfoBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_JTBAllWhiteList:
            JTBAllWhiteListBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_JTBAllBlackList:
            JTBAllBlackListBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_SVTCPUAllBlackList:
            SVTCPUAllBlackListBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_GJICAllBlackList:
            GJICAllBlackListBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_AccSettleTxResult:
            TxSettleBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_AccSettleTxAdjust:
            SettleAdjustBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_AccSettleClear:
            ClearBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_FtpAudit:
            FtpAuditBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_SPTFtpAudit:
            SPTFtpAuditBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_SPTAccSettleTxResult:
            SPTTxSettleBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_SPTAccSettleTxAdjust:
            SPTSettleAdjustBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_AccSettleDetailClear:
            ClearDetailBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_TicketStockSnapshot:
            StockStatBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_OtherEodControl:
            OtherEodBodyData.xdrEncode(xdr);
            break;
        case MessageType_t.MT_OtherTvmUi:
            eodDataOtherTVMUI.xdrEncode(xdr);
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        FileType = xdr.xdrDecodeInt();
        switch ( FileType ) {
        case MessageType_t.MT_YptTransaction:
            YptUDBodyData = new UDBodyData_t(xdr);
            break;
        case MessageType_t.MT_YktTransaction:
            YktUDBodyData = new UDBodyData_t(xdr);
            break;
        case MessageType_t.MT_SVTCPUCardTransaction:
            SVTCPUUDBodyData = new UDBodyData_t(xdr);
            break;
        case MessageType_t.MT_ICCardTransaction:
            JRICUDBodyData = new UDBodyData_t(xdr);
            break;
        case MessageType_t.MT_JTBCardTransaction:
            JTBUDBodyData = new UDBodyData_t(xdr);
            break;
        case MessageType_t.MT_GJICCardTransaction:
            GJICUDBodyData = new UDBodyData_t(xdr);
            break;
        case MessageType_t.MT_QpayTransaction:
            QpayUDBodyData = new UDBodyData_t(xdr);
            break;
        case MessageType_t.MT_QrcodeTransaction:
            QrcodeUDBodyData = new UDBodyData_t(xdr);
            break;
        case MessageType_t.MT_FaceTransaction:
            FaceUDBodyData = new UDBodyData_t(xdr);
            break;
        case MessageType_t.MT_SleAuditRegisterNew:
            ARBodyDataNew = new ARBodyDataNew_t(xdr);
            break;
        case MessageType_t.MT_SleAuditRegister:
            ARBodyData = new ARBodyData_t(xdr);
            break;
        case MessageType_t.MT_EodMasterControl:
            EODMasterBodyData = new EODMasterBodyData_t(xdr);
            break;
        case MessageType_t.MT_RunMasterControl:
            RunMasterBodyData = new RunMasterBodyData_t(xdr);
            break;
        case MessageType_t.MT_OtherMasterControl:
            OtherMasterBodyData = new OtherMasterBodyData_t(xdr);
            break;
        case MessageType_t.MT_EodSystemControl:
            eodDataSystem = new EODDataSystemBD_t(xdr);
            break;
        case MessageType_t.MT_EodTopo:
            eodDataTopo = new EODDataTopoBD_t(xdr);
            break;
        case MessageType_t.MT_EodFareMediaType:
            eodDataFareType = new EODDataFareTypeBD_t(xdr);
            break;
        case MessageType_t.MT_EodDiscount:
            eodDataDiscount = new EODDataDiscountBD_t(xdr);
            break;
        case MessageType_t.MT_EodCalendar:
            eodDataCalendar = new EODDataCalendarBD_t(xdr);
            break;
        case MessageType_t.MT_EodFare:
            eodDataFare = new EODDataFareBD_t(xdr);
            break;
        case MessageType_t.MT_EodTvmUi:
            eodDataTVMUI = new EODDataTVMUIBD_t(xdr);
            break;
        case MessageType_t.MT_EodTrainSchedule:
            eodTrainSchedule = new EODDataTrainScheduleBD_t(xdr);
            break;
        case MessageType_t.MT_EodNewTvmUi:
            eodDataNewTVMUI = new EODDataNewTVMUIBD_t(xdr);
            break;
        case MessageType_t.MT_EodPriviledge:
            eodDataPriviledge = new EODDataPriviledgeBD_t(xdr);
            break;
        case MessageType_t.MT_EodStationLayout:
            eodDataStationLayout = new EODDataStationLayoutBD_t(xdr);
            break;
        case MessageType_t.MT_EodTvmRunConfig:
            eodDataTVMConfig = new EODDataTVMConfigBD_t(xdr);
            break;
        case MessageType_t.MT_EodAgmRunConfig:
            eodDataAGMConfig = new EODDataAGMConfigBD_t(xdr);
            break;
        case MessageType_t.MT_EodBomRunConfig:
            eodDataBOMConfig = new EODDataBOMConfigBD_t(xdr);
            break;
        case MessageType_t.MT_ModeHistoryList:
            ModeListBodyData = new ModeListBodyData_t(xdr);
            break;
        case MessageType_t.MT_YktBlacklist:
            YktBlackListBodyData = new YKTBlackListBD_t(xdr);
            break;
        case MessageType_t.MT_YptAllBlackList:
            YptAllBlackListBodyData = new ACCAllBlackListBD_t(xdr);
            break;
        case MessageType_t.MT_YptAddBlackList:
            YptAddBlackListBodyData = new ACCAddBlackListBD_t(xdr);
            break;
        case MessageType_t.MT_YptRangeBlackList:
            YptRangeBlackListBodyData = new ACCRangeBlackListBD_t(xdr);
            break;
        case MessageType_t.MT_StaffBlackList:
            StaffBlackListBodyData = new StaffBlackListBD_t(xdr);
            break;
        case MessageType_t.MT_PbocPk:
            PbocPkInfoBodyData = new PbocPkBD_t(xdr);
            break;
        case MessageType_t.MT_PbocParam:
            PbocParamInfoBodyData = new PbocParamBD_t(xdr);
            break;
        case MessageType_t.MT_PbocBin:
            PbocBinInfoBodyData = new PbocBinBD_t(xdr);
            break;
        case MessageType_t.MT_JTBAllWhiteList:
            JTBAllWhiteListBodyData = new JTBAllWhiteListBD_t(xdr);
            break;
        case MessageType_t.MT_JTBAllBlackList:
            JTBAllBlackListBodyData = new JTBAllBlackListBD_t(xdr);
            break;
        case MessageType_t.MT_SVTCPUAllBlackList:
            SVTCPUAllBlackListBodyData = new SVTCPUAllBlackListBD_t(xdr);
            break;
        case MessageType_t.MT_GJICAllBlackList:
            GJICAllBlackListBodyData = new GJICAllBlackListBD_t(xdr);
            break;
        case MessageType_t.MT_AccSettleTxResult:
            TxSettleBodyData = new TxSettleBodyData_t(xdr);
            break;
        case MessageType_t.MT_AccSettleTxAdjust:
            SettleAdjustBodyData = new SettleAdjustBodyData_t(xdr);
            break;
        case MessageType_t.MT_AccSettleClear:
            ClearBodyData = new ClearBodyData_t(xdr);
            break;
        case MessageType_t.MT_FtpAudit:
            FtpAuditBodyData = new FtpAuditBodyData_t(xdr);
            break;
        case MessageType_t.MT_SPTFtpAudit:
            SPTFtpAuditBodyData = new SPTFtpAuditBodyData_t(xdr);
            break;
        case MessageType_t.MT_SPTAccSettleTxResult:
            SPTTxSettleBodyData = new SPTTxSettleBodyData_t(xdr);
            break;
        case MessageType_t.MT_SPTAccSettleTxAdjust:
            SPTSettleAdjustBodyData = new SPTSettleAdjustBodyData_t(xdr);
            break;
        case MessageType_t.MT_AccSettleDetailClear:
            ClearDetailBodyData = new ClearDetailBodyData_t(xdr);
            break;
        case MessageType_t.MT_TicketStockSnapshot:
            StockStatBodyData = new StockStatBodyData_t(xdr);
            break;
        case MessageType_t.MT_OtherEodControl:
            OtherEodBodyData = new OtherEodBodyData_t(xdr);
            break;
        case MessageType_t.MT_OtherTvmUi:
            eodDataOtherTVMUI = new EODDataOtherTVMUIBD_t(xdr);
            break;
        }
    }

}
// End of FileBodyData_t.java
