package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class FtpAuditFile_t implements XdrAble {
    public String fileName;
    public U32_t fileSize;
    public U32_t recordCount;

    public FtpAuditFile_t() {
    }

    public FtpAuditFile_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeString(fileName);
        fileSize.xdrEncode(xdr);
        recordCount.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        fileName = xdr.xdrDecodeString();
        fileSize = new U32_t(xdr);
        recordCount = new U32_t(xdr);
    }

}
// End of FtpAuditFile_t.java
