package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class FtpAccountInfo_t implements XdrAble {
    public int dirClass;
    public U32_t ipAddress;
    public String userName;
    public String pin;
    public String path;

    public FtpAccountInfo_t() {
    }

    public FtpAccountInfo_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(dirClass);
        ipAddress.xdrEncode(xdr);
        xdr.xdrEncodeString(userName);
        xdr.xdrEncodeString(pin);
        xdr.xdrEncodeString(path);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        dirClass = xdr.xdrDecodeInt();
        ipAddress = new U32_t(xdr);
        userName = xdr.xdrDecodeString();
        pin = xdr.xdrDecodeString();
        path = xdr.xdrDecodeString();
    }

}
// End of FtpAccountInfo_t.java
