package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class FtpAuditBodyData_t implements XdrAble {
    public Date2_t settleDate;
    public DeviceID_t settleObject;
    public FtpAuditFile_t[] yktAuditList;
    public FtpAuditFile_t[] yptAuditList;
    public FtpAuditFile_t[] SVTCPUAuditList;
    public FtpAuditFile_t[] JRICAuditList;
    public FtpAuditFile_t[] JTBAuditList;
    public FtpAuditFile_t[] GJICAuditList;

    public FtpAuditBodyData_t() {
    }

    public FtpAuditBodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        settleDate.xdrEncode(xdr);
        settleObject.xdrEncode(xdr);
        { int $size = yktAuditList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { yktAuditList[$idx].xdrEncode(xdr); } }
        { int $size = yptAuditList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { yptAuditList[$idx].xdrEncode(xdr); } }
        { int $size = SVTCPUAuditList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { SVTCPUAuditList[$idx].xdrEncode(xdr); } }
        { int $size = JRICAuditList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { JRICAuditList[$idx].xdrEncode(xdr); } }
        { int $size = JTBAuditList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { JTBAuditList[$idx].xdrEncode(xdr); } }
        { int $size = GJICAuditList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { GJICAuditList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        settleDate = new Date2_t(xdr);
        settleObject = new DeviceID_t(xdr);
        { int $size = xdr.xdrDecodeInt(); yktAuditList = new FtpAuditFile_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { yktAuditList[$idx] = new FtpAuditFile_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); yptAuditList = new FtpAuditFile_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { yptAuditList[$idx] = new FtpAuditFile_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); SVTCPUAuditList = new FtpAuditFile_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { SVTCPUAuditList[$idx] = new FtpAuditFile_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); JRICAuditList = new FtpAuditFile_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { JRICAuditList[$idx] = new FtpAuditFile_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); JTBAuditList = new FtpAuditFile_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { JTBAuditList[$idx] = new FtpAuditFile_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); GJICAuditList = new FtpAuditFile_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { GJICAuditList[$idx] = new FtpAuditFile_t(xdr); } }
    }

}
// End of FtpAuditBodyData_t.java
