package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class GateProcessStatByType_t implements XdrAble {
    public TicketType_t TicketType;
    public U32_t CountOfGateEntry;
    public U32_t CountOfGateExit;
    public U32_t CountOfTicketRecycle;
    public U32_t ValueOfDebit;
    public U32_t CountOfBlock;

    public GateProcessStatByType_t() {
    }

    public GateProcessStatByType_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        TicketType.xdrEncode(xdr);
        CountOfGateEntry.xdrEncode(xdr);
        CountOfGateExit.xdrEncode(xdr);
        CountOfTicketRecycle.xdrEncode(xdr);
        ValueOfDebit.xdrEncode(xdr);
        CountOfBlock.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        TicketType = new TicketType_t(xdr);
        CountOfGateEntry = new U32_t(xdr);
        CountOfGateExit = new U32_t(xdr);
        CountOfTicketRecycle = new U32_t(xdr);
        ValueOfDebit = new U32_t(xdr);
        CountOfBlock = new U32_t(xdr);
    }

}
// End of GateProcessStatByType_t.java
