package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Interface_t implements XdrAble {
    public U8_t resolutionNumber;
    public U16_t interfaceNumber;
    public String cnBaseMapFileName;
    public String enBaseMapFileName;

    public Interface_t() {
    }

    public Interface_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        resolutionNumber.xdrEncode(xdr);
        interfaceNumber.xdrEncode(xdr);
        xdr.xdrEncodeString(cnBaseMapFileName);
        xdr.xdrEncodeString(enBaseMapFileName);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        resolutionNumber = new U8_t(xdr);
        interfaceNumber = new U16_t(xdr);
        cnBaseMapFileName = xdr.xdrDecodeString();
        enBaseMapFileName = xdr.xdrDecodeString();
    }

}
// End of Interface_t.java
