package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class JTBAllBlackList_t implements XdrAble {
    public U32_t[] AcquirerCode;
    public TicketLogID_t TicketLogicalID;
    public U8_t processFlag;

    public JTBAllBlackList_t() {
    }

    public JTBAllBlackList_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        { int $size = 3; for ( int $idx = 0; $idx < $size; ++$idx ) { AcquirerCode[$idx].xdrEncode(xdr); } }
        TicketLogicalID.xdrEncode(xdr);
        processFlag.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        { int $size = 3; AcquirerCode = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { AcquirerCode[$idx] = new U32_t(xdr); } }
        TicketLogicalID = new TicketLogID_t(xdr);
        processFlag = new U8_t(xdr);
    }

}
// End of JTBAllBlackList_t.java
