package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class JTBAllWhiteList_t implements XdrAble {
    public U32_t[] AcquirerCode;
    public U32_t IIN;
    public U32_t Cardorg;
    public U32_t[] Rsvd;

    public JTBAllWhiteList_t() {
    }

    public JTBAllWhiteList_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        { int $size = 3; for ( int $idx = 0; $idx < $size; ++$idx ) { AcquirerCode[$idx].xdrEncode(xdr); } }
        IIN.xdrEncode(xdr);
        Cardorg.xdrEncode(xdr);
        { int $size = 3; for ( int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        { int $size = 3; AcquirerCode = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { AcquirerCode[$idx] = new U32_t(xdr); } }
        IIN = new U32_t(xdr);
        Cardorg = new U32_t(xdr);
        { int $size = 3; Rsvd = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx] = new U32_t(xdr); } }
    }

}
// End of JTBAllWhiteList_t.java
