package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class LayoutDevice_t implements XdrAble {
    public DeviceID_t deviceId;
    public String deviceName;
    public int deviceType;
    public int deviceSubType;
    public U8_t deviceSeqInStation;
    public U8_t lobbyId;
    public U8_t groupId;
    public U8_t deviceSeqInGroup;
    public S16_t xPos;
    public S16_t yPos;
    public S16_t angle;
    public U32_t ipAdd;
    public U8_t useFlag;

    public LayoutDevice_t() {
    }

    public LayoutDevice_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        deviceId.xdrEncode(xdr);
        xdr.xdrEncodeString(deviceName);
        xdr.xdrEncodeInt(deviceType);
        xdr.xdrEncodeInt(deviceSubType);
        deviceSeqInStation.xdrEncode(xdr);
        lobbyId.xdrEncode(xdr);
        groupId.xdrEncode(xdr);
        deviceSeqInGroup.xdrEncode(xdr);
        xPos.xdrEncode(xdr);
        yPos.xdrEncode(xdr);
        angle.xdrEncode(xdr);
        ipAdd.xdrEncode(xdr);
        useFlag.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        deviceId = new DeviceID_t(xdr);
        deviceName = xdr.xdrDecodeString();
        deviceType = xdr.xdrDecodeInt();
        deviceSubType = xdr.xdrDecodeInt();
        deviceSeqInStation = new U8_t(xdr);
        lobbyId = new U8_t(xdr);
        groupId = new U8_t(xdr);
        deviceSeqInGroup = new U8_t(xdr);
        xPos = new S16_t(xdr);
        yPos = new S16_t(xdr);
        angle = new S16_t(xdr);
        ipAdd = new U32_t(xdr);
        useFlag = new U8_t(xdr);
    }

}
// End of LayoutDevice_t.java
