package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class LineTrainSchedule_t implements XdrAble {
    public LineID_t lineId;
    public StationTrainSchedule_t[] stationScheduleList;

    public LineTrainSchedule_t() {
    }

    public LineTrainSchedule_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        lineId.xdrEncode(xdr);
        { int $size = stationScheduleList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { stationScheduleList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        lineId = new LineID_t(xdr);
        { int $size = xdr.xdrDecodeInt(); stationScheduleList = new StationTrainSchedule_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { stationScheduleList[$idx] = new StationTrainSchedule_t(xdr); } }
    }

}
// End of LineTrainSchedule_t.java
