package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class LineInfo_t implements XdrAble {
    public LineID_t lineCode;
    public UnicodeString_t lineCnName;
    public String lineEnName;
    public U8_t useFlag;

    public LineInfo_t() {
    }

    public LineInfo_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        lineCode.xdrEncode(xdr);
        lineCnName.xdrEncode(xdr);
        xdr.xdrEncodeString(lineEnName);
        useFlag.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        lineCode = new LineID_t(xdr);
        lineCnName = new UnicodeString_t(xdr);
        lineEnName = xdr.xdrDecodeString();
        useFlag = new U8_t(xdr);
    }

}
// End of LineInfo_t.java
