package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class MaintenanceData_t implements XdrAble {
    public U16_t timePinEnter;
    public U16_t retryLogCount;
    public U16_t quitIntervalInIdle;
    public U16_t alarmIntervalInDoorOpen;

    public MaintenanceData_t() {
    }

    public MaintenanceData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        timePinEnter.xdrEncode(xdr);
        retryLogCount.xdrEncode(xdr);
        quitIntervalInIdle.xdrEncode(xdr);
        alarmIntervalInDoorOpen.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        timePinEnter = new U16_t(xdr);
        retryLogCount = new U16_t(xdr);
        quitIntervalInIdle = new U16_t(xdr);
        alarmIntervalInDoorOpen = new U16_t(xdr);
    }

}
// End of MaintenanceData_t.java
