package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
/**
 * Enumeration (collection of constants).
 */
public interface MessageType_t {

    public static final int MT_Mack = 0x1000;
    public static final int MT_InitForTx = 0x1001;
    public static final int MT_DataSynch = 0x1002;
    public static final int MT_QueryRunfileVersion = 0x1003;
    public static final int MT_QueryEODVersion = 0x1004;
    public static final int MT_CommandMode = 0x1005;
    public static final int MT_InfoMode = 0x1006;
    public static final int MT_BroadCastMode = 0x1007;
    public static final int MT_QueryMode = 0x1008;
    public static final int MT_InfoFlowData = 0x1009;
    public static final int MT_InfoDeviceStatus = 0x100a;
    public static final int MT_QueryDeviceStatus = 0x100b;
    public static final int MT_Reserved1 = 0x100c;
    public static final int MT_Reserved2 = 0x100d;
    public static final int MT_CommandTimeSynch = 0x100e;
    public static final int MT_CommandEQM = 0x100f;
    public static final int MT_InfoDeviceEvent = 0x1010;
    public static final int MT_UserAuthenticate = 0x1021;
    public static final int MT_YPTCardAuthenticate = 0x1022;
    public static final int MT_UserPinChange = 0x1023;
    public static final int MT_CPUCardAuthenticate = 0x1024;
    public static final int MT_CPUCardConfirm = 0x1025;
    public static final int MT_NonImmediateRefundApply = 0x1026;
    public static final int MT_CardAccountQuery = 0x1027;
    public static final int MT_CardAccountSend = 0x1028;
    public static final int MT_NonImmediateRefundConfirm = 0x1029;
    public static final int MT_CPUCardSaleCheck = 0x1030;
    public static final int MT_YptTransaction = 0x2001;
    public static final int MT_YktTransaction = 0x2002;
    public static final int MT_SleFinance = 0x2003;
    public static final int MT_SleAuditRegister = 0x2004;
    public static final int MT_SVTCPUCardTransaction = 0x2005;
    public static final int MT_JTBCardTransaction = 0x2006;
    public static final int MT_ICCardTransaction = 0x2007;
    public static final int MT_GJICCardTransaction = 0x2008;
    public static final int MT_SleAuditRegisterNew = 0x2009;
    public static final int MT_QpayTransaction = 0x200a;
    public static final int MT_QrcodeTransaction = 0x200b;
    public static final int MT_FaceTransaction = 0x200c;
    public static final int MT_SleDeviceEvent = 0x3001;
    public static final int MT_EodMasterControl = 0x4001;
    public static final int MT_RunMasterControl = 0x4002;
    public static final int MT_OtherMasterControl = 0x4003;
    public static final int MT_YktBlacklist = 0x4011;
    public static final int MT_YptAllBlackList = 0x4012;
    public static final int MT_YptAddBlackList = 0x4013;
    public static final int MT_YptRangeBlackList = 0x4014;
    public static final int MT_StaffBlackList = 0x4015;
    public static final int MT_ModeHistoryList = 0x4021;
    public static final int MT_EodSystemControl = 0x4031;
    public static final int MT_EodTopo = 0x4032;
    public static final int MT_EodFareMediaType = 0x4033;
    public static final int MT_EodDiscount = 0x4034;
    public static final int MT_EodCalendar = 0x4035;
    public static final int MT_EodFare = 0x4036;
    public static final int MT_EodTvmUi = 0x4037;
    public static final int MT_EodTrainSchedule = 0x4038;
    public static final int MT_EodNewTvmUi = 0x4039;
    public static final int MT_EodPriviledge = 0x4041;
    public static final int MT_EodStationLayout = 0x4042;
    public static final int MT_EodTvmRunConfig = 0x4043;
    public static final int MT_EodAgmRunConfig = 0x4044;
    public static final int MT_EodBomRunConfig = 0x4045;
    public static final int MT_PbocPk = 0x4051;
    public static final int MT_PbocParam = 0x4052;
    public static final int MT_PbocBin = 0x4053;
    public static final int MT_JTBAllWhiteList = 0x4054;
    public static final int MT_JTBAllBlackList = 0x4055;
    public static final int MT_SVTCPUAllBlackList = 0x4056;
    public static final int MT_GJICAllBlackList = 0x4057;
    public static final int MT_TP = 0x4058;
    public static final int MT_SleSoftware = 0x4091;
    public static final int MT_TicketStockSnapshot = 0x5001;
    public static final int MT_FtpAudit = 0x6001;
    public static final int MT_AccSettleTxResult = 0x6002;
    public static final int MT_AccSettleTxAdjust = 0x6003;
    public static final int MT_AccSettleClear = 0x6004;
    public static final int MT_SPTFtpAudit = 0x6005;
    public static final int MT_SPTAccSettleTxResult = 0x6006;
    public static final int MT_SPTAccSettleTxAdjust = 0x6007;
    public static final int MT_AccSettleDetailClear = 0x6008;
    public static final int MT_OtherEodControl = 0x4004;
    public static final int MT_OtherTvmUi = 0x4040;

}
// End of MessageType_t.java
