package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class ModeListBodyData_t implements XdrAble {
    public U16_t versionNo;
    public ModeItem_t [] modeList;

    public ModeListBodyData_t() {
    }

    public ModeListBodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        versionNo.xdrEncode(xdr);
        { int $size = modeList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { modeList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        versionNo = new U16_t(xdr);
        { int $size = xdr.xdrDecodeInt(); modeList = new ModeItem_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { modeList[$idx] = new ModeItem_t(xdr); } }
    }

}
// End of ModeListBodyData_t.java
