package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class ModeItem_t implements XdrAble {
    public ModeCode_t modeCode;
    public Date2_t operateDay;
    public LineID_t lineId;
    public StationID_t stationId;
    public AFCTime_t timeOfModeStart;
    public AFCTime_t timeOfModeEnd;

    public ModeItem_t() {
    }

    public ModeItem_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        modeCode.xdrEncode(xdr);
        operateDay.xdrEncode(xdr);
        lineId.xdrEncode(xdr);
        stationId.xdrEncode(xdr);
        timeOfModeStart.xdrEncode(xdr);
        timeOfModeEnd.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        modeCode = new ModeCode_t(xdr);
        operateDay = new Date2_t(xdr);
        lineId = new LineID_t(xdr);
        stationId = new StationID_t(xdr);
        timeOfModeStart = new AFCTime_t(xdr);
        timeOfModeEnd = new AFCTime_t(xdr);
    }

}
// End of ModeItem_t.java
