package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class ModeStation_t implements XdrAble {
    public StationID_t stationId;
    public ModeCode_t mode;

    public ModeStation_t() {
    }

    public ModeStation_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        stationId.xdrEncode(xdr);
        mode.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        stationId = new StationID_t(xdr);
        mode = new ModeCode_t(xdr);
    }

}
// End of ModeStation_t.java
