package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class ModuleStatus_t implements XdrAble {
    public U16_t moduleTypeId;
    public U8_t statusValue;

    public ModuleStatus_t() {
    }

    public ModuleStatus_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        moduleTypeId.xdrEncode(xdr);
        statusValue.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        moduleTypeId = new U16_t(xdr);
        statusValue = new U8_t(xdr);
    }

}
// End of ModuleStatus_t.java
