package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class MultiTripDiscount_t implements XdrAble {
    public U16_t discountCode;
    public U8_t businessMap;
    public Seconds_t validTime;
    public U8_t discountType;
    public ValueCent_t discountValue;
    public U8_t discountRatio;

    public MultiTripDiscount_t() {
    }

    public MultiTripDiscount_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        discountCode.xdrEncode(xdr);
        businessMap.xdrEncode(xdr);
        validTime.xdrEncode(xdr);
        discountType.xdrEncode(xdr);
        discountValue.xdrEncode(xdr);
        discountRatio.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        discountCode = new U16_t(xdr);
        businessMap = new U8_t(xdr);
        validTime = new Seconds_t(xdr);
        discountType = new U8_t(xdr);
        discountValue = new ValueCent_t(xdr);
        discountRatio = new U8_t(xdr);
    }

}
// End of MultiTripDiscount_t.java
