package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class OtherTicketComm_t implements XdrAble {
    public ChipType_t ChipType;
    public U32_t CardType;
    public TicketType_t TicketType;
    public int TicketFamily;
    public TicketLogID_t TicketLogicalID;
    public TicketPhyID_t TicketPhyID;
    public U16_t CityCode;
    public U16_t BusinessCode;
    public U32_t SAMSN;
    public U16_t CountIntotal;
    public U32_t valuePreTx;
    public int testFlag;
    public U8_t cardVerNo;
    public Date2_t CardDate;
    public U32_t SysTN;
    public U16_t ServicInputN;
    public U16_t CardSN;
    public TerminalID_t TerminalID;
    public TicketCatalogID_t TicketCatalogID;
    public U32_t[] Rsvd;

    public OtherTicketComm_t() {
    }

    public OtherTicketComm_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        ChipType.xdrEncode(xdr);
        CardType.xdrEncode(xdr);
        TicketType.xdrEncode(xdr);
        xdr.xdrEncodeInt(TicketFamily);
        TicketLogicalID.xdrEncode(xdr);
        TicketPhyID.xdrEncode(xdr);
        CityCode.xdrEncode(xdr);
        BusinessCode.xdrEncode(xdr);
        SAMSN.xdrEncode(xdr);
        CountIntotal.xdrEncode(xdr);
        valuePreTx.xdrEncode(xdr);
        xdr.xdrEncodeInt(testFlag);
        cardVerNo.xdrEncode(xdr);
        CardDate.xdrEncode(xdr);
        SysTN.xdrEncode(xdr);
        ServicInputN.xdrEncode(xdr);
        CardSN.xdrEncode(xdr);
        TerminalID.xdrEncode(xdr);
        TicketCatalogID.xdrEncode(xdr);
        { int $size = 2; for ( int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        ChipType = new ChipType_t(xdr);
        CardType = new U32_t(xdr);
        TicketType = new TicketType_t(xdr);
        TicketFamily = xdr.xdrDecodeInt();
        TicketLogicalID = new TicketLogID_t(xdr);
        TicketPhyID = new TicketPhyID_t(xdr);
        CityCode = new U16_t(xdr);
        BusinessCode = new U16_t(xdr);
        SAMSN = new U32_t(xdr);
        CountIntotal = new U16_t(xdr);
        valuePreTx = new U32_t(xdr);
        testFlag = xdr.xdrDecodeInt();
        cardVerNo = new U8_t(xdr);
        CardDate = new Date2_t(xdr);
        SysTN = new U32_t(xdr);
        ServicInputN = new U16_t(xdr);
        CardSN = new U16_t(xdr);
        TerminalID = new TerminalID_t(xdr);
        TicketCatalogID = new TicketCatalogID_t(xdr);
        { int $size = 2; Rsvd = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx] = new U32_t(xdr); } }
    }

}
// End of OtherTicketComm_t.java
