package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class OtherMasterBodyData_t implements XdrAble {
    public OtherFileRecord_t [] OtherFileList;

    public OtherMasterBodyData_t() {
    }

    public OtherMasterBodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        { int $size = OtherFileList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { OtherFileList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        { int $size = xdr.xdrDecodeInt(); OtherFileList = new OtherFileRecord_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { OtherFileList[$idx] = new OtherFileRecord_t(xdr); } }
    }

}
// End of OtherMasterBodyData_t.java
