package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Packet_t implements XdrAble {
    public PacketHeader_t PacketHeader;
    public PacketBodyData_t PacketBodyData;
    public MD5_t Md5;

    public Packet_t() {
    }

    public Packet_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        PacketHeader.xdrEncode(xdr);
        PacketBodyData.xdrEncode(xdr);
        Md5.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        PacketHeader = new PacketHeader_t(xdr);
        PacketBodyData = new PacketBodyData_t(xdr);
        Md5 = new MD5_t(xdr);
    }

}
// End of Packet_t.java
