package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class PacketHeader_t implements XdrAble {
    public U16_t PacketLength;
    public int MessageType;
    public U32_t ProtocalVersion;
    public DeviceID_t SenderID;
    public DeviceID_t RecieverID;
    public SN_t SessionID;
    public U32_t SessionFlagMap;

    public PacketHeader_t() {
    }

    public PacketHeader_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        PacketLength.xdrEncode(xdr);
        xdr.xdrEncodeInt(MessageType);
        ProtocalVersion.xdrEncode(xdr);
        SenderID.xdrEncode(xdr);
        RecieverID.xdrEncode(xdr);
        SessionID.xdrEncode(xdr);
        SessionFlagMap.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        PacketLength = new U16_t(xdr);
        MessageType = xdr.xdrDecodeInt();
        ProtocalVersion = new U32_t(xdr);
        SenderID = new DeviceID_t(xdr);
        RecieverID = new DeviceID_t(xdr);
        SessionID = new SN_t(xdr);
        SessionFlagMap = new U32_t(xdr);
    }

}
// End of PacketHeader_t.java
