package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class PacketBodyData_t implements XdrAble {
    public int MessageType;
    public PBD1001_t pbd1001;
    public PBD1002_t pbd1002;
    public PBD1003_t pbd1003;
    public PBD1004_t pbd1004;
    public PBD1005_t pbd1005;
    public PBD1006_t pbd1006;
    public PBD1007_t pbd1007;
    public PBD1008_t pbd1008;
    public PBD1009_t pbd1009;
    public PBD100a_t pbd100a;
    public PBD100b_t pbd100b;
    public PBD100e_t pbd100e;
    public PBD100f_t pbd100f;
    public PBD1010_t pbd1010;
    public PBD1021_t pbd1021;
    public PBD1022_t pbd1022;
    public PBD1023_t pbd1023;
    public PBD1024_t pbd1024;
    public PBD1025_t pbd1025;
    public PBD1030_t pbd1030;
    public PBD1026_t pbd1026;
    public PBD1027_t pbd1027;
    public PBD1028_t pbd1028;
    public PBD1029_t pbd1029;

    public PacketBodyData_t() {
    }

    public PacketBodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(MessageType);
        switch ( MessageType ) {
        case MessageType_t.MT_InitForTx:
            pbd1001.xdrEncode(xdr);
            break;
        case MessageType_t.MT_DataSynch:
            pbd1002.xdrEncode(xdr);
            break;
        case MessageType_t.MT_QueryRunfileVersion:
            pbd1003.xdrEncode(xdr);
            break;
        case MessageType_t.MT_QueryEODVersion:
            pbd1004.xdrEncode(xdr);
            break;
        case MessageType_t.MT_CommandMode:
            pbd1005.xdrEncode(xdr);
            break;
        case MessageType_t.MT_InfoMode:
            pbd1006.xdrEncode(xdr);
            break;
        case MessageType_t.MT_BroadCastMode:
            pbd1007.xdrEncode(xdr);
            break;
        case MessageType_t.MT_QueryMode:
            pbd1008.xdrEncode(xdr);
            break;
        case MessageType_t.MT_InfoFlowData:
            pbd1009.xdrEncode(xdr);
            break;
        case MessageType_t.MT_InfoDeviceStatus:
            pbd100a.xdrEncode(xdr);
            break;
        case MessageType_t.MT_QueryDeviceStatus:
            pbd100b.xdrEncode(xdr);
            break;
        case MessageType_t.MT_Reserved1:
            break;
        case MessageType_t.MT_Reserved2:
            break;
        case MessageType_t.MT_CommandTimeSynch:
            pbd100e.xdrEncode(xdr);
            break;
        case MessageType_t.MT_CommandEQM:
            pbd100f.xdrEncode(xdr);
            break;
        case MessageType_t.MT_InfoDeviceEvent:
            pbd1010.xdrEncode(xdr);
            break;
        case MessageType_t.MT_UserAuthenticate:
            pbd1021.xdrEncode(xdr);
            break;
        case MessageType_t.MT_YPTCardAuthenticate:
            pbd1022.xdrEncode(xdr);
            break;
        case MessageType_t.MT_UserPinChange:
            pbd1023.xdrEncode(xdr);
            break;
        case MessageType_t.MT_CPUCardAuthenticate:
            pbd1024.xdrEncode(xdr);
            break;
        case MessageType_t.MT_CPUCardConfirm:
            pbd1025.xdrEncode(xdr);
            break;
        case MessageType_t.MT_CPUCardSaleCheck:
            pbd1030.xdrEncode(xdr);
            break;
        case MessageType_t.MT_NonImmediateRefundApply:
            pbd1026.xdrEncode(xdr);
            break;
        case MessageType_t.MT_CardAccountQuery:
            pbd1027.xdrEncode(xdr);
            break;
        case MessageType_t.MT_CardAccountSend:
            pbd1028.xdrEncode(xdr);
            break;
        case MessageType_t.MT_NonImmediateRefundConfirm:
            pbd1029.xdrEncode(xdr);
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        MessageType = xdr.xdrDecodeInt();
        switch ( MessageType ) {
        case MessageType_t.MT_InitForTx:
            pbd1001 = new PBD1001_t(xdr);
            break;
        case MessageType_t.MT_DataSynch:
            pbd1002 = new PBD1002_t(xdr);
            break;
        case MessageType_t.MT_QueryRunfileVersion:
            pbd1003 = new PBD1003_t(xdr);
            break;
        case MessageType_t.MT_QueryEODVersion:
            pbd1004 = new PBD1004_t(xdr);
            break;
        case MessageType_t.MT_CommandMode:
            pbd1005 = new PBD1005_t(xdr);
            break;
        case MessageType_t.MT_InfoMode:
            pbd1006 = new PBD1006_t(xdr);
            break;
        case MessageType_t.MT_BroadCastMode:
            pbd1007 = new PBD1007_t(xdr);
            break;
        case MessageType_t.MT_QueryMode:
            pbd1008 = new PBD1008_t(xdr);
            break;
        case MessageType_t.MT_InfoFlowData:
            pbd1009 = new PBD1009_t(xdr);
            break;
        case MessageType_t.MT_InfoDeviceStatus:
            pbd100a = new PBD100a_t(xdr);
            break;
        case MessageType_t.MT_QueryDeviceStatus:
            pbd100b = new PBD100b_t(xdr);
            break;
        case MessageType_t.MT_Reserved1:
            break;
        case MessageType_t.MT_Reserved2:
            break;
        case MessageType_t.MT_CommandTimeSynch:
            pbd100e = new PBD100e_t(xdr);
            break;
        case MessageType_t.MT_CommandEQM:
            pbd100f = new PBD100f_t(xdr);
            break;
        case MessageType_t.MT_InfoDeviceEvent:
            pbd1010 = new PBD1010_t(xdr);
            break;
        case MessageType_t.MT_UserAuthenticate:
            pbd1021 = new PBD1021_t(xdr);
            break;
        case MessageType_t.MT_YPTCardAuthenticate:
            pbd1022 = new PBD1022_t(xdr);
            break;
        case MessageType_t.MT_UserPinChange:
            pbd1023 = new PBD1023_t(xdr);
            break;
        case MessageType_t.MT_CPUCardAuthenticate:
            pbd1024 = new PBD1024_t(xdr);
            break;
        case MessageType_t.MT_CPUCardConfirm:
            pbd1025 = new PBD1025_t(xdr);
            break;
        case MessageType_t.MT_CPUCardSaleCheck:
            pbd1030 = new PBD1030_t(xdr);
            break;
        case MessageType_t.MT_NonImmediateRefundApply:
            pbd1026 = new PBD1026_t(xdr);
            break;
        case MessageType_t.MT_CardAccountQuery:
            pbd1027 = new PBD1027_t(xdr);
            break;
        case MessageType_t.MT_CardAccountSend:
            pbd1028 = new PBD1028_t(xdr);
            break;
        case MessageType_t.MT_NonImmediateRefundConfirm:
            pbd1029 = new PBD1029_t(xdr);
            break;
        }
    }

}
// End of PacketBodyData_t.java
