package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class PassControlData_t implements XdrAble {
    public U16_t maxCountOfTicketOP;
    public U16_t timeoutIntervalOfPassIn;
    public U16_t timeoutIntervalOfPassOut;
    public U16_t delayIntervalOfContinuousPass;
    public U16_t resetIntervalOfError;
    public U16_t delayIntervalOfBreakIn;
    public U16_t delayIntervalOfAGDirectionSwtich;

    public PassControlData_t() {
    }

    public PassControlData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        maxCountOfTicketOP.xdrEncode(xdr);
        timeoutIntervalOfPassIn.xdrEncode(xdr);
        timeoutIntervalOfPassOut.xdrEncode(xdr);
        delayIntervalOfContinuousPass.xdrEncode(xdr);
        resetIntervalOfError.xdrEncode(xdr);
        delayIntervalOfBreakIn.xdrEncode(xdr);
        delayIntervalOfAGDirectionSwtich.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        maxCountOfTicketOP = new U16_t(xdr);
        timeoutIntervalOfPassIn = new U16_t(xdr);
        timeoutIntervalOfPassOut = new U16_t(xdr);
        delayIntervalOfContinuousPass = new U16_t(xdr);
        resetIntervalOfError = new U16_t(xdr);
        delayIntervalOfBreakIn = new U16_t(xdr);
        delayIntervalOfAGDirectionSwtich = new U16_t(xdr);
    }

}
// End of PassControlData_t.java
