package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class PBD1029_t implements XdrAble {
    public int sf;
    public Req1029BodyData_t Req1029BodyData;
    public MackBodyData_t MackBodyData;

    public PBD1029_t() {
    }

    public PBD1029_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(sf);
        switch ( sf ) {
        case SessionFlag_t.SF_Req:
            Req1029BodyData.xdrEncode(xdr);
            break;
        case SessionFlag_t.SF_Resp:
            break;
        case SessionFlag_t.SF_Mack:
            MackBodyData.xdrEncode(xdr);
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        sf = xdr.xdrDecodeInt();
        switch ( sf ) {
        case SessionFlag_t.SF_Req:
            Req1029BodyData = new Req1029BodyData_t(xdr);
            break;
        case SessionFlag_t.SF_Resp:
            break;
        case SessionFlag_t.SF_Mack:
            MackBodyData = new MackBodyData_t(xdr);
            break;
        }
    }

}
// End of PBD1029_t.java
