package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class PBD1002_t implements XdrAble {
    public int sf;
    public Req1002BodyData_t Req1002BodyData;
    public Resp1002BodyData_t Resp1002BodyData;

    public PBD1002_t() {
    }

    public PBD1002_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(sf);
        switch ( sf ) {
        case SessionFlag_t.SF_Req:
            Req1002BodyData.xdrEncode(xdr);
            break;
        case SessionFlag_t.SF_Resp:
            Resp1002BodyData.xdrEncode(xdr);
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        sf = xdr.xdrDecodeInt();
        switch ( sf ) {
        case SessionFlag_t.SF_Req:
            Req1002BodyData = new Req1002BodyData_t(xdr);
            break;
        case SessionFlag_t.SF_Resp:
            Resp1002BodyData = new Resp1002BodyData_t(xdr);
            break;
        }
    }

}
// End of PBD1002_t.java
