package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class PBD1008_t implements XdrAble {
    public int sf;
    public Req1008BodyData_t Req1008BodyData;
    public Resp1008BodyData_t Resp1008BodyData;

    public PBD1008_t() {
    }

    public PBD1008_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(sf);
        switch ( sf ) {
        case SessionFlag_t.SF_Req:
            Req1008BodyData.xdrEncode(xdr);
            break;
        case SessionFlag_t.SF_Resp:
            Resp1008BodyData.xdrEncode(xdr);
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        sf = xdr.xdrDecodeInt();
        switch ( sf ) {
        case SessionFlag_t.SF_Req:
            Req1008BodyData = new Req1008BodyData_t(xdr);
            break;
        case SessionFlag_t.SF_Resp:
            Resp1008BodyData = new Resp1008BodyData_t(xdr);
            break;
        }
    }

}
// End of PBD1008_t.java
