package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class PBD1024_t implements XdrAble {
    public int sf;
    public Req1024BodyData_t Req1024BodyData;
    public Resp1024BodyData_t Resp1024BodyData;

    public PBD1024_t() {
    }

    public PBD1024_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(sf);
        switch ( sf ) {
        case SessionFlag_t.SF_Req:
            Req1024BodyData.xdrEncode(xdr);
            break;
        case SessionFlag_t.SF_Resp:
            Resp1024BodyData.xdrEncode(xdr);
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        sf = xdr.xdrDecodeInt();
        switch ( sf ) {
        case SessionFlag_t.SF_Req:
            Req1024BodyData = new Req1024BodyData_t(xdr);
            break;
        case SessionFlag_t.SF_Resp:
            Resp1024BodyData = new Resp1024BodyData_t(xdr);
            break;
        }
    }

}
// End of PBD1024_t.java
