package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class PbocBinBD_t implements XdrAble {
    public U16_t versionNo;
    public PbocBinInfo_t[] blackList;

    public PbocBinBD_t() {
    }

    public PbocBinBD_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        versionNo.xdrEncode(xdr);
        { int $size = blackList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { blackList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        versionNo = new U16_t(xdr);
        { int $size = xdr.xdrDecodeInt(); blackList = new PbocBinInfo_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { blackList[$idx] = new PbocBinInfo_t(xdr); } }
    }

}
// End of PbocBinBD_t.java
