package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Picture_t implements XdrAble {
    public U16_t areaNumber;
    public U16_t newImageNumber;
    public String cnNewImageFileName;
    public String enNewImageFileName;
    public U16_t newImageXPos;
    public U16_t newImageYPos;
    public U16_t newImageWidth;
    public U16_t newImageHeight;
    public U8_t useFlag;
    public ButtonView_t [] ButtonViewList;

    public Picture_t() {
    }

    public Picture_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        areaNumber.xdrEncode(xdr);
        newImageNumber.xdrEncode(xdr);
        xdr.xdrEncodeString(cnNewImageFileName);
        xdr.xdrEncodeString(enNewImageFileName);
        newImageXPos.xdrEncode(xdr);
        newImageYPos.xdrEncode(xdr);
        newImageWidth.xdrEncode(xdr);
        newImageHeight.xdrEncode(xdr);
        useFlag.xdrEncode(xdr);
        { int $size = ButtonViewList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { ButtonViewList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        areaNumber = new U16_t(xdr);
        newImageNumber = new U16_t(xdr);
        cnNewImageFileName = xdr.xdrDecodeString();
        enNewImageFileName = xdr.xdrDecodeString();
        newImageXPos = new U16_t(xdr);
        newImageYPos = new U16_t(xdr);
        newImageWidth = new U16_t(xdr);
        newImageHeight = new U16_t(xdr);
        useFlag = new U8_t(xdr);
        { int $size = xdr.xdrDecodeInt(); ButtonViewList = new ButtonView_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { ButtonViewList[$idx] = new ButtonView_t(xdr); } }
    }

}
// End of Picture_t.java
