package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class PointDiscount_t implements XdrAble {
    public U16_t discountCode;
    public U8_t discountType;
    public U16_t minCount;
    public ValueCent_t minValue;
    public U8_t discountRatio;
    public U8_t resetType;

    public PointDiscount_t() {
    }

    public PointDiscount_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        discountCode.xdrEncode(xdr);
        discountType.xdrEncode(xdr);
        minCount.xdrEncode(xdr);
        minValue.xdrEncode(xdr);
        discountRatio.xdrEncode(xdr);
        resetType.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        discountCode = new U16_t(xdr);
        discountType = new U8_t(xdr);
        minCount = new U16_t(xdr);
        minValue = new ValueCent_t(xdr);
        discountRatio = new U8_t(xdr);
        resetType = new U8_t(xdr);
    }

}
// End of PointDiscount_t.java
