package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class PriviledgeUser_t implements XdrAble {
    public U32_t userId;
    public String userPin;
    public StationID_t userStation;
    public U8_t useFlag;
    public AFCTime_t validTime;
    public AFCTime_t expireTime;
    public U16_t sleUserFlag;
    public UnicodeString_t userName;
    public U16_t[] roleGrantedList;
    public StationID_t[] stationGrantedList;
    public int [] deviceTypeGrantedList;
    public DeviceID_t [] sleList;

    public PriviledgeUser_t() {
    }

    public PriviledgeUser_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        userId.xdrEncode(xdr);
        xdr.xdrEncodeString(userPin);
        userStation.xdrEncode(xdr);
        useFlag.xdrEncode(xdr);
        validTime.xdrEncode(xdr);
        expireTime.xdrEncode(xdr);
        sleUserFlag.xdrEncode(xdr);
        userName.xdrEncode(xdr);
        { int $size = roleGrantedList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { roleGrantedList[$idx].xdrEncode(xdr); } }
        { int $size = stationGrantedList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { stationGrantedList[$idx].xdrEncode(xdr); } }
        xdr.xdrEncodeIntVector(deviceTypeGrantedList);
        { int $size = sleList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { sleList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        userId = new U32_t(xdr);
        userPin = xdr.xdrDecodeString();
        userStation = new StationID_t(xdr);
        useFlag = new U8_t(xdr);
        validTime = new AFCTime_t(xdr);
        expireTime = new AFCTime_t(xdr);
        sleUserFlag = new U16_t(xdr);
        userName = new UnicodeString_t(xdr);
        { int $size = xdr.xdrDecodeInt(); roleGrantedList = new U16_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { roleGrantedList[$idx] = new U16_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); stationGrantedList = new StationID_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { stationGrantedList[$idx] = new StationID_t(xdr); } }
        deviceTypeGrantedList = xdr.xdrDecodeIntVector();
        { int $size = xdr.xdrDecodeInt(); sleList = new DeviceID_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { sleList[$idx] = new DeviceID_t(xdr); } }
    }

}
// End of PriviledgeUser_t.java
