package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class RangeBlackList_t implements XdrAble {
    public TicketPhyID_t ticketPhyStartID;
    public TicketPhyID_t ticketPhyEndID;
    public U8_t processFlag;

    public RangeBlackList_t() {
    }

    public RangeBlackList_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        ticketPhyStartID.xdrEncode(xdr);
        ticketPhyEndID.xdrEncode(xdr);
        processFlag.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        ticketPhyStartID = new TicketPhyID_t(xdr);
        ticketPhyEndID = new TicketPhyID_t(xdr);
        processFlag = new U8_t(xdr);
    }

}
// End of RangeBlackList_t.java
