package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Req1023BodyData_t implements XdrAble {
    public AFCTime_t currentTime;
    public DeviceID_t deviceID;
    public String userId;
    public U8_t pinCryptFlag;
    public String oldUserPin;
    public String newUserPin;

    public Req1023BodyData_t() {
    }

    public Req1023BodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        currentTime.xdrEncode(xdr);
        deviceID.xdrEncode(xdr);
        xdr.xdrEncodeString(userId);
        pinCryptFlag.xdrEncode(xdr);
        xdr.xdrEncodeString(oldUserPin);
        xdr.xdrEncodeString(newUserPin);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        currentTime = new AFCTime_t(xdr);
        deviceID = new DeviceID_t(xdr);
        userId = xdr.xdrDecodeString();
        pinCryptFlag = new U8_t(xdr);
        oldUserPin = xdr.xdrDecodeString();
        newUserPin = xdr.xdrDecodeString();
    }

}
// End of Req1023BodyData_t.java
