package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Req1007BodyData_t implements XdrAble {
    public AFCTime_t currentTime;
    public ModeStation_t [] modeStationList;

    public Req1007BodyData_t() {
    }

    public Req1007BodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        currentTime.xdrEncode(xdr);
        { int $size = modeStationList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { modeStationList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        currentTime = new AFCTime_t(xdr);
        { int $size = xdr.xdrDecodeInt(); modeStationList = new ModeStation_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { modeStationList[$idx] = new ModeStation_t(xdr); } }
    }

}
// End of Req1007BodyData_t.java
