package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Req1006BodyData_t implements XdrAble {
    public AFCTime_t currentTime;
    public DeviceID_t deviceID;
    public ModeCode_t mode;

    public Req1006BodyData_t() {
    }

    public Req1006BodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        currentTime.xdrEncode(xdr);
        deviceID.xdrEncode(xdr);
        mode.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        currentTime = new AFCTime_t(xdr);
        deviceID = new DeviceID_t(xdr);
        mode = new ModeCode_t(xdr);
    }

}
// End of Req1006BodyData_t.java
