package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Req1002BodyData_t implements XdrAble {
    public AFCTime_t currentTime;
    public int fileType;
    public U8_t operationType;

    public Req1002BodyData_t() {
    }

    public Req1002BodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        currentTime.xdrEncode(xdr);
        xdr.xdrEncodeInt(fileType);
        operationType.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        currentTime = new AFCTime_t(xdr);
        fileType = xdr.xdrDecodeInt();
        operationType = new U8_t(xdr);
    }

}
// End of Req1002BodyData_t.java
