package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Req1025BodyData_t implements XdrAble {
    public DeviceID_t deviceID;
    public TerminalID_t TerminalID;
    public U32_t TransSN;
    public AFCTime_t DepositTime;
    public int TicketFamily;
    public TicketType_t TicketType;
    public TicketLogID_t TicketLogicalID;
    public U16_t CountIntotal;
    public ChipType_t ChipType;
    public OperatorID_t operatorID;
    public PaymentMeans_t paymentMeans;
    public U32_t valuePreTx;
    public U32_t transactionValue;
    public U32_t AfterTxn;
    public ValueCent_t deposit;
    public ValueCent_t txValue;
    public Date2_t Enddate;
    public U32_t RandomN;
    public U32_t MAC1;
    public U8_t Writestatus;
    public TAC_t TAC;
    public U32_t authSessionId;
    public AFCTime_t ACCcurrentTime;
    public U8_t businessType;
    public U8_t IdCardType;
    public U32_t identNo;
    public UnicodeString_t Name;
    public String IdNumber;
    public U32_t[] Rsvd;

    public Req1025BodyData_t() {
    }

    public Req1025BodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        deviceID.xdrEncode(xdr);
        TerminalID.xdrEncode(xdr);
        TransSN.xdrEncode(xdr);
        DepositTime.xdrEncode(xdr);
        xdr.xdrEncodeInt(TicketFamily);
        TicketType.xdrEncode(xdr);
        TicketLogicalID.xdrEncode(xdr);
        CountIntotal.xdrEncode(xdr);
        ChipType.xdrEncode(xdr);
        operatorID.xdrEncode(xdr);
        paymentMeans.xdrEncode(xdr);
        valuePreTx.xdrEncode(xdr);
        transactionValue.xdrEncode(xdr);
        AfterTxn.xdrEncode(xdr);
        deposit.xdrEncode(xdr);
        txValue.xdrEncode(xdr);
        Enddate.xdrEncode(xdr);
        RandomN.xdrEncode(xdr);
        MAC1.xdrEncode(xdr);
        Writestatus.xdrEncode(xdr);
        TAC.xdrEncode(xdr);
        authSessionId.xdrEncode(xdr);
        ACCcurrentTime.xdrEncode(xdr);
        businessType.xdrEncode(xdr);
        IdCardType.xdrEncode(xdr);
        identNo.xdrEncode(xdr);
        Name.xdrEncode(xdr);
        xdr.xdrEncodeString(IdNumber);
        { int $size = 3; for ( int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        deviceID = new DeviceID_t(xdr);
        TerminalID = new TerminalID_t(xdr);
        TransSN = new U32_t(xdr);
        DepositTime = new AFCTime_t(xdr);
        TicketFamily = xdr.xdrDecodeInt();
        TicketType = new TicketType_t(xdr);
        TicketLogicalID = new TicketLogID_t(xdr);
        CountIntotal = new U16_t(xdr);
        ChipType = new ChipType_t(xdr);
        operatorID = new OperatorID_t(xdr);
        paymentMeans = new PaymentMeans_t(xdr);
        valuePreTx = new U32_t(xdr);
        transactionValue = new U32_t(xdr);
        AfterTxn = new U32_t(xdr);
        deposit = new ValueCent_t(xdr);
        txValue = new ValueCent_t(xdr);
        Enddate = new Date2_t(xdr);
        RandomN = new U32_t(xdr);
        MAC1 = new U32_t(xdr);
        Writestatus = new U8_t(xdr);
        TAC = new TAC_t(xdr);
        authSessionId = new U32_t(xdr);
        ACCcurrentTime = new AFCTime_t(xdr);
        businessType = new U8_t(xdr);
        IdCardType = new U8_t(xdr);
        identNo = new U32_t(xdr);
        Name = new UnicodeString_t(xdr);
        IdNumber = xdr.xdrDecodeString();
        { int $size = 3; Rsvd = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx] = new U32_t(xdr); } }
    }

}
// End of Req1025BodyData_t.java
