package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Req1030BodyData_t implements XdrAble {
    public SN_t UDSN;
    public AFCTime_t currentTime;
    public DeviceID_t deviceID;
    public SAMID_t TACSamID;
    public TicketLogID_t TicketLogicalID;
    public U32_t RandomN;
    public U32_t[] FensanNo;
    public String APDU;

    public Req1030BodyData_t() {
    }

    public Req1030BodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        UDSN.xdrEncode(xdr);
        currentTime.xdrEncode(xdr);
        deviceID.xdrEncode(xdr);
        TACSamID.xdrEncode(xdr);
        TicketLogicalID.xdrEncode(xdr);
        RandomN.xdrEncode(xdr);
        { int $size = 2; for ( int $idx = 0; $idx < $size; ++$idx ) { FensanNo[$idx].xdrEncode(xdr); } }
        xdr.xdrEncodeString(APDU);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        UDSN = new SN_t(xdr);
        currentTime = new AFCTime_t(xdr);
        deviceID = new DeviceID_t(xdr);
        TACSamID = new SAMID_t(xdr);
        TicketLogicalID = new TicketLogID_t(xdr);
        RandomN = new U32_t(xdr);
        { int $size = 2; FensanNo = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { FensanNo[$idx] = new U32_t(xdr); } }
        APDU = xdr.xdrDecodeString();
    }

}
// End of Req1030BodyData_t.java
