package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Req100fBodyData_t implements XdrAble {
    public AFCTime_t currentTime;
    public DeviceID_t deviceId;
    public U8_t commandType;
    public U16_t commandCode;

    public Req100fBodyData_t() {
    }

    public Req100fBodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        currentTime.xdrEncode(xdr);
        deviceId.xdrEncode(xdr);
        commandType.xdrEncode(xdr);
        commandCode.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        currentTime = new AFCTime_t(xdr);
        deviceId = new DeviceID_t(xdr);
        commandType = new U8_t(xdr);
        commandCode = new U16_t(xdr);
    }

}
// End of Req100fBodyData_t.java
