package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Req1029BodyData_t implements XdrAble {
    public DeviceID_t deviceID;
    public String ApplyNb;
    public AFCTime_t ACCcurrentTime;
    public OperatorID_t operatorID;
    public TicketPhyID_t TicketPhyID;
    public TicketLogID_t TicketLogicalID;
    public TicketPrintID_t TicketPrintID;
    public UnicodeString_t Name;
    public U8_t IdCardType;
    public String IdNumber;
    public String TelephoneCode;
    public int TicketFamily;
    public TicketType_t TicketType;
    public U8_t RefundResult;
    public U8_t RefundType;
    public ValueCent_t TransactionValue;
    public U32_t[] Rsvd;

    public Req1029BodyData_t() {
    }

    public Req1029BodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        deviceID.xdrEncode(xdr);
        xdr.xdrEncodeString(ApplyNb);
        ACCcurrentTime.xdrEncode(xdr);
        operatorID.xdrEncode(xdr);
        TicketPhyID.xdrEncode(xdr);
        TicketLogicalID.xdrEncode(xdr);
        TicketPrintID.xdrEncode(xdr);
        Name.xdrEncode(xdr);
        IdCardType.xdrEncode(xdr);
        xdr.xdrEncodeString(IdNumber);
        xdr.xdrEncodeString(TelephoneCode);
        xdr.xdrEncodeInt(TicketFamily);
        TicketType.xdrEncode(xdr);
        RefundResult.xdrEncode(xdr);
        RefundType.xdrEncode(xdr);
        TransactionValue.xdrEncode(xdr);
        { int $size = 2; for ( int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        deviceID = new DeviceID_t(xdr);
        ApplyNb = xdr.xdrDecodeString();
        ACCcurrentTime = new AFCTime_t(xdr);
        operatorID = new OperatorID_t(xdr);
        TicketPhyID = new TicketPhyID_t(xdr);
        TicketLogicalID = new TicketLogID_t(xdr);
        TicketPrintID = new TicketPrintID_t(xdr);
        Name = new UnicodeString_t(xdr);
        IdCardType = new U8_t(xdr);
        IdNumber = xdr.xdrDecodeString();
        TelephoneCode = xdr.xdrDecodeString();
        TicketFamily = xdr.xdrDecodeInt();
        TicketType = new TicketType_t(xdr);
        RefundResult = new U8_t(xdr);
        RefundType = new U8_t(xdr);
        TransactionValue = new ValueCent_t(xdr);
        { int $size = 2; Rsvd = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx] = new U32_t(xdr); } }
    }

}
// End of Req1029BodyData_t.java
