package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Req1024BodyData_t implements XdrAble {
    public SN_t UDSN;
    public AFCTime_t currentTime;
    public DeviceID_t deviceID;
    public SAMID_t TACSamID;
    public int TicketFamily;
    public TicketType_t TicketType;
    public TicketLogID_t TicketLogicalID;
    public ChipType_t ChipType;
    public U8_t businessType;
    public ValueCent_t deposit;
    public ValueCent_t txValue;
    public U32_t transactionValue;
    public Date2_t Startdate;
    public Date2_t Enddate;
    public U32_t MAC1;
    public U32_t RandomN;
    public U32_t valuePreTx;
    public U16_t CountIntotal;
    public U8_t RechargeFlag;
    public TerminalID_t TerminalID;
    public U32_t[] Rsvd;

    public Req1024BodyData_t() {
    }

    public Req1024BodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        UDSN.xdrEncode(xdr);
        currentTime.xdrEncode(xdr);
        deviceID.xdrEncode(xdr);
        TACSamID.xdrEncode(xdr);
        xdr.xdrEncodeInt(TicketFamily);
        TicketType.xdrEncode(xdr);
        TicketLogicalID.xdrEncode(xdr);
        ChipType.xdrEncode(xdr);
        businessType.xdrEncode(xdr);
        deposit.xdrEncode(xdr);
        txValue.xdrEncode(xdr);
        transactionValue.xdrEncode(xdr);
        Startdate.xdrEncode(xdr);
        Enddate.xdrEncode(xdr);
        MAC1.xdrEncode(xdr);
        RandomN.xdrEncode(xdr);
        valuePreTx.xdrEncode(xdr);
        CountIntotal.xdrEncode(xdr);
        RechargeFlag.xdrEncode(xdr);
        TerminalID.xdrEncode(xdr);
        { int $size = 4; for ( int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        UDSN = new SN_t(xdr);
        currentTime = new AFCTime_t(xdr);
        deviceID = new DeviceID_t(xdr);
        TACSamID = new SAMID_t(xdr);
        TicketFamily = xdr.xdrDecodeInt();
        TicketType = new TicketType_t(xdr);
        TicketLogicalID = new TicketLogID_t(xdr);
        ChipType = new ChipType_t(xdr);
        businessType = new U8_t(xdr);
        deposit = new ValueCent_t(xdr);
        txValue = new ValueCent_t(xdr);
        transactionValue = new U32_t(xdr);
        Startdate = new Date2_t(xdr);
        Enddate = new Date2_t(xdr);
        MAC1 = new U32_t(xdr);
        RandomN = new U32_t(xdr);
        valuePreTx = new U32_t(xdr);
        CountIntotal = new U16_t(xdr);
        RechargeFlag = new U8_t(xdr);
        TerminalID = new TerminalID_t(xdr);
        { int $size = 4; Rsvd = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx] = new U32_t(xdr); } }
    }

}
// End of Req1024BodyData_t.java
