package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Req1009BodyData_t implements XdrAble {
    public AFCTime_t currentTime;
    public DeviceID_t deviceID;
    public AFCTime_t timeOfStart;
    public AFCTime_t timeOfStatics;
    public U32_t inCount;
    public U32_t outCount;
    public U32_t saleCount;

    public Req1009BodyData_t() {
    }

    public Req1009BodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        currentTime.xdrEncode(xdr);
        deviceID.xdrEncode(xdr);
        timeOfStart.xdrEncode(xdr);
        timeOfStatics.xdrEncode(xdr);
        inCount.xdrEncode(xdr);
        outCount.xdrEncode(xdr);
        saleCount.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        currentTime = new AFCTime_t(xdr);
        deviceID = new DeviceID_t(xdr);
        timeOfStart = new AFCTime_t(xdr);
        timeOfStatics = new AFCTime_t(xdr);
        inCount = new U32_t(xdr);
        outCount = new U32_t(xdr);
        saleCount = new U32_t(xdr);
    }

}
// End of Req1009BodyData_t.java
