package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Req1022BodyData_t implements XdrAble {
    public AFCTime_t currentTime;
    public DeviceID_t deviceID;
    public SAMID_t psamId;
    public TicketPhyID_t phyTicketId;
    public U16_t cityCode;
    public TicketLogicalID_t logicalTicketId;
    public U32_t cardCode;
    public U8_t businessType;
    public ValueCent_t deposit;
    public ValueCent_t txValue;

    public Req1022BodyData_t() {
    }

    public Req1022BodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        currentTime.xdrEncode(xdr);
        deviceID.xdrEncode(xdr);
        psamId.xdrEncode(xdr);
        phyTicketId.xdrEncode(xdr);
        cityCode.xdrEncode(xdr);
        logicalTicketId.xdrEncode(xdr);
        cardCode.xdrEncode(xdr);
        businessType.xdrEncode(xdr);
        deposit.xdrEncode(xdr);
        txValue.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        currentTime = new AFCTime_t(xdr);
        deviceID = new DeviceID_t(xdr);
        psamId = new SAMID_t(xdr);
        phyTicketId = new TicketPhyID_t(xdr);
        cityCode = new U16_t(xdr);
        logicalTicketId = new TicketLogicalID_t(xdr);
        cardCode = new U32_t(xdr);
        businessType = new U8_t(xdr);
        deposit = new ValueCent_t(xdr);
        txValue = new ValueCent_t(xdr);
    }

}
// End of Req1022BodyData_t.java
