package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Req1028BodyData_t implements XdrAble {
    public DeviceID_t deviceID;
    public AFCTime_t ACCcurrentTime;
    public String ApplyNb;
    public TicketPhyID_t TicketPhyID;
    public TicketLogID_t TicketLogicalID;
    public TicketPrintID_t TicketPrintID;
    public U8_t AccTicketStatus;
    public UnicodeString_t Name;
    public U8_t IdCardType;
    public String IdNumber;
    public String Phone;
    public int TicketFamily;
    public TicketType_t TicketType;
    public U32_t RemainingValue;
    public ValueCent_t forgiveValue;
    public OperatorID_t operatorID;
    public AFCTime_t ConfirmTimeAtAcc;
    public OperatorID_t OperatorIDAtAcc;
    public ValueCent_t RemainingValueAtAcc;
    public ValueCent_t forgiveValueAtAcc;
    public U8_t ApplicationResults;
    public U32_t[] Rsvd;

    public Req1028BodyData_t() {
    }

    public Req1028BodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        deviceID.xdrEncode(xdr);
        ACCcurrentTime.xdrEncode(xdr);
        xdr.xdrEncodeString(ApplyNb);
        TicketPhyID.xdrEncode(xdr);
        TicketLogicalID.xdrEncode(xdr);
        TicketPrintID.xdrEncode(xdr);
        AccTicketStatus.xdrEncode(xdr);
        Name.xdrEncode(xdr);
        IdCardType.xdrEncode(xdr);
        xdr.xdrEncodeString(IdNumber);
        xdr.xdrEncodeString(Phone);
        xdr.xdrEncodeInt(TicketFamily);
        TicketType.xdrEncode(xdr);
        RemainingValue.xdrEncode(xdr);
        forgiveValue.xdrEncode(xdr);
        operatorID.xdrEncode(xdr);
        ConfirmTimeAtAcc.xdrEncode(xdr);
        OperatorIDAtAcc.xdrEncode(xdr);
        RemainingValueAtAcc.xdrEncode(xdr);
        forgiveValueAtAcc.xdrEncode(xdr);
        ApplicationResults.xdrEncode(xdr);
        { int $size = 4; for ( int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        deviceID = new DeviceID_t(xdr);
        ACCcurrentTime = new AFCTime_t(xdr);
        ApplyNb = xdr.xdrDecodeString();
        TicketPhyID = new TicketPhyID_t(xdr);
        TicketLogicalID = new TicketLogID_t(xdr);
        TicketPrintID = new TicketPrintID_t(xdr);
        AccTicketStatus = new U8_t(xdr);
        Name = new UnicodeString_t(xdr);
        IdCardType = new U8_t(xdr);
        IdNumber = xdr.xdrDecodeString();
        Phone = xdr.xdrDecodeString();
        TicketFamily = xdr.xdrDecodeInt();
        TicketType = new TicketType_t(xdr);
        RemainingValue = new U32_t(xdr);
        forgiveValue = new ValueCent_t(xdr);
        operatorID = new OperatorID_t(xdr);
        ConfirmTimeAtAcc = new AFCTime_t(xdr);
        OperatorIDAtAcc = new OperatorID_t(xdr);
        RemainingValueAtAcc = new ValueCent_t(xdr);
        forgiveValueAtAcc = new ValueCent_t(xdr);
        ApplicationResults = new U8_t(xdr);
        { int $size = 4; Rsvd = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx] = new U32_t(xdr); } }
    }

}
// End of Req1028BodyData_t.java
