package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Req1027BodyData_t implements XdrAble {
    public U8_t QueryType;
    public DeviceID_t deviceID;
    public String ApplyNb;
    public TicketPhyID_t TicketPhyID;
    public TicketLogID_t TicketLogicalID;
    public TicketPrintID_t TicketPrintID;
    public UnicodeString_t Name;
    public U8_t IdCardType;
    public String IdNumber;
    public U32_t[] Rsvd;

    public Req1027BodyData_t() {
    }

    public Req1027BodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        QueryType.xdrEncode(xdr);
        deviceID.xdrEncode(xdr);
        xdr.xdrEncodeString(ApplyNb);
        TicketPhyID.xdrEncode(xdr);
        TicketLogicalID.xdrEncode(xdr);
        TicketPrintID.xdrEncode(xdr);
        Name.xdrEncode(xdr);
        IdCardType.xdrEncode(xdr);
        xdr.xdrEncodeString(IdNumber);
        { int $size = 4; for ( int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        QueryType = new U8_t(xdr);
        deviceID = new DeviceID_t(xdr);
        ApplyNb = xdr.xdrDecodeString();
        TicketPhyID = new TicketPhyID_t(xdr);
        TicketLogicalID = new TicketLogID_t(xdr);
        TicketPrintID = new TicketPrintID_t(xdr);
        Name = new UnicodeString_t(xdr);
        IdCardType = new U8_t(xdr);
        IdNumber = xdr.xdrDecodeString();
        { int $size = 4; Rsvd = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx] = new U32_t(xdr); } }
    }

}
// End of Req1027BodyData_t.java
