package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class ResolutionInfo_t implements XdrAble {
    public U8_t resolutionNumber;
    public U16_t screenWidth;
    public U16_t screenHeight;

    public ResolutionInfo_t() {
    }

    public ResolutionInfo_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        resolutionNumber.xdrEncode(xdr);
        screenWidth.xdrEncode(xdr);
        screenHeight.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        resolutionNumber = new U8_t(xdr);
        screenWidth = new U16_t(xdr);
        screenHeight = new U16_t(xdr);
    }

}
// End of ResolutionInfo_t.java
