package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Resp100bBodyData_t implements XdrAble {
    public U8_t result;
    public AFCTime_t currentTime;
    public DeviceID_t deviceID;
    public U8_t deviceStatus;
    public ModuleStatus_t [] moduleStatus;

    public Resp100bBodyData_t() {
    }

    public Resp100bBodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        result.xdrEncode(xdr);
        currentTime.xdrEncode(xdr);
        deviceID.xdrEncode(xdr);
        deviceStatus.xdrEncode(xdr);
        { int $size = moduleStatus.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { moduleStatus[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        result = new U8_t(xdr);
        currentTime = new AFCTime_t(xdr);
        deviceID = new DeviceID_t(xdr);
        deviceStatus = new U8_t(xdr);
        { int $size = xdr.xdrDecodeInt(); moduleStatus = new ModuleStatus_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { moduleStatus[$idx] = new ModuleStatus_t(xdr); } }
    }

}
// End of Resp100bBodyData_t.java
