package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Resp1008BodyData_t implements XdrAble {
    public U8_t result;
    public ModeCode_t modeInUse;
    public String modeListFile;
    public ModeStation_t [] modeStationList;

    public Resp1008BodyData_t() {
    }

    public Resp1008BodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        result.xdrEncode(xdr);
        modeInUse.xdrEncode(xdr);
        xdr.xdrEncodeString(modeListFile);
        { int $size = modeStationList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { modeStationList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        result = new U8_t(xdr);
        modeInUse = new ModeCode_t(xdr);
        modeListFile = xdr.xdrDecodeString();
        { int $size = xdr.xdrDecodeInt(); modeStationList = new ModeStation_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { modeStationList[$idx] = new ModeStation_t(xdr); } }
    }

}
// End of Resp1008BodyData_t.java
