package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Resp1001BodyData_t implements XdrAble {
    public U8_t result;
    public FtpAccountInfo_t [] ftpAccountList;

    public Resp1001BodyData_t() {
    }

    public Resp1001BodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        result.xdrEncode(xdr);
        { int $size = ftpAccountList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { ftpAccountList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        result = new U8_t(xdr);
        { int $size = xdr.xdrDecodeInt(); ftpAccountList = new FtpAccountInfo_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { ftpAccountList[$idx] = new FtpAccountInfo_t(xdr); } }
    }

}
// End of Resp1001BodyData_t.java
