package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Resp1004BodyData_t implements XdrAble {
    public U8_t result;
    public VersionItem_t[] EODListVersion;

    public Resp1004BodyData_t() {
    }

    public Resp1004BodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        result.xdrEncode(xdr);
        { int $size = EODListVersion.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { EODListVersion[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        result = new U8_t(xdr);
        { int $size = xdr.xdrDecodeInt(); EODListVersion = new VersionItem_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { EODListVersion[$idx] = new VersionItem_t(xdr); } }
    }

}
// End of Resp1004BodyData_t.java
