package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Resp1024BodyData_t implements XdrAble {
    public U8_t result;
    public U32_t authSessionId;
    public AFCTime_t ACCcurrentTime;
    public U32_t MAC2;

    public Resp1024BodyData_t() {
    }

    public Resp1024BodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        result.xdrEncode(xdr);
        authSessionId.xdrEncode(xdr);
        ACCcurrentTime.xdrEncode(xdr);
        MAC2.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        result = new U8_t(xdr);
        authSessionId = new U32_t(xdr);
        ACCcurrentTime = new AFCTime_t(xdr);
        MAC2 = new U32_t(xdr);
    }

}
// End of Resp1024BodyData_t.java
