package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class RunFileRecord_t implements XdrAble {
    public int configFileType;
    public String configFileName;
    public U16_t versionNo;

    public RunFileRecord_t() {
    }

    public RunFileRecord_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(configFileType);
        xdr.xdrEncodeString(configFileName);
        versionNo.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        configFileType = xdr.xdrDecodeInt();
        configFileName = xdr.xdrDecodeString();
        versionNo = new U16_t(xdr);
    }

}
// End of RunFileRecord_t.java
