package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class RunMasterBodyData_t implements XdrAble {
    public RunFileRecord_t [] runFileList;

    public RunMasterBodyData_t() {
    }

    public RunMasterBodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        { int $size = runFileList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { runFileList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        { int $size = xdr.xdrDecodeInt(); runFileList = new RunFileRecord_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { runFileList[$idx] = new RunFileRecord_t(xdr); } }
    }

}
// End of RunMasterBodyData_t.java
