package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
/**
 * Enumeration (collection of constants).
 */
public interface SessionFlag_t {

    public static final int SF_Req = 0;
    public static final int SF_Resp = 1;
    public static final int SF_Mack = 2;

}
// End of SessionFlag_t.java
