package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class settledFile_t implements XdrAble {
    public String fileName;
    public CorrectTx_t [] CorrectTxList;
    public DoubtTx_t [] doubtTxList;

    public settledFile_t() {
    }

    public settledFile_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeString(fileName);
        { int $size = CorrectTxList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { CorrectTxList[$idx].xdrEncode(xdr); } }
        { int $size = doubtTxList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { doubtTxList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        fileName = xdr.xdrDecodeString();
        { int $size = xdr.xdrDecodeInt(); CorrectTxList = new CorrectTx_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { CorrectTxList[$idx] = new CorrectTx_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); doubtTxList = new DoubtTx_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { doubtTxList[$idx] = new DoubtTx_t(xdr); } }
    }

}
// End of settledFile_t.java
