package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class SettleAdjustBodyData_t implements XdrAble {
    public Date2_t settleDate;
    public AdjustFile_t[] adjustFileList;

    public SettleAdjustBodyData_t() {
    }

    public SettleAdjustBodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        settleDate.xdrEncode(xdr);
        { int $size = adjustFileList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { adjustFileList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        settleDate = new Date2_t(xdr);
        { int $size = xdr.xdrDecodeInt(); adjustFileList = new AdjustFile_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { adjustFileList[$idx] = new AdjustFile_t(xdr); } }
    }

}
// End of SettleAdjustBodyData_t.java
