package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class SLEAR_t implements XdrAble {
    public int deviceType;
    public AGMAR_t agmAr;
    public TVMAR_t tvmAr;
    public BOMAR_t bomAr;

    public SLEAR_t() {
    }

    public SLEAR_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(deviceType);
        switch ( deviceType ) {
        case DeviceType_t.DT_AGM:
            agmAr.xdrEncode(xdr);
            break;
        case DeviceType_t.DT_TVM:
            tvmAr.xdrEncode(xdr);
            break;
        case DeviceType_t.DT_BOM:
            bomAr.xdrEncode(xdr);
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        deviceType = xdr.xdrDecodeInt();
        switch ( deviceType ) {
        case DeviceType_t.DT_AGM:
            agmAr = new AGMAR_t(xdr);
            break;
        case DeviceType_t.DT_TVM:
            tvmAr = new TVMAR_t(xdr);
            break;
        case DeviceType_t.DT_BOM:
            bomAr = new BOMAR_t(xdr);
            break;
        }
    }

}
// End of SLEAR_t.java
