package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class SLEARMSGNew_t implements XdrAble {
    public ARFileTag_t ARFileTag;
    public ARCommNew_t ARCommNew;
    public SLEAR_t ARData;

    public SLEARMSGNew_t() {
    }

    public SLEARMSGNew_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        ARFileTag.xdrEncode(xdr);
        ARCommNew.xdrEncode(xdr);
        ARData.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        ARFileTag = new ARFileTag_t(xdr);
        ARCommNew = new ARCommNew_t(xdr);
        ARData = new SLEAR_t(xdr);
    }

}
// End of SLEARMSGNew_t.java
