package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */

import org.acplt.oncrpc.*;

import java.io.IOException;

public class SLEUD_t implements XdrAble {
    public int transactionType;
    public TXSJTInit_t TXSJTInit;
    public TXSJTSale_t TXSJTSale;
    public TXSJTEntryExit_t TXSJTEntry;
    public TXSJTEntryExit_t TXSJTExit;
    public TXSJTChangeEntryExit_t TXSJTChangeEntry;
    public TXSJTChangeEntryExit_t TXSJTChangeExit;
    public TXSJTUpdate_t TXSJTUpdate;
    public TXSJTRefund_t TXSJTRefund;
    public TXSJTBlock_t TXSJTBlock;
    public TXSVTInit_t TXYptInit;
    public TXSVTSaleDeposit_t TXYptAddValue;
    public TXSVTSaleDeposit_t TXSvtSale;
    public TXSVTSaleDeposit_t TXDevSale;
    public TXYKTEntryExit_t TXYKTEntry;
    public TXYKTEntryExit_t TXYKTExit;
    public TXYKTChangeEntryExit_t TXYKTChangeEntry;
    public TXYKTChangeEntryExit_t TXYKTChangeExit;
    public TXYKTUpdate_t TXYKTUpdate;
    public TXYKTSaleDeposit_t TXYKTSale;
    public TXYKTSaleDeposit_t TXYKTAddValue;
    public TXYKTAdmin_t TXYKTBlock;
    public TXICEntryExit_t TXICEntry;
    public TXICEntryExit_t TXICExit;
    public TXICUpdate_t TXICUpdate;
    public TXSVTCPUInit_t TXSVTCPUInit;
    public TXSVTCPUSaleDeposit_t TXSVTCPUAddValue;
    public TXSVTCPUSaleDeposit_t TXSVTCPUSale;
    public TXSVTCPUEntryExit_t TXSVTCPUEntry;
    public TXSVTCPUEntryExit_t TXSVTCPUExit;
    public TXSVTCPUChangeEntryExit_t TXSVTChangeCPUEntry;
    public TXSVTCPUChangeEntryExit_t TXSVTChangeCPUExit;
    public TXSVTCPUUpdate_t TXSVTCPUUpdate;
    public TXSVTCPUAdmin_t TXSVTCPUBlock;
    public TXSVTCPUAdmin_t TXSVTCPUUnlock;
    public TXSVTCPUImmediateRefund_t TXSVTCPUImRefund;
    public TXSVTCPUNonImmediateRefund_t TXSVTCPUNonImRefund;
    public TXSVTCPUCheck_t TXSVTCPUCheck;
    public TXJTBEntryExit_t TXJTBEntry;
    public TXJTBEntryExit_t TXJTBExit;
    public TXJTBChangeEntryExit_t TXJTBChangeEntry;
    public TXJTBChangeEntryExit_t TXJTBChangeExit;
    public TXJTBUpdate_t TXJTBUpdate;
    public TXJTBSaleDeposit_t TXJTBAddValue;
    public TXJTBSaleDeposit_t TXJTBSale;
    public TXJTBAdmin_t TXJTBBlock;
    public TXGJICEntryExit_t TXGJICEntry;
    public TXGJICEntryExit_t TXGJICExit;
    public TXGJICSaleDeposit_t TXGJICAddValue;
    public TXGJICUpdate_t TXGJICUpdate;
    public TXGJICAdmin_t TXGJICBlock;
    public TXYKTAdmin_t YKTCheck;
    public TXQpayEntryExit_t TXQpayEntry;
    public TXQpayEntryExit_t TXQpayExit;
    public TXQpayUpdate_t TXQpayUpdate;
    public TXQpayRefund_t TXQpayRefund;
    public TXQrcodeEntryExit_t TXQrcodeEntry;
    public TXQrcodeEntryExit_t TXQrcodeExit;
    public TXQrcodeUpdate_t TXQrcodeUpdate;
    public TXQrcodeRefund_t TXQrcodeRefund;
    public TXFaceEntryExit_t TXFaceEntry;
    public TXFaceEntryExit_t TXFaceExit;
    public TXFaceUpdate_t TXFaceUpdate;
    public TXFaceRefund_t TXFaceRefund;
    public TXJTBAdmin_t TXJTBCheck;

    public SLEUD_t() {
    }

    public SLEUD_t(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
            throws OncRpcException, IOException {
        xdr.xdrEncodeInt(transactionType);
        switch (transactionType) {
            case TransactionType_t.TXT_YptInit:
                TXSJTInit.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_YptSale:
                TXSJTSale.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_YptEntry:
                TXSJTEntry.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_YptExit:
                TXSJTExit.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_YptChangeEntry:
                TXSJTChangeEntry.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_YptChangeExit:
                TXSJTChangeExit.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_YptUpdate:
                TXSJTUpdate.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_YptRefund:
                TXSJTRefund.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_YptBlock:
                TXSJTBlock.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_YptSVTInit:
                TXYptInit.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_YptAddValue:
                TXYptAddValue.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_YptSVTSale:
                TXSvtSale.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_YptDEVSale:
                TXDevSale.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_YktEntry:
                TXYKTEntry.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_YktExit:
                TXYKTExit.xdrEncode(xdr);
                break;
//        case TXT_YktChaneEntry:
//            TXYKTChangeEntry.xdrEncode(xdr);
//            break;
            case TransactionType_t.TXT_YktChangeExit:
                TXYKTChangeExit.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_YktUpdate:
                TXYKTUpdate.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_YktSale:
                TXYKTSale.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_YktAddValue:
                TXYKTAddValue.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_YktBlock:
                TXYKTBlock.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_ICEntry:
                TXICEntry.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_ICExit:
                TXICExit.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_ICUpdate:
                TXICUpdate.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_SVTCPUInit:
                TXSVTCPUInit.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_SVTCPUAddValue:
                TXSVTCPUAddValue.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_SVTCPUSale:
                TXSVTCPUSale.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_SVTCPUEntry:
                TXSVTCPUEntry.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_SVTCPUExit:
                TXSVTCPUExit.xdrEncode(xdr);
                break;
//        case TXT_SVTChangeCPUEntry:
//            TXSVTChangeCPUEntry.xdrEncode(xdr);
//            break;
//        case TXT_SVTChangeCPUExit:
//            TXSVTChangeCPUExit.xdrEncode(xdr);
//            break;
            case TransactionType_t.TXT_SVTCPUUpdate:
                TXSVTCPUUpdate.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_SVTCPUBlock:
                TXSVTCPUBlock.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_SVTCPUUnlock:
                TXSVTCPUUnlock.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_SVTCPUImmediateRefund:
                TXSVTCPUImRefund.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_SVTCPUNonImmediateRefund:
                TXSVTCPUNonImRefund.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_SVTCPUCheck:
                TXSVTCPUCheck.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_JTBEntry:
                TXJTBEntry.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_JTBExit:
                TXJTBExit.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_JTBChangeEntry:
                TXJTBChangeEntry.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_JTBChangeExit:
                TXJTBChangeExit.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_JTBUpdate:
                TXJTBUpdate.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_JTBAddValue:
                TXJTBAddValue.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_JTBSale:
                TXJTBSale.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_JTBBlock:
                TXJTBBlock.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_GJICEntry:
                TXGJICEntry.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_GJICExit:
                TXGJICExit.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_GJICAddValue:
                TXGJICAddValue.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_GJICUpdate:
                TXGJICUpdate.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_GJICBlock:
                TXGJICBlock.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_YktCheck:
                YKTCheck.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_QpayEntry:
                TXQpayEntry.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_QpayExit:
                TXQpayExit.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_QpayUpdate:
                TXQpayUpdate.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_QpayRefund:
                TXQpayRefund.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_QrcodeEntry:
                TXQrcodeEntry.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_QrcodeExit:
                TXQrcodeExit.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_QrcodeUpdate:
                TXQrcodeUpdate.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_QrcodeRefund:
                TXQrcodeRefund.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_FaceEntry:
                TXFaceEntry.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_FaceExit:
                TXFaceExit.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_FaceUpdate:
                TXFaceUpdate.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_FaceRefund:
                TXFaceRefund.xdrEncode(xdr);
                break;
            case TransactionType_t.TXT_JTBCheck:
                TXJTBCheck.xdrEncode(xdr);
                break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        transactionType = xdr.xdrDecodeInt();
        switch (transactionType) {
            case TransactionType_t.TXT_YptInit:
                TXSJTInit = new TXSJTInit_t(xdr);
                break;
            case TransactionType_t.TXT_YptSale:
                TXSJTSale = new TXSJTSale_t(xdr);
                break;
            case TransactionType_t.TXT_YptEntry:
                TXSJTEntry = new TXSJTEntryExit_t(xdr);
                break;
            case TransactionType_t.TXT_YptExit:
                TXSJTExit = new TXSJTEntryExit_t(xdr);
                break;
            case TransactionType_t.TXT_YptChangeEntry:
                TXSJTChangeEntry = new TXSJTChangeEntryExit_t(xdr);
                break;
            case TransactionType_t.TXT_YptChangeExit:
                TXSJTChangeExit = new TXSJTChangeEntryExit_t(xdr);
                break;
            case TransactionType_t.TXT_YptUpdate:
                TXSJTUpdate = new TXSJTUpdate_t(xdr);
                break;
            case TransactionType_t.TXT_YptRefund:
                TXSJTRefund = new TXSJTRefund_t(xdr);
                break;
            case TransactionType_t.TXT_YptBlock:
                TXSJTBlock = new TXSJTBlock_t(xdr);
                break;
            case TransactionType_t.TXT_YptSVTInit:
                TXYptInit = new TXSVTInit_t(xdr);
                break;
            case TransactionType_t.TXT_YptAddValue:
                TXYptAddValue = new TXSVTSaleDeposit_t(xdr);
                break;
            case TransactionType_t.TXT_YptSVTSale:
                TXSvtSale = new TXSVTSaleDeposit_t(xdr);
                break;
            case TransactionType_t.TXT_YptDEVSale:
                TXDevSale = new TXSVTSaleDeposit_t(xdr);
                break;
            case TransactionType_t.TXT_YktEntry:
                TXYKTEntry = new TXYKTEntryExit_t(xdr);
                break;
            case TransactionType_t.TXT_YktExit:
                TXYKTExit = new TXYKTEntryExit_t(xdr);
                break;
//        case TXT_YktChaneEntry:
//            TXYKTChangeEntry = new TXYKTChangeEntryExit_t(xdr);
//            break;
            case TransactionType_t.TXT_YktChangeExit:
                TXYKTChangeExit = new TXYKTChangeEntryExit_t(xdr);
                break;
            case TransactionType_t.TXT_YktUpdate:
                TXYKTUpdate = new TXYKTUpdate_t(xdr);
                break;
            case TransactionType_t.TXT_YktSale:
                TXYKTSale = new TXYKTSaleDeposit_t(xdr);
                break;
            case TransactionType_t.TXT_YktAddValue:
                TXYKTAddValue = new TXYKTSaleDeposit_t(xdr);
                break;
            case TransactionType_t.TXT_YktBlock:
                TXYKTBlock = new TXYKTAdmin_t(xdr);
                break;
            case TransactionType_t.TXT_ICEntry:
                TXICEntry = new TXICEntryExit_t(xdr);
                break;
            case TransactionType_t.TXT_ICExit:
                TXICExit = new TXICEntryExit_t(xdr);
                break;
            case TransactionType_t.TXT_ICUpdate:
                TXICUpdate = new TXICUpdate_t(xdr);
                break;
            case TransactionType_t.TXT_SVTCPUInit:
                TXSVTCPUInit = new TXSVTCPUInit_t(xdr);
                break;
            case TransactionType_t.TXT_SVTCPUAddValue:
                TXSVTCPUAddValue = new TXSVTCPUSaleDeposit_t(xdr);
                break;
            case TransactionType_t.TXT_SVTCPUSale:
                TXSVTCPUSale = new TXSVTCPUSaleDeposit_t(xdr);
                break;
            case TransactionType_t.TXT_SVTCPUEntry:
                TXSVTCPUEntry = new TXSVTCPUEntryExit_t(xdr);
                break;
            case TransactionType_t.TXT_SVTCPUExit:
                TXSVTCPUExit = new TXSVTCPUEntryExit_t(xdr);
                break;
//        case TXT_SVTChangeCPUEntry:
//            TXSVTChangeCPUEntry = new TXSVTCPUChangeEntryExit_t(xdr);
//            break;
//        case TXT_SVTChangeCPUExit:
//            TXSVTChangeCPUExit = new TXSVTCPUChangeEntryExit_t(xdr);
//            break;
            case TransactionType_t.TXT_SVTCPUUpdate:
                TXSVTCPUUpdate = new TXSVTCPUUpdate_t(xdr);
                break;
            case TransactionType_t.TXT_SVTCPUBlock:
                TXSVTCPUBlock = new TXSVTCPUAdmin_t(xdr);
                break;
            case TransactionType_t.TXT_SVTCPUUnlock:
                TXSVTCPUUnlock = new TXSVTCPUAdmin_t(xdr);
                break;
            case TransactionType_t.TXT_SVTCPUImmediateRefund:
                TXSVTCPUImRefund = new TXSVTCPUImmediateRefund_t(xdr);
                break;
            case TransactionType_t.TXT_SVTCPUNonImmediateRefund:
                TXSVTCPUNonImRefund = new TXSVTCPUNonImmediateRefund_t(xdr);
                break;
            case TransactionType_t.TXT_SVTCPUCheck:
                TXSVTCPUCheck = new TXSVTCPUCheck_t(xdr);
                break;
            case TransactionType_t.TXT_JTBEntry:
                TXJTBEntry = new TXJTBEntryExit_t(xdr);
                break;
            case TransactionType_t.TXT_JTBExit:
                TXJTBExit = new TXJTBEntryExit_t(xdr);
                break;
            case TransactionType_t.TXT_JTBChangeEntry:
                TXJTBChangeEntry = new TXJTBChangeEntryExit_t(xdr);
                break;
            case TransactionType_t.TXT_JTBChangeExit:
                TXJTBChangeExit = new TXJTBChangeEntryExit_t(xdr);
                break;
            case TransactionType_t.TXT_JTBUpdate:
                TXJTBUpdate = new TXJTBUpdate_t(xdr);
                break;
            case TransactionType_t.TXT_JTBAddValue:
                TXJTBAddValue = new TXJTBSaleDeposit_t(xdr);
                break;
            case TransactionType_t.TXT_JTBSale:
                TXJTBSale = new TXJTBSaleDeposit_t(xdr);
                break;
            case TransactionType_t.TXT_JTBBlock:
                TXJTBBlock = new TXJTBAdmin_t(xdr);
                break;
            case TransactionType_t.TXT_GJICEntry:
                TXGJICEntry = new TXGJICEntryExit_t(xdr);
                break;
            case TransactionType_t.TXT_GJICExit:
                TXGJICExit = new TXGJICEntryExit_t(xdr);
                break;
            case TransactionType_t.TXT_GJICAddValue:
                TXGJICAddValue = new TXGJICSaleDeposit_t(xdr);
                break;
            case TransactionType_t.TXT_GJICUpdate:
                TXGJICUpdate = new TXGJICUpdate_t(xdr);
                break;
            case TransactionType_t.TXT_GJICBlock:
                TXGJICBlock = new TXGJICAdmin_t(xdr);
                break;
            case TransactionType_t.TXT_YktCheck:
                YKTCheck = new TXYKTAdmin_t(xdr);
                break;
            case TransactionType_t.TXT_QpayEntry:
                TXQpayEntry = new TXQpayEntryExit_t(xdr);
                break;
            case TransactionType_t.TXT_QpayExit:
                TXQpayExit = new TXQpayEntryExit_t(xdr);
                break;
            case TransactionType_t.TXT_QpayUpdate:
                TXQpayUpdate = new TXQpayUpdate_t(xdr);
                break;
            case TransactionType_t.TXT_QpayRefund:
                TXQpayRefund = new TXQpayRefund_t(xdr);
                break;
            case TransactionType_t.TXT_QrcodeEntry:
                TXQrcodeEntry = new TXQrcodeEntryExit_t(xdr);
                break;
            case TransactionType_t.TXT_QrcodeExit:
                TXQrcodeExit = new TXQrcodeEntryExit_t(xdr);
                break;
            case TransactionType_t.TXT_QrcodeUpdate:
                TXQrcodeUpdate = new TXQrcodeUpdate_t(xdr);
                break;
            case TransactionType_t.TXT_QrcodeRefund:
                TXQrcodeRefund = new TXQrcodeRefund_t(xdr);
                break;
            case TransactionType_t.TXT_FaceEntry:
                TXFaceEntry = new TXFaceEntryExit_t(xdr);
                break;
            case TransactionType_t.TXT_FaceExit:
                TXFaceExit = new TXFaceEntryExit_t(xdr);
                break;
            case TransactionType_t.TXT_FaceUpdate:
                TXFaceUpdate = new TXFaceUpdate_t(xdr);
                break;
            case TransactionType_t.TXT_FaceRefund:
                TXFaceRefund = new TXFaceRefund_t(xdr);
                break;
            case TransactionType_t.TXT_JTBCheck:
                TXJTBCheck = new TXJTBAdmin_t(xdr);
                break;
        }
    }

}
// End of SLEUD_t.java
