package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class SLEUDMSG_t implements XdrAble {
    public SLEUD_t UDData;
    public SN_t UDSN;
    public UDComm_t UDComm;
    public TAC_t TAC;

    public SLEUDMSG_t() {
    }

    public SLEUDMSG_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        UDData.xdrEncode(xdr);
        UDSN.xdrEncode(xdr);
        UDComm.xdrEncode(xdr);
        TAC.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        UDData = new SLEUD_t(xdr);
        UDSN = new SN_t(xdr);
        UDComm = new UDComm_t(xdr);
        TAC = new TAC_t(xdr);
    }

}
// End of SLEUDMSG_t.java
