package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class SPTFtpAuditBodyData_t implements XdrAble {
    public Date2_t settleDate;
    public DeviceID_t settleObject;
    public FtpAuditFile_t [] fileAuditList;

    public SPTFtpAuditBodyData_t() {
    }

    public SPTFtpAuditBodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        settleDate.xdrEncode(xdr);
        settleObject.xdrEncode(xdr);
        { int $size = fileAuditList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { fileAuditList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        settleDate = new Date2_t(xdr);
        settleObject = new DeviceID_t(xdr);
        { int $size = xdr.xdrDecodeInt(); fileAuditList = new FtpAuditFile_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { fileAuditList[$idx] = new FtpAuditFile_t(xdr); } }
    }

}
// End of SPTFtpAuditBodyData_t.java
