package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class SPTTxSettleBodyData_t implements XdrAble {
    public Date2_t settleDate;
    public U32_t totalTxCount;
    public U32_t correctTxCount;
    public U32_t correctTxValue;
    public U32_t doubtTxCount;
    public U32_t doubtTxValue;
    public U8_t OuditFlag;
    public settledFile_t [] settledFileList;
    public ErrorFile_t [] errorFileList;

    public SPTTxSettleBodyData_t() {
    }

    public SPTTxSettleBodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        settleDate.xdrEncode(xdr);
        totalTxCount.xdrEncode(xdr);
        correctTxCount.xdrEncode(xdr);
        correctTxValue.xdrEncode(xdr);
        doubtTxCount.xdrEncode(xdr);
        doubtTxValue.xdrEncode(xdr);
        OuditFlag.xdrEncode(xdr);
        { int $size = settledFileList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { settledFileList[$idx].xdrEncode(xdr); } }
        { int $size = errorFileList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { errorFileList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        settleDate = new Date2_t(xdr);
        totalTxCount = new U32_t(xdr);
        correctTxCount = new U32_t(xdr);
        correctTxValue = new U32_t(xdr);
        doubtTxCount = new U32_t(xdr);
        doubtTxValue = new U32_t(xdr);
        OuditFlag = new U8_t(xdr);
        { int $size = xdr.xdrDecodeInt(); settledFileList = new settledFile_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { settledFileList[$idx] = new settledFile_t(xdr); } }
        { int $size = xdr.xdrDecodeInt(); errorFileList = new ErrorFile_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { errorFileList[$idx] = new ErrorFile_t(xdr); } }
    }

}
// End of SPTTxSettleBodyData_t.java
