package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class StationInfo_t implements XdrAble {
    public StationID_t stationCode;
    public UnicodeString_t stationCnName;
    public String stationEnName;
    public LineID_t belongs;
    public U8_t useFlag;

    public StationInfo_t() {
    }

    public StationInfo_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        stationCode.xdrEncode(xdr);
        stationCnName.xdrEncode(xdr);
        xdr.xdrEncodeString(stationEnName);
        belongs.xdrEncode(xdr);
        useFlag.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        stationCode = new StationID_t(xdr);
        stationCnName = new UnicodeString_t(xdr);
        stationEnName = xdr.xdrDecodeString();
        belongs = new LineID_t(xdr);
        useFlag = new U8_t(xdr);
    }

}
// End of StationInfo_t.java
