package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class StationLayout_t implements XdrAble {
    public StationID_t stationId;
    public String stationMapFilename;
    public LayoutDevice_t [] deviceList;

    public StationLayout_t() {
    }

    public StationLayout_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        stationId.xdrEncode(xdr);
        xdr.xdrEncodeString(stationMapFilename);
        { int $size = deviceList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { deviceList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        stationId = new StationID_t(xdr);
        stationMapFilename = xdr.xdrDecodeString();
        { int $size = xdr.xdrDecodeInt(); deviceList = new LayoutDevice_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { deviceList[$idx] = new LayoutDevice_t(xdr); } }
    }

}
// End of StationLayout_t.java
