package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class StationTrainSchedule_t implements XdrAble {
    public StationID_t stationId;
    public U8_t direction;
    public U8_t startEndFlag;
    public SecondsSinceMidNight_t trainTime;

    public StationTrainSchedule_t() {
    }

    public StationTrainSchedule_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        stationId.xdrEncode(xdr);
        direction.xdrEncode(xdr);
        startEndFlag.xdrEncode(xdr);
        trainTime.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        stationId = new StationID_t(xdr);
        direction = new U8_t(xdr);
        startEndFlag = new U8_t(xdr);
        trainTime = new SecondsSinceMidNight_t(xdr);
    }

}
// End of StationTrainSchedule_t.java
