package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class StockStatBodyData_t implements XdrAble {
    public Date2_t statDate;
    public TicketStockStat_t[] stockStatList;

    public StockStatBodyData_t() {
    }

    public StockStatBodyData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        statDate.xdrEncode(xdr);
        { int $size = stockStatList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { stockStatList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        statDate = new Date2_t(xdr);
        { int $size = xdr.xdrDecodeInt(); stockStatList = new TicketStockStat_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { stockStatList[$idx] = new TicketStockStat_t(xdr); } }
    }

}
// End of StockStatBodyData_t.java
