package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class SVTCPUAllBlackList_t implements XdrAble {
    public TicketLogID_t TicketLogicalID;
    public U8_t processFlag;

    public SVTCPUAllBlackList_t() {
    }

    public SVTCPUAllBlackList_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        TicketLogicalID.xdrEncode(xdr);
        processFlag.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        TicketLogicalID = new TicketLogID_t(xdr);
        processFlag = new U8_t(xdr);
    }

}
// End of SVTCPUAllBlackList_t.java
