package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
/**
 * A collection of constants used by the "tianjinAFC1" ONC/RPC program.
 */
public interface tianjinAFC1 {
    public static final int CTJAFCEISVersion = 0x010200;
}
// End of tianjinAFC1.java
