package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TicketReaderData_t implements XdrAble {
    public U16_t maxTicketErrorCount;
    public U16_t waitTimeForWriteOk;
    public U16_t retryForWriteOk;

    public TicketReaderData_t() {
    }

    public TicketReaderData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        maxTicketErrorCount.xdrEncode(xdr);
        waitTimeForWriteOk.xdrEncode(xdr);
        retryForWriteOk.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        maxTicketErrorCount = new U16_t(xdr);
        waitTimeForWriteOk = new U16_t(xdr);
        retryForWriteOk = new U16_t(xdr);
    }

}
// End of TicketReaderData_t.java
