package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
/**
 * Enumeration (collection of constants).
 */
public interface TicketFamily_t {

    public static final int TicketFamily_SJTToken = 0;
    public static final int TicketFamily_SJTCard = 1;
    public static final int TicketFamily_SJZQ = 2;
    public static final int TicketFamily_YKTM1 = 3;
    public static final int TicketFamily_YKTCPU = 4;
    public static final int TicketFamily_SVTM1 = 5;
    public static final int TicketFamily_QGRsvd = 6;
    public static final int TicketFamily_SVTCPU = 7;
    public static final int TicketFamily_IC = 8;
    public static final int TicketFamily_JTB = 9;
    public static final int TicketFamily_GJIC = 10;
    public static final int TicketFamily_SVTJC = 11;
    public static final int TicketFamily_SVTJS = 12;
    public static final int TicketFamily_UNI = 13;
    public static final int TicketFamily_QRCODE = 14;
    public static final int TicketFamily_FACE = 15;

}
// End of TicketFamily_t.java
