package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TicketBoxData_t implements XdrAble {
    public U16_t countUptoEmptyOfTicketBox;
    public U16_t countEmptiedOfTicketBox;
    public U16_t countUptoFullOfTicketBox;
    public U16_t countFulledOfTicketBox;
    public U16_t countUptoFullOfInvalidBox;
    public U16_t countFulledOfInvalidBox;

    public TicketBoxData_t() {
    }

    public TicketBoxData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        countUptoEmptyOfTicketBox.xdrEncode(xdr);
        countEmptiedOfTicketBox.xdrEncode(xdr);
        countUptoFullOfTicketBox.xdrEncode(xdr);
        countFulledOfTicketBox.xdrEncode(xdr);
        countUptoFullOfInvalidBox.xdrEncode(xdr);
        countFulledOfInvalidBox.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        countUptoEmptyOfTicketBox = new U16_t(xdr);
        countEmptiedOfTicketBox = new U16_t(xdr);
        countUptoFullOfTicketBox = new U16_t(xdr);
        countFulledOfTicketBox = new U16_t(xdr);
        countUptoFullOfInvalidBox = new U16_t(xdr);
        countFulledOfInvalidBox = new U16_t(xdr);
    }

}
// End of TicketBoxData_t.java
