package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TicketStockStat_t implements XdrAble {
    public StationID_t statId;
    public U16_t stockIndex;
    public U32_t ticketCount;
    public U32_t invalidTicketCount;

    public TicketStockStat_t() {
    }

    public TicketStockStat_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        statId.xdrEncode(xdr);
        stockIndex.xdrEncode(xdr);
        ticketCount.xdrEncode(xdr);
        invalidTicketCount.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        statId = new StationID_t(xdr);
        stockIndex = new U16_t(xdr);
        ticketCount = new U32_t(xdr);
        invalidTicketCount = new U32_t(xdr);
    }

}
// End of TicketStockStat_t.java
