package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TransactionQueryData_t implements XdrAble {
    public U8_t countLimitOfTnxQuery;
    public U8_t intervalLimitOfTnxQuery;

    public TransactionQueryData_t() {
    }

    public TransactionQueryData_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        countLimitOfTnxQuery.xdrEncode(xdr);
        intervalLimitOfTnxQuery.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        countLimitOfTnxQuery = new U8_t(xdr);
        intervalLimitOfTnxQuery = new U8_t(xdr);
    }

}
// End of TransactionQueryData_t.java
