package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
/**
 * Enumeration (collection of constants).
 */
public interface TransactionType_t {

    public static final int TXT_YptInit = 0x00;
    public static final int TXT_YptSale = 0x01;
    public static final int TXT_YptAddValue = 0x02;
    public static final int TXT_YptEntry = 0x03;
    public static final int TXT_YptExit = 0x04;
    public static final int TXT_YptUpdate = 0x05;
    public static final int TXT_YptRefund = 0x06;
    public static final int TXT_YptBlock = 0x07;
    public static final int TXT_YptSVTInit = 0x08;
    public static final int TXT_YptSVTSale = 0x09;
    public static final int TXT_SVTCPUSale = 0x0B;
    public static final int TXT_SVTCPUInit = 0x0C;
    public static final int TXT_SVTCPUAddValue = 0x0D;
    public static final int TXT_SVTCPUEntry = 0x0E;
    public static final int TXT_SVTCPUExit = 0x0F;
    public static final int TXT_SVTCPUUpdate = 0x10;
    public static final int TXT_SVTCPUBlock = 0x11;
    public static final int TXT_SVTCPUUnlock = 0x12;
    public static final int TXT_SVTCPUCheck = 0x13;
    public static final int TXT_SVTCPUImmediateRefund = 0x14;
    public static final int TXT_SVTCPUNonImmediateRefund = 0x15;
    public static final int TXT_QpayEntry = 0x16;
    public static final int TXT_QpayExit = 0x17;
    public static final int TXT_QpayUpdate = 0x18;
    public static final int TXT_QpayRefund = 0x19;
    public static final int TXT_QrcodeEntry = 0x1A;
    public static final int TXT_QrcodeExit = 0x1B;
    public static final int TXT_QrcodeUpdate = 0x1C;
    public static final int TXT_QrcodeRefund = 0x1D;
    public static final int TXT_YktSale = 0x81;
    public static final int TXT_YktAddValue = 0x82;
    public static final int TXT_YktEntry = 0x83;
    public static final int TXT_YktExit = 0x84;
    public static final int TXT_YktUpdate = 0x85;
    public static final int TXT_YktBlock = 0x87;
    public static final int TXT_ICEntry = 0x90;
    public static final int TXT_ICExit = 0x91;
    public static final int TXT_ICUpdate = 0x92;
    public static final int TXT_JTBEntry = 0x93;
    public static final int TXT_JTBExit = 0x94;
    public static final int TXT_JTBUpdate = 0x95;
    public static final int TXT_JTBBlock = 0x96;
    public static final int TXT_JTBAddValue = 0x97;
    public static final int TXT_GJICEntry = 0x98;
    public static final int TXT_GJICExit = 0x99;
    public static final int TXT_GJICUpdate = 0xA0;
    public static final int TXT_GJICBlock = 0xA1;
    public static final int TXT_GJICAddValue = 0xA2;
    public static final int TXT_YktCheck = 0x88;
    public static final int TXT_JTBSale = 0xA3;
    public static final int TXT_YptDEVSale = 0x1E;
    public static final int TXT_YptChangeEntry = 0x31;
    public static final int TXT_YptChangeExit = 0x32;
    public static final int TXT_YktChangeEntry = 0x89;
    public static final int TXT_YktChangeExit = 0x8A;
    public static final int TXT_SVTCPUChangeEntry = 0x33;
    public static final int TXT_SVTCPUChangeExit = 0x34;
    public static final int TXT_JTBChangeEntry = 0xA4;
    public static final int TXT_JTBChangeExit = 0xA5;
    public static final int TXT_FaceEntry = 0x35;
    public static final int TXT_FaceExit = 0x36;
    public static final int TXT_FaceUpdate = 0x37;
    public static final int TXT_FaceRefund = 0x38;
    public static final int TXT_JTBCheck = 0xA6;

}
// End of TransactionType_t.java
