package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TVMAR_t implements XdrAble {
    public U32_t[] ARItem;

    public TVMAR_t() {
    }

    public TVMAR_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        { int $size = 32; for ( int $idx = 0; $idx < $size; ++$idx ) { ARItem[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        { int $size = 32; ARItem = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { ARItem[$idx] = new U32_t(xdr); } }
    }

}
// End of TVMAR_t.java
