package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TVMFareAreaNew_t implements XdrAble {
    public U16_t areaNumber;
    public U16_t lineId;
    public U16_t useFlag;
    public U16_t fareAreaId;
    public java.lang.String cnFareImageFileName;
    public java.lang.String enFareImageFileName;
    public U16_t fareXPos;
    public U16_t fareYPos;
    public U16_t fareWidht;
    public U16_t fareHeight;
    public java.lang.String zoomCnFareImageFileName;
    public java.lang.String zoomEnFareImageFileName;
    public U16_t zoomFareXPos;
    public U16_t zoomFareYPos;
    public U16_t zoomFareWidth;
    public U16_t zoomFareHeight;

    public TVMFareAreaNew_t() {
    }

    public TVMFareAreaNew_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        areaNumber.xdrEncode(xdr);
        lineId.xdrEncode(xdr);
        useFlag.xdrEncode(xdr);
        fareAreaId.xdrEncode(xdr);
        xdr.xdrEncodeString(cnFareImageFileName);
        xdr.xdrEncodeString(enFareImageFileName);
        fareXPos.xdrEncode(xdr);
        fareYPos.xdrEncode(xdr);
        fareWidht.xdrEncode(xdr);
        fareHeight.xdrEncode(xdr);
        xdr.xdrEncodeString(zoomCnFareImageFileName);
        xdr.xdrEncodeString(zoomEnFareImageFileName);
        zoomFareXPos.xdrEncode(xdr);
        zoomFareYPos.xdrEncode(xdr);
        zoomFareWidth.xdrEncode(xdr);
        zoomFareHeight.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        areaNumber = new U16_t(xdr);
        lineId = new U16_t(xdr);
        useFlag = new U16_t(xdr);
        fareAreaId = new U16_t(xdr);
        cnFareImageFileName = xdr.xdrDecodeString();
        enFareImageFileName = xdr.xdrDecodeString();
        fareXPos = new U16_t(xdr);
        fareYPos = new U16_t(xdr);
        fareWidht = new U16_t(xdr);
        fareHeight = new U16_t(xdr);
        zoomCnFareImageFileName = xdr.xdrDecodeString();
        zoomEnFareImageFileName = xdr.xdrDecodeString();
        zoomFareXPos = new U16_t(xdr);
        zoomFareYPos = new U16_t(xdr);
        zoomFareWidth = new U16_t(xdr);
        zoomFareHeight = new U16_t(xdr);
    }

}
// End of TVMFareAreaNew_t.java
