package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TVMFareValueSelection_t implements XdrAble {
    public U16_t buttonId;
    public U16_t buttonValue;
    public U16_t fareTier;
    public U16_t xPos;
    public U16_t yPos;
    public U16_t width;
    public U16_t height;

    public TVMFareValueSelection_t() {
    }

    public TVMFareValueSelection_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        buttonId.xdrEncode(xdr);
        buttonValue.xdrEncode(xdr);
        fareTier.xdrEncode(xdr);
        xPos.xdrEncode(xdr);
        yPos.xdrEncode(xdr);
        width.xdrEncode(xdr);
        height.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        buttonId = new U16_t(xdr);
        buttonValue = new U16_t(xdr);
        fareTier = new U16_t(xdr);
        xPos = new U16_t(xdr);
        yPos = new U16_t(xdr);
        width = new U16_t(xdr);
        height = new U16_t(xdr);
    }

}
// End of TVMFareValueSelection_t.java
