package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TVMFareArea_t implements XdrAble {
    public U16_t areaId;
    public U16_t xPos;
    public U16_t yPos;
    public U16_t widht;
    public U16_t height;
    public U16_t useFlag;
    public java.lang.String zoomCnImageFileName;
    public java.lang.String zoomEnImageFileName;
    public U16_t zoomXPos;
    public U16_t zoomYPos;
    public U16_t zoomWidth;
    public U16_t zoomHeight;

    public TVMFareArea_t() {
    }

    public TVMFareArea_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        areaId.xdrEncode(xdr);
        xPos.xdrEncode(xdr);
        yPos.xdrEncode(xdr);
        widht.xdrEncode(xdr);
        height.xdrEncode(xdr);
        useFlag.xdrEncode(xdr);
        xdr.xdrEncodeString(zoomCnImageFileName);
        xdr.xdrEncodeString(zoomEnImageFileName);
        zoomXPos.xdrEncode(xdr);
        zoomYPos.xdrEncode(xdr);
        zoomWidth.xdrEncode(xdr);
        zoomHeight.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        areaId = new U16_t(xdr);
        xPos = new U16_t(xdr);
        yPos = new U16_t(xdr);
        widht = new U16_t(xdr);
        height = new U16_t(xdr);
        useFlag = new U16_t(xdr);
        zoomCnImageFileName = xdr.xdrDecodeString();
        zoomEnImageFileName = xdr.xdrDecodeString();
        zoomXPos = new U16_t(xdr);
        zoomYPos = new U16_t(xdr);
        zoomWidth = new U16_t(xdr);
        zoomHeight = new U16_t(xdr);
    }

}
// End of TVMFareArea_t.java
