package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TVMLineSelectionNew_t implements XdrAble {
    public U16_t areaNumber;
    public U16_t newLineButtonId;
    public U16_t lineButtonXPos;
    public U16_t lineButtonYPos;
    public U16_t lineButtonWidth;
    public U16_t lineButtonHeight;
    public java.lang.String cnLineButtonImageFileName;
    public java.lang.String enLineButtonImageFileName;
    public U16_t useFlag;
    public ButtonView_t [] ButtonViewList;

    public TVMLineSelectionNew_t() {
    }

    public TVMLineSelectionNew_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        areaNumber.xdrEncode(xdr);
        newLineButtonId.xdrEncode(xdr);
        lineButtonXPos.xdrEncode(xdr);
        lineButtonYPos.xdrEncode(xdr);
        lineButtonWidth.xdrEncode(xdr);
        lineButtonHeight.xdrEncode(xdr);
        xdr.xdrEncodeString(cnLineButtonImageFileName);
        xdr.xdrEncodeString(enLineButtonImageFileName);
        useFlag.xdrEncode(xdr);
        { int $size = ButtonViewList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { ButtonViewList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        areaNumber = new U16_t(xdr);
        newLineButtonId = new U16_t(xdr);
        lineButtonXPos = new U16_t(xdr);
        lineButtonYPos = new U16_t(xdr);
        lineButtonWidth = new U16_t(xdr);
        lineButtonHeight = new U16_t(xdr);
        cnLineButtonImageFileName = xdr.xdrDecodeString();
        enLineButtonImageFileName = xdr.xdrDecodeString();
        useFlag = new U16_t(xdr);
        { int $size = xdr.xdrDecodeInt(); ButtonViewList = new ButtonView_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { ButtonViewList[$idx] = new ButtonView_t(xdr); } }
    }

}
// End of TVMLineSelectionNew_t.java
