package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TVMLineSelection_t implements XdrAble {
    public U16_t lineButtonId;
    public U16_t buttonXPos;
    public U16_t buttonYPos;
    public U16_t buttonWidth;
    public U16_t buttonHeight;
    public U16_t useFlag;
    public java.lang.String cnImageFileName;
    public java.lang.String enImageFileName;
    public U16_t lineXPos;
    public U16_t lineYPos;
    public U16_t lineWidth;
    public U16_t lineHeight;

    public TVMLineSelection_t() {
    }

    public TVMLineSelection_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        lineButtonId.xdrEncode(xdr);
        buttonXPos.xdrEncode(xdr);
        buttonYPos.xdrEncode(xdr);
        buttonWidth.xdrEncode(xdr);
        buttonHeight.xdrEncode(xdr);
        useFlag.xdrEncode(xdr);
        xdr.xdrEncodeString(cnImageFileName);
        xdr.xdrEncodeString(enImageFileName);
        lineXPos.xdrEncode(xdr);
        lineYPos.xdrEncode(xdr);
        lineWidth.xdrEncode(xdr);
        lineHeight.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        lineButtonId = new U16_t(xdr);
        buttonXPos = new U16_t(xdr);
        buttonYPos = new U16_t(xdr);
        buttonWidth = new U16_t(xdr);
        buttonHeight = new U16_t(xdr);
        useFlag = new U16_t(xdr);
        cnImageFileName = xdr.xdrDecodeString();
        enImageFileName = xdr.xdrDecodeString();
        lineXPos = new U16_t(xdr);
        lineYPos = new U16_t(xdr);
        lineWidth = new U16_t(xdr);
        lineHeight = new U16_t(xdr);
    }

}
// End of TVMLineSelection_t.java
