package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TVMLastTrainNew_t implements XdrAble {
    public StationID_t originStationId;
    public StationID_t destStationId;
    public SecondsSinceMidNight_t lastTrainTime;

    public TVMLastTrainNew_t() {
    }

    public TVMLastTrainNew_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        originStationId.xdrEncode(xdr);
        destStationId.xdrEncode(xdr);
        lastTrainTime.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        originStationId = new StationID_t(xdr);
        destStationId = new StationID_t(xdr);
        lastTrainTime = new SecondsSinceMidNight_t(xdr);
    }

}
// End of TVMLastTrainNew_t.java
