package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TVMPersonalization_t implements XdrAble {
    public LineID_t lineCode;
    public U8_t personalizedFileNumber;
    public U8_t personalizedFileType;
    public U8_t personalizedFileFlag;
    public java.lang.String personalizedFileName;
    public U32_t[] Rsvd;

    public TVMPersonalization_t() {
    }

    public TVMPersonalization_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        lineCode.xdrEncode(xdr);
        personalizedFileNumber.xdrEncode(xdr);
        personalizedFileType.xdrEncode(xdr);
        personalizedFileFlag.xdrEncode(xdr);
        xdr.xdrEncodeString(personalizedFileName);
        { int $size = 32; for ( int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        lineCode = new LineID_t(xdr);
        personalizedFileNumber = new U8_t(xdr);
        personalizedFileType = new U8_t(xdr);
        personalizedFileFlag = new U8_t(xdr);
        personalizedFileName = xdr.xdrDecodeString();
        { int $size = 32; Rsvd = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx] = new U32_t(xdr); } }
    }

}
// End of TVMPersonalization_t.java
