package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TVMStationInLineNew_t implements XdrAble {
    public U16_t areaNumber;
    public U16_t newLineButtonId;
    public U16_t stationInLineButtonId;
    public U16_t stationInLineXPos;
    public U16_t stationInLineYPos;
    public U16_t stationInLineWidth;
    public U16_t stationInLineHeight;
    public U8_t useFlag;

    public TVMStationInLineNew_t() {
    }

    public TVMStationInLineNew_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        areaNumber.xdrEncode(xdr);
        newLineButtonId.xdrEncode(xdr);
        stationInLineButtonId.xdrEncode(xdr);
        stationInLineXPos.xdrEncode(xdr);
        stationInLineYPos.xdrEncode(xdr);
        stationInLineWidth.xdrEncode(xdr);
        stationInLineHeight.xdrEncode(xdr);
        useFlag.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        areaNumber = new U16_t(xdr);
        newLineButtonId = new U16_t(xdr);
        stationInLineButtonId = new U16_t(xdr);
        stationInLineXPos = new U16_t(xdr);
        stationInLineYPos = new U16_t(xdr);
        stationInLineWidth = new U16_t(xdr);
        stationInLineHeight = new U16_t(xdr);
        useFlag = new U8_t(xdr);
    }

}
// End of TVMStationInLineNew_t.java
