package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TVMStationInAreaNew_t implements XdrAble {
    public U16_t areaNumber;
    public U8_t stationInAreaUserFlag;
    public U16_t fareAreaId;
    public U16_t stationInAreaId;
    public U16_t stationInAreaXPos;
    public U16_t stationInAreaYPos;
    public U16_t stationInAreaWidth;
    public U16_t stationInAreaHeight;

    public TVMStationInAreaNew_t() {
    }

    public TVMStationInAreaNew_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        areaNumber.xdrEncode(xdr);
        stationInAreaUserFlag.xdrEncode(xdr);
        fareAreaId.xdrEncode(xdr);
        stationInAreaId.xdrEncode(xdr);
        stationInAreaXPos.xdrEncode(xdr);
        stationInAreaYPos.xdrEncode(xdr);
        stationInAreaWidth.xdrEncode(xdr);
        stationInAreaHeight.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        areaNumber = new U16_t(xdr);
        stationInAreaUserFlag = new U8_t(xdr);
        fareAreaId = new U16_t(xdr);
        stationInAreaId = new U16_t(xdr);
        stationInAreaXPos = new U16_t(xdr);
        stationInAreaYPos = new U16_t(xdr);
        stationInAreaWidth = new U16_t(xdr);
        stationInAreaHeight = new U16_t(xdr);
    }

}
// End of TVMStationInAreaNew_t.java
