package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TVMStationInLine_t implements XdrAble {
    public U16_t stationButtonId;
    public U16_t lineButtonId;
    public U16_t xPos;
    public U16_t yPos;
    public U16_t width;
    public U16_t height;
    public U8_t useFlag;

    public TVMStationInLine_t() {
    }

    public TVMStationInLine_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        stationButtonId.xdrEncode(xdr);
        lineButtonId.xdrEncode(xdr);
        xPos.xdrEncode(xdr);
        yPos.xdrEncode(xdr);
        width.xdrEncode(xdr);
        height.xdrEncode(xdr);
        useFlag.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        stationButtonId = new U16_t(xdr);
        lineButtonId = new U16_t(xdr);
        xPos = new U16_t(xdr);
        yPos = new U16_t(xdr);
        width = new U16_t(xdr);
        height = new U16_t(xdr);
        useFlag = new U8_t(xdr);
    }

}
// End of TVMStationInLine_t.java
