package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TVMTopBanner_t implements XdrAble {
    public U16_t bannerId;
    public java.lang.String cnImageFileName;
    public java.lang.String enImageFileName;

    public TVMTopBanner_t() {
    }

    public TVMTopBanner_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        bannerId.xdrEncode(xdr);
        xdr.xdrEncodeString(cnImageFileName);
        xdr.xdrEncodeString(enImageFileName);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        bannerId = new U16_t(xdr);
        cnImageFileName = xdr.xdrDecodeString();
        enImageFileName = xdr.xdrDecodeString();
    }

}
// End of TVMTopBanner_t.java
