package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TVMValueSelectionNew_t implements XdrAble {
    public U16_t areaNumber;
    public U16_t selectButtonId;
    public U16_t selectButtonType;
    public java.lang.String cnSelectButtonIdFileName;
    public java.lang.String enSelectButtonIdFileName;
    public U16_t buttonValueOrNumber;
    public U16_t buttonXPos;
    public U16_t buttonYPos;
    public U16_t buttonWidth;
    public U16_t buttonHeight;
    public U8_t useFlag;
    public ButtonView_t [] ButtonViewList;

    public TVMValueSelectionNew_t() {
    }

    public TVMValueSelectionNew_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        areaNumber.xdrEncode(xdr);
        selectButtonId.xdrEncode(xdr);
        selectButtonType.xdrEncode(xdr);
        xdr.xdrEncodeString(cnSelectButtonIdFileName);
        xdr.xdrEncodeString(enSelectButtonIdFileName);
        buttonValueOrNumber.xdrEncode(xdr);
        buttonXPos.xdrEncode(xdr);
        buttonYPos.xdrEncode(xdr);
        buttonWidth.xdrEncode(xdr);
        buttonHeight.xdrEncode(xdr);
        useFlag.xdrEncode(xdr);
        { int $size = ButtonViewList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { ButtonViewList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        areaNumber = new U16_t(xdr);
        selectButtonId = new U16_t(xdr);
        selectButtonType = new U16_t(xdr);
        cnSelectButtonIdFileName = xdr.xdrDecodeString();
        enSelectButtonIdFileName = xdr.xdrDecodeString();
        buttonValueOrNumber = new U16_t(xdr);
        buttonXPos = new U16_t(xdr);
        buttonYPos = new U16_t(xdr);
        buttonWidth = new U16_t(xdr);
        buttonHeight = new U16_t(xdr);
        useFlag = new U8_t(xdr);
        { int $size = xdr.xdrDecodeInt(); ButtonViewList = new ButtonView_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { ButtonViewList[$idx] = new ButtonView_t(xdr); } }
    }

}
// End of TVMValueSelectionNew_t.java
