package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TXGJICSaleDeposit_t implements XdrAble {
    public OtherTicketComm_t OtherTicketComm;
    public Date2_t CardDate;
    public Date2_t StartUseDate;
    public ValueCent_t transactionValue;
    public U32_t AfterTxn;
    public ValueCent_t forgiveValue;
    public OperatorID_t operatorID;
    public BOMShiftID_t bomShiftID;
    public PaymentMeans_t PaymentMeans;
    public U32_t[] Rsvd;

    public TXGJICSaleDeposit_t() {
    }

    public TXGJICSaleDeposit_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        OtherTicketComm.xdrEncode(xdr);
        CardDate.xdrEncode(xdr);
        StartUseDate.xdrEncode(xdr);
        transactionValue.xdrEncode(xdr);
        AfterTxn.xdrEncode(xdr);
        forgiveValue.xdrEncode(xdr);
        operatorID.xdrEncode(xdr);
        bomShiftID.xdrEncode(xdr);
        PaymentMeans.xdrEncode(xdr);
        { int $size = 4; for ( int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        OtherTicketComm = new OtherTicketComm_t(xdr);
        CardDate = new Date2_t(xdr);
        StartUseDate = new Date2_t(xdr);
        transactionValue = new ValueCent_t(xdr);
        AfterTxn = new U32_t(xdr);
        forgiveValue = new ValueCent_t(xdr);
        operatorID = new OperatorID_t(xdr);
        bomShiftID = new BOMShiftID_t(xdr);
        PaymentMeans = new PaymentMeans_t(xdr);
        { int $size = 4; Rsvd = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx] = new U32_t(xdr); } }
    }

}
// End of TXGJICSaleDeposit_t.java
