package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TXICEntryExit_t implements XdrAble {
    public OtherTicketComm_t OtherTicketComm;
    public U8_t entryExitBit;
    public StationID_t entryStationID;
    public DeviceID_t entryDeviceID;
    public AFCTime_t entryDateTime;
    public ValueCent_t transactionValue;
    public ValueCent_t balanceValue;
    public U32_t[] Rsvd;
    public java.lang.String SpecilDate;

    public TXICEntryExit_t() {
    }

    public TXICEntryExit_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        OtherTicketComm.xdrEncode(xdr);
        entryExitBit.xdrEncode(xdr);
        entryStationID.xdrEncode(xdr);
        entryDeviceID.xdrEncode(xdr);
        entryDateTime.xdrEncode(xdr);
        transactionValue.xdrEncode(xdr);
        balanceValue.xdrEncode(xdr);
        { int $size = 4; for ( int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx].xdrEncode(xdr); } }
        xdr.xdrEncodeString(SpecilDate);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        OtherTicketComm = new OtherTicketComm_t(xdr);
        entryExitBit = new U8_t(xdr);
        entryStationID = new StationID_t(xdr);
        entryDeviceID = new DeviceID_t(xdr);
        entryDateTime = new AFCTime_t(xdr);
        transactionValue = new ValueCent_t(xdr);
        balanceValue = new ValueCent_t(xdr);
        { int $size = 4; Rsvd = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx] = new U32_t(xdr); } }
        SpecilDate = xdr.xdrDecodeString();
    }

}
// End of TXICEntryExit_t.java
