package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TXICUpdate_t implements XdrAble {
    public OtherTicketComm_t OtherTicketComm;
    public U8_t updateType;
    public OperatorID_t operatorID;
    public BOMShiftID_t bomShiftID;
    public PaymentMeans_t paymentMeans;
    public ValueCent_t transactionValue;
    public ValueCent_t balanceValue;
    public U32_t[] Rsvd;
    public java.lang.String SpecilDate;

    public TXICUpdate_t() {
    }

    public TXICUpdate_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        OtherTicketComm.xdrEncode(xdr);
        updateType.xdrEncode(xdr);
        operatorID.xdrEncode(xdr);
        bomShiftID.xdrEncode(xdr);
        paymentMeans.xdrEncode(xdr);
        transactionValue.xdrEncode(xdr);
        balanceValue.xdrEncode(xdr);
        { int $size = 4; for ( int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx].xdrEncode(xdr); } }
        xdr.xdrEncodeString(SpecilDate);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        OtherTicketComm = new OtherTicketComm_t(xdr);
        updateType = new U8_t(xdr);
        operatorID = new OperatorID_t(xdr);
        bomShiftID = new BOMShiftID_t(xdr);
        paymentMeans = new PaymentMeans_t(xdr);
        transactionValue = new ValueCent_t(xdr);
        balanceValue = new ValueCent_t(xdr);
        { int $size = 4; Rsvd = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx] = new U32_t(xdr); } }
        SpecilDate = xdr.xdrDecodeString();
    }

}
// End of TXICUpdate_t.java
