package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TXJTBAdmin_t implements XdrAble {
    public OtherTicketComm_t OtherTicketComm;
    public UnicodeString_t TnxComment;
    public OperatorID_t operatorID;
    public BOMShiftID_t bomShiftID;
    public U32_t TransAccount;
    public U32_t TransactionValue;
    public PaymentMeans_t PaymentMeans;
    public U16_t YKTCityCode;
    public U8_t ConsumerKeyVersion;
    public U8_t ConsumerKeyIndex;
    public U32_t AfterTxn;
    public U32_t[] CardIdentificationCode;
    public U8_t AlgorithmIdentification;
    public U32_t OverLimit;
    public U32_t CardKind;
    public U32_t ChildCardKind;
    public U32_t BalBef;
    public U32_t[] Rsvd;

    public TXJTBAdmin_t() {
    }

    public TXJTBAdmin_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        OtherTicketComm.xdrEncode(xdr);
        TnxComment.xdrEncode(xdr);
        operatorID.xdrEncode(xdr);
        bomShiftID.xdrEncode(xdr);
        TransAccount.xdrEncode(xdr);
        TransactionValue.xdrEncode(xdr);
        PaymentMeans.xdrEncode(xdr);
        YKTCityCode.xdrEncode(xdr);
        ConsumerKeyVersion.xdrEncode(xdr);
        ConsumerKeyIndex.xdrEncode(xdr);
        AfterTxn.xdrEncode(xdr);
        { int $size = 2; for ( int $idx = 0; $idx < $size; ++$idx ) { CardIdentificationCode[$idx].xdrEncode(xdr); } }
        AlgorithmIdentification.xdrEncode(xdr);
        OverLimit.xdrEncode(xdr);
        CardKind.xdrEncode(xdr);
        ChildCardKind.xdrEncode(xdr);
        BalBef.xdrEncode(xdr);
        { int $size = 4; for ( int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        OtherTicketComm = new OtherTicketComm_t(xdr);
        TnxComment = new UnicodeString_t(xdr);
        operatorID = new OperatorID_t(xdr);
        bomShiftID = new BOMShiftID_t(xdr);
        TransAccount = new U32_t(xdr);
        TransactionValue = new U32_t(xdr);
        PaymentMeans = new PaymentMeans_t(xdr);
        YKTCityCode = new U16_t(xdr);
        ConsumerKeyVersion = new U8_t(xdr);
        ConsumerKeyIndex = new U8_t(xdr);
        AfterTxn = new U32_t(xdr);
        { int $size = 2; CardIdentificationCode = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { CardIdentificationCode[$idx] = new U32_t(xdr); } }
        AlgorithmIdentification = new U8_t(xdr);
        OverLimit = new U32_t(xdr);
        CardKind = new U32_t(xdr);
        ChildCardKind = new U32_t(xdr);
        BalBef = new U32_t(xdr);
        { int $size = 4; Rsvd = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx] = new U32_t(xdr); } }
    }

}
// End of TXJTBAdmin_t.java
