package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TXQpayUpdate_t implements XdrAble {
    public OtherTicketComm_t OtherTicketComm;
    public U8_t UpdateType;
    public OperatorID_t OperatorID;
    public BOMShiftID_t BOMShiftID;
    public U32_t TransAccount;
    public U32_t TransactionValue;
    public PaymentMeans_t PaymentMeans;
    public U32_t AfterTxn;
    public U32_t[] CardIdentificationCode;
    public U16_t BankID;
    public U8_t TransOrigin;
    public SN_t SPTSN;
    public SN_t BankSN;
    public Date2_t paySetday;
    public U8_t paytool;
    public U8_t paytype;
    public U32_t[] Rsvd;

    public TXQpayUpdate_t() {
    }

    public TXQpayUpdate_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        OtherTicketComm.xdrEncode(xdr);
        UpdateType.xdrEncode(xdr);
        OperatorID.xdrEncode(xdr);
        BOMShiftID.xdrEncode(xdr);
        TransAccount.xdrEncode(xdr);
        TransactionValue.xdrEncode(xdr);
        PaymentMeans.xdrEncode(xdr);
        AfterTxn.xdrEncode(xdr);
        { int $size = 2; for ( int $idx = 0; $idx < $size; ++$idx ) { CardIdentificationCode[$idx].xdrEncode(xdr); } }
        BankID.xdrEncode(xdr);
        TransOrigin.xdrEncode(xdr);
        SPTSN.xdrEncode(xdr);
        BankSN.xdrEncode(xdr);
        paySetday.xdrEncode(xdr);
        paytool.xdrEncode(xdr);
        paytype.xdrEncode(xdr);
        { int $size = 8; for ( int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        OtherTicketComm = new OtherTicketComm_t(xdr);
        UpdateType = new U8_t(xdr);
        OperatorID = new OperatorID_t(xdr);
        BOMShiftID = new BOMShiftID_t(xdr);
        TransAccount = new U32_t(xdr);
        TransactionValue = new U32_t(xdr);
        PaymentMeans = new PaymentMeans_t(xdr);
        AfterTxn = new U32_t(xdr);
        { int $size = 2; CardIdentificationCode = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { CardIdentificationCode[$idx] = new U32_t(xdr); } }
        BankID = new U16_t(xdr);
        TransOrigin = new U8_t(xdr);
        SPTSN = new SN_t(xdr);
        BankSN = new SN_t(xdr);
        paySetday = new Date2_t(xdr);
        paytool = new U8_t(xdr);
        paytype = new U8_t(xdr);
        { int $size = 8; Rsvd = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx] = new U32_t(xdr); } }
    }

}
// End of TXQpayUpdate_t.java
