package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TXSJTChangeEntryExit_t implements XdrAble {
    public ACCTicketComm_t accTicketComm;
    public U8_t entryExitBit;
    public StationID_t entryStationID;
    public AFCTime_t entryDateTime;
    public ValueCent_t transactionValue;
    public RecycleSJTFlag_t recycleSJTFlag;
    public U32_t containerID;
    public U32_t changeSN;

    public TXSJTChangeEntryExit_t() {
    }

    public TXSJTChangeEntryExit_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        accTicketComm.xdrEncode(xdr);
        entryExitBit.xdrEncode(xdr);
        entryStationID.xdrEncode(xdr);
        entryDateTime.xdrEncode(xdr);
        transactionValue.xdrEncode(xdr);
        recycleSJTFlag.xdrEncode(xdr);
        containerID.xdrEncode(xdr);
        changeSN.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        accTicketComm = new ACCTicketComm_t(xdr);
        entryExitBit = new U8_t(xdr);
        entryStationID = new StationID_t(xdr);
        entryDateTime = new AFCTime_t(xdr);
        transactionValue = new ValueCent_t(xdr);
        recycleSJTFlag = new RecycleSJTFlag_t(xdr);
        containerID = new U32_t(xdr);
        changeSN = new U32_t(xdr);
    }

}
// End of TXSJTChangeEntryExit_t.java
