package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TXSJTInit_t implements XdrAble {
    public ACCTicketComm_t accTicketComm;
    public U8_t issueTaskType;
    public ValueCent_t transactionValue;
    public OperatorID_t operatorID;
    public Date2_t initDate;

    public TXSJTInit_t() {
    }

    public TXSJTInit_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        accTicketComm.xdrEncode(xdr);
        issueTaskType.xdrEncode(xdr);
        transactionValue.xdrEncode(xdr);
        operatorID.xdrEncode(xdr);
        initDate.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        accTicketComm = new ACCTicketComm_t(xdr);
        issueTaskType = new U8_t(xdr);
        transactionValue = new ValueCent_t(xdr);
        operatorID = new OperatorID_t(xdr);
        initDate = new Date2_t(xdr);
    }

}
// End of TXSJTInit_t.java
