package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TXSJTSale_t implements XdrAble {
    public ACCTicketComm_t accTicketComm;
    public OperatorID_t operatorID;
    public BOMShiftID_t bomShiftID;
    public ValueCent_t transactionValue;
    public MediaType_t mediaType;
    public PaymentMeans_t paymentMeans;
    public Duration_t duration;

    public TXSJTSale_t() {
    }

    public TXSJTSale_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        accTicketComm.xdrEncode(xdr);
        operatorID.xdrEncode(xdr);
        bomShiftID.xdrEncode(xdr);
        transactionValue.xdrEncode(xdr);
        mediaType.xdrEncode(xdr);
        paymentMeans.xdrEncode(xdr);
        duration.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        accTicketComm = new ACCTicketComm_t(xdr);
        operatorID = new OperatorID_t(xdr);
        bomShiftID = new BOMShiftID_t(xdr);
        transactionValue = new ValueCent_t(xdr);
        mediaType = new MediaType_t(xdr);
        paymentMeans = new PaymentMeans_t(xdr);
        duration = new Duration_t(xdr);
    }

}
// End of TXSJTSale_t.java
