package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TXSJTBlock_t implements XdrAble {
    public ACCTicketComm_t accTicketComm;
    public OperatorID_t operatorID;
    public BOMShiftID_t bomShiftID;
    public U8_t blockReason;

    public TXSJTBlock_t() {
    }

    public TXSJTBlock_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        accTicketComm.xdrEncode(xdr);
        operatorID.xdrEncode(xdr);
        bomShiftID.xdrEncode(xdr);
        blockReason.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        accTicketComm = new ACCTicketComm_t(xdr);
        operatorID = new OperatorID_t(xdr);
        bomShiftID = new BOMShiftID_t(xdr);
        blockReason = new U8_t(xdr);
    }

}
// End of TXSJTBlock_t.java
