package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TXSJTRefund_t implements XdrAble {
    public ACCTicketComm_t accTicketComm;
    public OperatorID_t operatorID;
    public StationID_t StationID_t;
    public PaymentMeans_t paymentMeans;
    public ValueCent_t transactionValue;

    public TXSJTRefund_t() {
    }

    public TXSJTRefund_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        accTicketComm.xdrEncode(xdr);
        operatorID.xdrEncode(xdr);
        StationID_t.xdrEncode(xdr);
        paymentMeans.xdrEncode(xdr);
        transactionValue.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        accTicketComm = new ACCTicketComm_t(xdr);
        operatorID = new OperatorID_t(xdr);
        StationID_t = new StationID_t(xdr);
        paymentMeans = new PaymentMeans_t(xdr);
        transactionValue = new ValueCent_t(xdr);
    }

}
// End of TXSJTRefund_t.java
