package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TXSVTCPUCheck_t implements XdrAble {
    public OtherTicketComm_t OtherTicketComm;
    public OperatorID_t operatorID;
    public BOMShiftID_t bomShiftID;
    public UnicodeString_t Name;
    public U8_t IdCardType;
    public java.lang.String IdNumber;
    public U32_t[] Rsvd;

    public TXSVTCPUCheck_t() {
    }

    public TXSVTCPUCheck_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        OtherTicketComm.xdrEncode(xdr);
        operatorID.xdrEncode(xdr);
        bomShiftID.xdrEncode(xdr);
        Name.xdrEncode(xdr);
        IdCardType.xdrEncode(xdr);
        xdr.xdrEncodeString(IdNumber);
        { int $size = 4; for ( int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        OtherTicketComm = new OtherTicketComm_t(xdr);
        operatorID = new OperatorID_t(xdr);
        bomShiftID = new BOMShiftID_t(xdr);
        Name = new UnicodeString_t(xdr);
        IdCardType = new U8_t(xdr);
        IdNumber = xdr.xdrDecodeString();
        { int $size = 4; Rsvd = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx] = new U32_t(xdr); } }
    }

}
// End of TXSVTCPUCheck_t.java
