package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TXSVTInit_t implements XdrAble {
    public ACCTicketComm_t accTicketComm;
    public U8_t issueTaskType;
    public ValueCent_t transactionValue;
    public ValueCent_t balanceValue;
    public U32_t cardCode;
    public U32_t expireDate;
    public U8_t corpType;
    public U16_t departmentId;
    public U8_t rideLevel;
    public U8_t gender;
    public U8_t identType;
    public U32_t identNo;
    public UnicodeString_t holderName;
    public java.lang.String holderNo;
    public OperatorID_t operatorID;
    public Date2_t initDate;

    public TXSVTInit_t() {
    }

    public TXSVTInit_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        accTicketComm.xdrEncode(xdr);
        issueTaskType.xdrEncode(xdr);
        transactionValue.xdrEncode(xdr);
        balanceValue.xdrEncode(xdr);
        cardCode.xdrEncode(xdr);
        expireDate.xdrEncode(xdr);
        corpType.xdrEncode(xdr);
        departmentId.xdrEncode(xdr);
        rideLevel.xdrEncode(xdr);
        gender.xdrEncode(xdr);
        identType.xdrEncode(xdr);
        identNo.xdrEncode(xdr);
        holderName.xdrEncode(xdr);
        xdr.xdrEncodeString(holderNo);
        operatorID.xdrEncode(xdr);
        initDate.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        accTicketComm = new ACCTicketComm_t(xdr);
        issueTaskType = new U8_t(xdr);
        transactionValue = new ValueCent_t(xdr);
        balanceValue = new ValueCent_t(xdr);
        cardCode = new U32_t(xdr);
        expireDate = new U32_t(xdr);
        corpType = new U8_t(xdr);
        departmentId = new U16_t(xdr);
        rideLevel = new U8_t(xdr);
        gender = new U8_t(xdr);
        identType = new U8_t(xdr);
        identNo = new U32_t(xdr);
        holderName = new UnicodeString_t(xdr);
        holderNo = xdr.xdrDecodeString();
        operatorID = new OperatorID_t(xdr);
        initDate = new Date2_t(xdr);
    }

}
// End of TXSVTInit_t.java
