package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TXSVTCPUChangeEntryExit_t implements XdrAble {
    public OtherTicketComm_t OtherTicketComm;
    public U8_t entryExitBit;
    public StationID_t entryStationID;
    public DeviceID_t entryDeviceID;
    public AFCTime_t entryDateTime;
    public U32_t TransAccount;
    public U32_t TransactionValue;
    public U16_t YKTCityCode;
    public U8_t ConsumerKeyVersion;
    public U8_t ConsumerKeyIndex;
    public U32_t AfterTxn;
    public U32_t[] CardIdentificationCode;
    public U8_t AlgorithmIdentification;
    public U32_t discountFlag;
    public U16_t multiTripDiscountCode;
    public U8_t discountType;
    public ValueCent_t discountValue;
    public U32_t discountRatio;
    public U8_t pointDiscountCode;
    public U32_t CurrentBonus;
    public U32_t AccumulationBonus;
    public U32_t OverLimit;
    public U32_t changeSN;
    public U32_t[] Rsvd;

    public TXSVTCPUChangeEntryExit_t() {
    }

    public TXSVTCPUChangeEntryExit_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        OtherTicketComm.xdrEncode(xdr);
        entryExitBit.xdrEncode(xdr);
        entryStationID.xdrEncode(xdr);
        entryDeviceID.xdrEncode(xdr);
        entryDateTime.xdrEncode(xdr);
        TransAccount.xdrEncode(xdr);
        TransactionValue.xdrEncode(xdr);
        YKTCityCode.xdrEncode(xdr);
        ConsumerKeyVersion.xdrEncode(xdr);
        ConsumerKeyIndex.xdrEncode(xdr);
        AfterTxn.xdrEncode(xdr);
        { int $size = 2; for ( int $idx = 0; $idx < $size; ++$idx ) { CardIdentificationCode[$idx].xdrEncode(xdr); } }
        AlgorithmIdentification.xdrEncode(xdr);
        discountFlag.xdrEncode(xdr);
        multiTripDiscountCode.xdrEncode(xdr);
        discountType.xdrEncode(xdr);
        discountValue.xdrEncode(xdr);
        discountRatio.xdrEncode(xdr);
        pointDiscountCode.xdrEncode(xdr);
        CurrentBonus.xdrEncode(xdr);
        AccumulationBonus.xdrEncode(xdr);
        OverLimit.xdrEncode(xdr);
        changeSN.xdrEncode(xdr);
        { int $size = 6; for ( int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        OtherTicketComm = new OtherTicketComm_t(xdr);
        entryExitBit = new U8_t(xdr);
        entryStationID = new StationID_t(xdr);
        entryDeviceID = new DeviceID_t(xdr);
        entryDateTime = new AFCTime_t(xdr);
        TransAccount = new U32_t(xdr);
        TransactionValue = new U32_t(xdr);
        YKTCityCode = new U16_t(xdr);
        ConsumerKeyVersion = new U8_t(xdr);
        ConsumerKeyIndex = new U8_t(xdr);
        AfterTxn = new U32_t(xdr);
        { int $size = 2; CardIdentificationCode = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { CardIdentificationCode[$idx] = new U32_t(xdr); } }
        AlgorithmIdentification = new U8_t(xdr);
        discountFlag = new U32_t(xdr);
        multiTripDiscountCode = new U16_t(xdr);
        discountType = new U8_t(xdr);
        discountValue = new ValueCent_t(xdr);
        discountRatio = new U32_t(xdr);
        pointDiscountCode = new U8_t(xdr);
        CurrentBonus = new U32_t(xdr);
        AccumulationBonus = new U32_t(xdr);
        OverLimit = new U32_t(xdr);
        changeSN = new U32_t(xdr);
        { int $size = 6; Rsvd = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx] = new U32_t(xdr); } }
    }

}
// End of TXSVTCPUChangeEntryExit_t.java
