package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TXSVTCPUNonImmediateRefund_t implements XdrAble {
    public OtherTicketComm_t OtherTicketComm;
    public Date2_t StartUseDate;
    public AFCTime_t ConfirmTimeAtAcc;
    public OperatorID_t OperatorIDAtAcc;
    public java.lang.String Apply;
    public UnicodeString_t Name;
    public U8_t IdCardType;
    public java.lang.String IdNumber;
    public java.lang.String TelephoneCode;
    public U8_t AccTicketStatus;
    public Date2_t ValidDateAtACC;
    public ValueCent_t balanceValueAtACC;
    public ValueCent_t forgiveValueAtACC;
    public ValueCent_t ForgiveValue;
    public U8_t RefundReason;
    public ValueCent_t DepreciationValue;
    public ValueCent_t refundFee;
    public ValueCent_t TransactionValue;
    public BOMShiftID_t bomShiftID;
    public OperatorID_t operatorID;
    public U32_t[] Rsvd;

    public TXSVTCPUNonImmediateRefund_t() {
    }

    public TXSVTCPUNonImmediateRefund_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        OtherTicketComm.xdrEncode(xdr);
        StartUseDate.xdrEncode(xdr);
        ConfirmTimeAtAcc.xdrEncode(xdr);
        OperatorIDAtAcc.xdrEncode(xdr);
        xdr.xdrEncodeString(Apply);
        Name.xdrEncode(xdr);
        IdCardType.xdrEncode(xdr);
        xdr.xdrEncodeString(IdNumber);
        xdr.xdrEncodeString(TelephoneCode);
        AccTicketStatus.xdrEncode(xdr);
        ValidDateAtACC.xdrEncode(xdr);
        balanceValueAtACC.xdrEncode(xdr);
        forgiveValueAtACC.xdrEncode(xdr);
        ForgiveValue.xdrEncode(xdr);
        RefundReason.xdrEncode(xdr);
        DepreciationValue.xdrEncode(xdr);
        refundFee.xdrEncode(xdr);
        TransactionValue.xdrEncode(xdr);
        bomShiftID.xdrEncode(xdr);
        operatorID.xdrEncode(xdr);
        { int $size = 4; for ( int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        OtherTicketComm = new OtherTicketComm_t(xdr);
        StartUseDate = new Date2_t(xdr);
        ConfirmTimeAtAcc = new AFCTime_t(xdr);
        OperatorIDAtAcc = new OperatorID_t(xdr);
        Apply = xdr.xdrDecodeString();
        Name = new UnicodeString_t(xdr);
        IdCardType = new U8_t(xdr);
        IdNumber = xdr.xdrDecodeString();
        TelephoneCode = xdr.xdrDecodeString();
        AccTicketStatus = new U8_t(xdr);
        ValidDateAtACC = new Date2_t(xdr);
        balanceValueAtACC = new ValueCent_t(xdr);
        forgiveValueAtACC = new ValueCent_t(xdr);
        ForgiveValue = new ValueCent_t(xdr);
        RefundReason = new U8_t(xdr);
        DepreciationValue = new ValueCent_t(xdr);
        refundFee = new ValueCent_t(xdr);
        TransactionValue = new ValueCent_t(xdr);
        bomShiftID = new BOMShiftID_t(xdr);
        operatorID = new OperatorID_t(xdr);
        { int $size = 4; Rsvd = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx] = new U32_t(xdr); } }
    }

}
// End of TXSVTCPUNonImmediateRefund_t.java
