package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TXSVTSaleDeposit_t implements XdrAble {
    public ACCTicketComm_t accTicketComm;
    public U32_t expireDate;
    public U32_t enableDate;
    public ValueCent_t transactionValue;
    public ValueCent_t balanceValue;
    public ValueCent_t forgiveValue;
    public PaymentMeans_t paymentMeans;
    public OperatorID_t operatorID;
    public BOMShiftID_t bomShiftID;

    public TXSVTSaleDeposit_t() {
    }

    public TXSVTSaleDeposit_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        accTicketComm.xdrEncode(xdr);
        expireDate.xdrEncode(xdr);
        enableDate.xdrEncode(xdr);
        transactionValue.xdrEncode(xdr);
        balanceValue.xdrEncode(xdr);
        forgiveValue.xdrEncode(xdr);
        paymentMeans.xdrEncode(xdr);
        operatorID.xdrEncode(xdr);
        bomShiftID.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        accTicketComm = new ACCTicketComm_t(xdr);
        expireDate = new U32_t(xdr);
        enableDate = new U32_t(xdr);
        transactionValue = new ValueCent_t(xdr);
        balanceValue = new ValueCent_t(xdr);
        forgiveValue = new ValueCent_t(xdr);
        paymentMeans = new PaymentMeans_t(xdr);
        operatorID = new OperatorID_t(xdr);
        bomShiftID = new BOMShiftID_t(xdr);
    }

}
// End of TXSVTSaleDeposit_t.java
