package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TXSVTCPUImmediateRefund_t implements XdrAble {
    public OtherTicketComm_t OtherTicketComm;
    public Date2_t StartUseDate;
    public U8_t AccTicketStatus;
    public ValueCent_t ForgiveValue;
    public U8_t RefundReason;
    public ValueCent_t DepreciationValue;
    public ValueCent_t refundFee;
    public ValueCent_t TransactionValue;
    public BOMShiftID_t bomShiftID;
    public OperatorID_t operatorID;
    public U32_t[] Rsvd;

    public TXSVTCPUImmediateRefund_t() {
    }

    public TXSVTCPUImmediateRefund_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        OtherTicketComm.xdrEncode(xdr);
        StartUseDate.xdrEncode(xdr);
        AccTicketStatus.xdrEncode(xdr);
        ForgiveValue.xdrEncode(xdr);
        RefundReason.xdrEncode(xdr);
        DepreciationValue.xdrEncode(xdr);
        refundFee.xdrEncode(xdr);
        TransactionValue.xdrEncode(xdr);
        bomShiftID.xdrEncode(xdr);
        operatorID.xdrEncode(xdr);
        { int $size = 4; for ( int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        OtherTicketComm = new OtherTicketComm_t(xdr);
        StartUseDate = new Date2_t(xdr);
        AccTicketStatus = new U8_t(xdr);
        ForgiveValue = new ValueCent_t(xdr);
        RefundReason = new U8_t(xdr);
        DepreciationValue = new ValueCent_t(xdr);
        refundFee = new ValueCent_t(xdr);
        TransactionValue = new ValueCent_t(xdr);
        bomShiftID = new BOMShiftID_t(xdr);
        operatorID = new OperatorID_t(xdr);
        { int $size = 4; Rsvd = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx] = new U32_t(xdr); } }
    }

}
// End of TXSVTCPUImmediateRefund_t.java
