package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TXSVTCPUUpdate_t implements XdrAble {
    public OtherTicketComm_t OtherTicketComm;
    public U8_t UpdateType;
    public OperatorID_t OperatorID;
    public BOMShiftID_t BOMShiftID;
    public U32_t TransAccount;
    public U32_t TransactionValue;
    public PaymentMeans_t PaymentMeans;
    public U16_t YKTCityCode;
    public U8_t ConsumerKeyVersion;
    public U8_t ConsumerKeyIndex;
    public U32_t AfterTxn;
    public U32_t[] CardIdentificationCode;
    public U8_t AlgorithmIdentification;
    public U32_t OverLimit;
    public U32_t[] Rsvd;

    public TXSVTCPUUpdate_t() {
    }

    public TXSVTCPUUpdate_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        OtherTicketComm.xdrEncode(xdr);
        UpdateType.xdrEncode(xdr);
        OperatorID.xdrEncode(xdr);
        BOMShiftID.xdrEncode(xdr);
        TransAccount.xdrEncode(xdr);
        TransactionValue.xdrEncode(xdr);
        PaymentMeans.xdrEncode(xdr);
        YKTCityCode.xdrEncode(xdr);
        ConsumerKeyVersion.xdrEncode(xdr);
        ConsumerKeyIndex.xdrEncode(xdr);
        AfterTxn.xdrEncode(xdr);
        { int $size = 2; for ( int $idx = 0; $idx < $size; ++$idx ) { CardIdentificationCode[$idx].xdrEncode(xdr); } }
        AlgorithmIdentification.xdrEncode(xdr);
        OverLimit.xdrEncode(xdr);
        { int $size = 7; for ( int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        OtherTicketComm = new OtherTicketComm_t(xdr);
        UpdateType = new U8_t(xdr);
        OperatorID = new OperatorID_t(xdr);
        BOMShiftID = new BOMShiftID_t(xdr);
        TransAccount = new U32_t(xdr);
        TransactionValue = new U32_t(xdr);
        PaymentMeans = new PaymentMeans_t(xdr);
        YKTCityCode = new U16_t(xdr);
        ConsumerKeyVersion = new U8_t(xdr);
        ConsumerKeyIndex = new U8_t(xdr);
        AfterTxn = new U32_t(xdr);
        { int $size = 2; CardIdentificationCode = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { CardIdentificationCode[$idx] = new U32_t(xdr); } }
        AlgorithmIdentification = new U8_t(xdr);
        OverLimit = new U32_t(xdr);
        { int $size = 7; Rsvd = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx] = new U32_t(xdr); } }
    }

}
// End of TXSVTCPUUpdate_t.java
