package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TXSVTCPUInit_t implements XdrAble {
    public OtherTicketComm_t OtherTicketComm;
    public U8_t issueTaskType;
    public TicketPrintID_t TicketPrintID;
    public U32_t BatchNumbe;
    public U32_t transactionValue;
    public U32_t AfterTxn;
    public U8_t corpType;
    public U16_t departmentId;
    public U8_t rideLevel;
    public U8_t gender;
    public U8_t IdCardType;
    public U32_t identNo;
    public UnicodeString_t Name;
    public java.lang.String IdNumber;
    public OperatorID_t operatorID;
    public Date2_t initDate;
    public U8_t AccTicketStatus;
    public U32_t[] Rsvd;

    public TXSVTCPUInit_t() {
    }

    public TXSVTCPUInit_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        OtherTicketComm.xdrEncode(xdr);
        issueTaskType.xdrEncode(xdr);
        TicketPrintID.xdrEncode(xdr);
        BatchNumbe.xdrEncode(xdr);
        transactionValue.xdrEncode(xdr);
        AfterTxn.xdrEncode(xdr);
        corpType.xdrEncode(xdr);
        departmentId.xdrEncode(xdr);
        rideLevel.xdrEncode(xdr);
        gender.xdrEncode(xdr);
        IdCardType.xdrEncode(xdr);
        identNo.xdrEncode(xdr);
        Name.xdrEncode(xdr);
        xdr.xdrEncodeString(IdNumber);
        operatorID.xdrEncode(xdr);
        initDate.xdrEncode(xdr);
        AccTicketStatus.xdrEncode(xdr);
        { int $size = 3; for ( int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        OtherTicketComm = new OtherTicketComm_t(xdr);
        issueTaskType = new U8_t(xdr);
        TicketPrintID = new TicketPrintID_t(xdr);
        BatchNumbe = new U32_t(xdr);
        transactionValue = new U32_t(xdr);
        AfterTxn = new U32_t(xdr);
        corpType = new U8_t(xdr);
        departmentId = new U16_t(xdr);
        rideLevel = new U8_t(xdr);
        gender = new U8_t(xdr);
        IdCardType = new U8_t(xdr);
        identNo = new U32_t(xdr);
        Name = new UnicodeString_t(xdr);
        IdNumber = xdr.xdrDecodeString();
        operatorID = new OperatorID_t(xdr);
        initDate = new Date2_t(xdr);
        AccTicketStatus = new U8_t(xdr);
        { int $size = 3; Rsvd = new U32_t[$size]; for (int $idx = 0; $idx < $size; ++$idx ) { Rsvd[$idx] = new U32_t(xdr); } }
    }

}
// End of TXSVTCPUInit_t.java
