package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TXYKTUpdate_t implements XdrAble {
    public YKTTicketComm_t yktTicketComm;
    public U8_t updateType;
    public OperatorID_t operatorID;
    public BOMShiftID_t bomShiftID;
    public PaymentMeans_t paymentMeans;

    public TXYKTUpdate_t() {
    }

    public TXYKTUpdate_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        yktTicketComm.xdrEncode(xdr);
        updateType.xdrEncode(xdr);
        operatorID.xdrEncode(xdr);
        bomShiftID.xdrEncode(xdr);
        paymentMeans.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        yktTicketComm = new YKTTicketComm_t(xdr);
        updateType = new U8_t(xdr);
        operatorID = new OperatorID_t(xdr);
        bomShiftID = new BOMShiftID_t(xdr);
        paymentMeans = new PaymentMeans_t(xdr);
    }

}
// End of TXYKTUpdate_t.java
