package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TXYKTAdmin_t implements XdrAble {
    public YKTTicketComm_t yktTicketComm;
    public UnicodeString_t TnxComment;
    public OperatorID_t operatorID;
    public BOMShiftID_t bomShiftID;

    public TXYKTAdmin_t() {
    }

    public TXYKTAdmin_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        yktTicketComm.xdrEncode(xdr);
        TnxComment.xdrEncode(xdr);
        operatorID.xdrEncode(xdr);
        bomShiftID.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        yktTicketComm = new YKTTicketComm_t(xdr);
        TnxComment = new UnicodeString_t(xdr);
        operatorID = new OperatorID_t(xdr);
        bomShiftID = new BOMShiftID_t(xdr);
    }

}
// End of TXYKTAdmin_t.java
