package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TXYKTChangeEntryExit_t implements XdrAble {
    public YKTTicketComm_t yktTicketComm;
    public U8_t entryExitBit;
    public StationID_t entryStationID;
    public AFCTime_t entryDateTime;
    public U32_t changeSN;

    public TXYKTChangeEntryExit_t() {
    }

    public TXYKTChangeEntryExit_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        yktTicketComm.xdrEncode(xdr);
        entryExitBit.xdrEncode(xdr);
        entryStationID.xdrEncode(xdr);
        entryDateTime.xdrEncode(xdr);
        changeSN.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        yktTicketComm = new YKTTicketComm_t(xdr);
        entryExitBit = new U8_t(xdr);
        entryStationID = new StationID_t(xdr);
        entryDateTime = new AFCTime_t(xdr);
        changeSN = new U32_t(xdr);
    }

}
// End of TXYKTChangeEntryExit_t.java
