package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class TXYKTSaleDeposit_t implements XdrAble {
    public YKTTicketComm_t yktTicketComm;
    public U16_t forgiveValue;
    public PaymentMeans_t paymentMeans;
    public U32_t OnlineTnxSeq;
    public OperatorID_t operatorID;
    public BOMShiftID_t bomShiftID;

    public TXYKTSaleDeposit_t() {
    }

    public TXYKTSaleDeposit_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        yktTicketComm.xdrEncode(xdr);
        forgiveValue.xdrEncode(xdr);
        paymentMeans.xdrEncode(xdr);
        OnlineTnxSeq.xdrEncode(xdr);
        operatorID.xdrEncode(xdr);
        bomShiftID.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        yktTicketComm = new YKTTicketComm_t(xdr);
        forgiveValue = new U16_t(xdr);
        paymentMeans = new PaymentMeans_t(xdr);
        OnlineTnxSeq = new U32_t(xdr);
        operatorID = new OperatorID_t(xdr);
        bomShiftID = new BOMShiftID_t(xdr);
    }

}
// End of TXYKTSaleDeposit_t.java
