package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class UDComm_t implements XdrAble {
    public AFCTime_t TransactionDateTime;
    public SAMID_t TACSamID;
    public DeviceID_t DeviceID;
    public int TransactionType;
    public ModeCode_t ModeCode;

    public UDComm_t() {
    }

    public UDComm_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        TransactionDateTime.xdrEncode(xdr);
        TACSamID.xdrEncode(xdr);
        DeviceID.xdrEncode(xdr);
        xdr.xdrEncodeInt(TransactionType);
        ModeCode.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        TransactionDateTime = new AFCTime_t(xdr);
        TACSamID = new SAMID_t(xdr);
        DeviceID = new DeviceID_t(xdr);
        TransactionType = xdr.xdrDecodeInt();
        ModeCode = new ModeCode_t(xdr);
    }

}
// End of UDComm_t.java
