package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class UserPriviledgeRole_t implements XdrAble {
    public U16_t roleId;
    public UnicodeString_t roleName;
    public U32_t [] roleFunctionList;

    public UserPriviledgeRole_t() {
    }

    public UserPriviledgeRole_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        roleId.xdrEncode(xdr);
        roleName.xdrEncode(xdr);
        { int $size = roleFunctionList.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { roleFunctionList[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        roleId = new U16_t(xdr);
        roleName = new UnicodeString_t(xdr);
        { int $size = xdr.xdrDecodeInt(); roleFunctionList = new U32_t[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { roleFunctionList[$idx] = new U32_t(xdr); } }
    }

}
// End of UserPriviledgeRole_t.java
