package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class UserCardM1Key_t implements XdrAble {
    public U8_t sectorId;
    public U8_t keyCryptFlag;
    public java.lang.String sectorKey;

    public UserCardM1Key_t() {
    }

    public UserCardM1Key_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        sectorId.xdrEncode(xdr);
        keyCryptFlag.xdrEncode(xdr);
        xdr.xdrEncodeString(sectorKey);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        sectorId = new U8_t(xdr);
        keyCryptFlag = new U8_t(xdr);
        sectorKey = xdr.xdrDecodeString();
    }

}
// End of UserCardM1Key_t.java
