package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class VersionItem_t implements XdrAble {
    public U8_t versionType;
    public int parameterType;
    public U16_t versionNo;

    public VersionItem_t() {
    }

    public VersionItem_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        versionType.xdrEncode(xdr);
        xdr.xdrEncodeInt(parameterType);
        versionNo.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        versionType = new U8_t(xdr);
        parameterType = xdr.xdrDecodeInt();
        versionNo = new U16_t(xdr);
    }

}
// End of VersionItem_t.java
