package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Word_t implements XdrAble {
    public U16_t areaNumber;
    public U16_t wordXPos;
    public U16_t wordYPos;
    public U16_t wordWidth;
    public U16_t wordHeight;
    public UnicodeString_t wordContent;
    public java.lang.String wordSize;
    public U8_t R;
    public U8_t G;
    public U8_t B;

    public Word_t() {
    }

    public Word_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        areaNumber.xdrEncode(xdr);
        wordXPos.xdrEncode(xdr);
        wordYPos.xdrEncode(xdr);
        wordWidth.xdrEncode(xdr);
        wordHeight.xdrEncode(xdr);
        wordContent.xdrEncode(xdr);
        xdr.xdrEncodeString(wordSize);
        R.xdrEncode(xdr);
        G.xdrEncode(xdr);
        B.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        areaNumber = new U16_t(xdr);
        wordXPos = new U16_t(xdr);
        wordYPos = new U16_t(xdr);
        wordWidth = new U16_t(xdr);
        wordHeight = new U16_t(xdr);
        wordContent = new UnicodeString_t(xdr);
        wordSize = xdr.xdrDecodeString();
        R = new U8_t(xdr);
        G = new U8_t(xdr);
        B = new U8_t(xdr);
    }

}
// End of Word_t.java
