package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class YktBlackList_t implements XdrAble {
    public TicketLogicalID_t ticketID;
    public U8_t processFlag;

    public YktBlackList_t() {
    }

    public YktBlackList_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        ticketID.xdrEncode(xdr);
        processFlag.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        ticketID = new TicketLogicalID_t(xdr);
        processFlag = new U8_t(xdr);
    }

}
// End of YktBlackList_t.java
