package com.svgtopng.entity.xdr;/*
 * Automatically generated by jrpcgen 1.0.7 on 2024/11/8 ����5:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class YKTTicketComm_t implements XdrAble {
    public ChipType_t ChipType;
    public U32_t CardSN;
    public U16_t CityCode;
    public U16_t BusinessCode;
    public U32_t IssueBatch;
    public U32_t CardAuthen;
    public U8_t CardType;
    public U16_t CountIntotal;
    public U32_t valuePreTx;
    public U32_t valueTx;
    public int testFlag;
    public U8_t cardVerNo;

    public YKTTicketComm_t() {
    }

    public YKTTicketComm_t(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        ChipType.xdrEncode(xdr);
        CardSN.xdrEncode(xdr);
        CityCode.xdrEncode(xdr);
        BusinessCode.xdrEncode(xdr);
        IssueBatch.xdrEncode(xdr);
        CardAuthen.xdrEncode(xdr);
        CardType.xdrEncode(xdr);
        CountIntotal.xdrEncode(xdr);
        valuePreTx.xdrEncode(xdr);
        valueTx.xdrEncode(xdr);
        xdr.xdrEncodeInt(testFlag);
        cardVerNo.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        ChipType = new ChipType_t(xdr);
        CardSN = new U32_t(xdr);
        CityCode = new U16_t(xdr);
        BusinessCode = new U16_t(xdr);
        IssueBatch = new U32_t(xdr);
        CardAuthen = new U32_t(xdr);
        CardType = new U8_t(xdr);
        CountIntotal = new U16_t(xdr);
        valuePreTx = new U32_t(xdr);
        valueTx = new U32_t(xdr);
        testFlag = xdr.xdrDecodeInt();
        cardVerNo = new U8_t(xdr);
    }

}
// End of YKTTicketComm_t.java
